### PR TITLE
Adding Arxiv Search

### PR DESCRIPTION
**Pull request by Koobah**
### Documentation

documented in-code. 

Changes in prompt
- added function as available command
- fixed numbering of commands
- clarified that browse website command can also be used to read articles
- clarified that agents do not have access to external data/web - agents were created to answer questions not available in "known" data.

### Test Plan

I have tested this by running multiple prompts.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thouroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by Slowly-Grokking — COMMENTED** [review]
arxiv search is a great idea.   I think changing to an unordered list as suggested [here](https://github.com/Torantulino/Auto-GPT/pull/880) might be a good idea.

might have to think about adding scholar.google.com too.

**Comment by nponeccop** [comment]
@Koobah There are conflicts now

**Review by nponeccop — APPROVED** [review]

**Comment by nponeccop** [comment]
@Koobah There are conflicts again due to constant merging

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Pwuts** [comment]
This would be perfect as a plugin! It's out of scope for the core repo though, so we won't be merging this PR. Check out the instructions for creating a plugin here: https://github.com/Significant-Gravitas/Auto-GPT-Plugins#creating-a-plugin

Also, feel free to join in on the action on Discord. Ping me there if you have further questions. :)

**Pull request closed without merging**
