### PR TITLE
Add ability to only install plugin deps, install them on image build

### PR DESCRIPTION
**Pull request by erik-megarad**
### Background

When using plugins you will need to install all of the dependencies of _every_ plugin _every_ time you start up the container. This is a bit annoying when developing plugins since you need to restart the container regularly. With this change the dependencies will be installed on image build, so that at start-up dependencies are only installed if they're different than what the image had at build time. This makes container start-up way way faster.

### Changes

- Adds a command-line argument to _only_ install deps (and not run the actual program)
- Run this command when building the docker image

### Documentation

- Just the documentation in the CLI option

### Test Plan

- I tested manually. AFAICT there aren't any tests covering the CLI. I would like to add some but that seems out of scope for such a small change.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes. 
- [x] I have run the following commands against my code to ensure it passes our linters:
    ```shell
    black .
    isort .
    mypy
    autoflake --remove-all-unused-imports --recursive --ignore-init-module-imports autogpt tests --in-place
    ```

### CODE REVIEW

**Review by Pwuts — CHANGES_REQUESTED** [review]
It makes little sense to install them during image build, because this will not work for normal end-users. Instead, we could install plugin deps to a custom folder and mount that folder as a docker volume so it is persisted across runs.

**Comment by erik-megarad** [comment]
Why wouldn't it work for normal end-users? It seems like it would be good for end-users to have the packages already installed.

**Comment by Pwuts** [comment]
At build time we do not know what plugins a user will want to use, so we would have to install all dependencies for all available plugins in the release image...

**Comment by erik-megarad** [comment]
Oh, I understand. I should've said that the intent for this change is optimization and not a replacement. What would be installed on build are the "base packages" so that they don't need to be installed every container startup. If a user adds more packages that need to be installed only those new packages need to be installed on startup.

**Comment by Pwuts** [comment]
What are the base packages?

**Comment by erik-megarad** [comment]
The base packages are in the requirements.txt file of Auto-GPT. Including dependencies there are 184 python packages. This change saves at least 45 seconds on container startup time, and I have an extremely fast network connection (6ms ping from the CDN, gigabit bandwidth).

**Comment by Pwuts** [comment]
Then I stand by my earlier comments

**Comment by ntindle** [comment]
Not sure if this is the best way to handle this. @Pwuts why not install them as reasonable defaults?

**Comment by erik-megarad** [comment]
I don't particularly care how it is handled but it's super annoying when developing a plugin, it takes over a minute to just cycle the container to reload your code change.

**Comment by Pwuts** [comment]
Completely understandable, and I would definitely like to fix that. Installing a second set of dependencies (from the plugin repo) in the release image is not a scalable solution though (imo).

From my earlier review:
> Instead, we could install plugin deps to a custom folder and mount that folder as a docker volume so it is persisted across runs.

More specifically, 2 ways to speed up package installation:
* At runtime: volume mount to persist `~/.cache/pip`
* At build time: (BuildKit in-build cache mounts)[https://stackoverflow.com/a/57282479]

**Comment by erik-megarad** [comment]
I'll do this a different way later

**Pull request closed without merging**
