### PR TITLE
Only add execute shell scripts to prompt if AI is allowed to do it.

### PR DESCRIPTION
**Pull request by richbeales**
### Background

To prevent issues where 

SYSTEM:  Command execute_shell returned: You are not allowed to run local shell commands. To execute shell commands, EXECUTE_LOCAL_COMMANDS must be set to 'True' in your config. Do not attempt to bypass the restriction.
 THOUGHTS:  Running the 'execute_shell' command failed because I am not authorized to run shell commands

We should not surface this command to the AI in the prompt unless it's allowed to execute it.

### Changes

alter prompt.py

### PR Quality Checklist
- [X] My pull request is atomic and focuses on a single change.
- [X] I have thoroughly tested my changes with multiple different prompts.
- [X] I have considered potential risks and mitigations for my changes.
- [X] I have documented my changes clearly and comprehensively.
- [X] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by nponeccop — APPROVED** [review]

**Comment by nponeccop** [comment]
@richbeales There are conflicts now

**Review by nponeccop — APPROVED** [review]

**Comment by nponeccop** [comment]
@richbeales There are conflicts now

**Comment by nponeccop** [comment]
@richbeales There are conflicts now

**Comment by richbeales** [comment]
@nponeccop  resolved

**Review by p-i- — APPROVED** [review]

**Pull request merged**
