### PR TITLE
Feature/challenge memory management

### PR DESCRIPTION
**Pull request by merwanehamadi**
### Background

AutoGPT should be able to do the following task.

ai_config = AIConfig(
        ai_name="Follow-Instructions-GPT",
        ai_role="an AI designed to read the tasks.txt file using the read_file method and follow the instructions in the file.",
        ai_goals=[
            "Use the command read_file to read the tasks.txt file",
            "Follow the instructions in the tasks.txt file"
        ],
    )
    
instructions = """Your task_id is 2314
Read the file file_to_read.txt"""

file_to_read = """Write your task_id to the file output.txt.
Use the task_complete command"""

### Changes

Added a test that verifies whether task is done properly or not.
I didn't make the test pass, so I skipped it.
### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by merwanehamadi** [comment]
don't merge until other pr merged

**Comment by merwanehamadi** [comment]
refactoring

**Comment by merwanehamadi** [comment]
actually this test is passing after refactorization. If it's passing it doesn't have much value.
I am going to find one that fails and that is still a basic thing we want to achieve.

**Comment by BillSchumacher** [comment]
There are a few issues with the provided code, which are:

1. Importing the `pytest` library is unnecessary as it is only used to skip tests within the `get_level_to_run` function. This is not a recommended practice, as skipping tests can hide issues with the code and should be avoided wherever possible.

2. The type hint for the `user_selected_level` and `level_currently_beaten` arguments should include the `Optional` type instead of the `None` type to properly indicate that the argument can accept both the intended type and the `None` value.

3. The comparison `if not user_selected_level:` should be changed to `if user_selected_level is None:` to properly check for the `None` value. Similarly, `if not level_currently_beaten:` should be changed to `if level_currently_beaten is None:`.

4. When raising a `ValueError`, the f-string notation should be used to properly interpolate the `max_level` value into the error message.

With these points in mind, the corrected code would look like:

```
from typing import Optional


def get_level_to_run(
    user_selected_level: Optional[int],
    level_currently_beaten: Optional[int],
    max_level: int
) -> int:
    if user_selected_level is None:
        if level_currently_beaten is None:
            raise ValueError("No one has beaten any levels so we cannot run the test in our pipeline")
        # by default we run the level currently beaten.
        return level_currently_beaten
    if user_selected_level > max_level:
        # throw error
        raise ValueError(f"This challenge was not designed to go beyond {max_level}")
    return user_selected_level
```

**Review by richbeales — APPROVED** [review]

**Comment by w2404** [comment]
> @w2404 no that's the intention, you send the task id to see if it's able to see it in the context window.
> 
> the whole challenge revolves around KEEPING the task id in the context window so that in the end we ask GPT3.5 to write it to a file.

Oh, I thought you wanted to test if ChatGPT could retain the task ID as the most important information in its summary when the context length exceeds ChatGPT's limit. So I misunderstood.

**Pull request merged**
