### PR TITLE
fixes #1821 by installing required drivers and adding options to chro…

### LINKED ISSUE #1821: SYSTEM:  Command browse_website returned: Error: Message: Service /home/appuser/.wdm/drivers/chromedriver/linux64/112.0.5615.49/chromedriver unexpectedly exited. Status code was: 127
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

1. Build a dockerized version of aouto-gpt
2. Give it any instruction that leads to it needing to browse_website

### Current behavior 😯

SYSTEM:  Command browse_website returned: Error: Message: Service /home/appuser/.wdm/drivers/chromedriver/linux64/112.0.5615.49/chromedriver unexpectedly exited. Status code was: 127

### Expected behavior 🤔

Should be bale to browse website properly

### Your prompt 📝

```yaml
# It really could be any prompt
```

### PR DESCRIPTION
**Pull request by psvensson**
…medriver

### Background

The web_browse functionality has been broken in the Docker container (and possibly outside it) for a day or two. 
This PR adds a number of needed libraries and options when invoking the chromium webdriver which fixes the problems (see #1821 for example)

### Changes

New libraries apt-got in Dockerfile + more options to the chromium creation

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by shahdevansh — DISMISSED** [review]
Works for me

**Comment by bvoo** [comment]
tested and can also confirm working

**Review by shahdevansh — DISMISSED** [review]

**Review by DarkShadowG — DISMISSED** [review]

**Comment by nponeccop** [comment]
@psvensson There are lint errors now

**Comment by psvensson** [comment]
hmm OK. The only thing left in my PR is one line in the Dockerfile. Is this where the lint errors are?

**Comment by psvensson** [comment]
Ah hang on, I see it. thx

**Review by p-i- — APPROVED** [review]

**Comment by vmajor** [comment]
Does not work for me: Command browse_website returned: Error: Message: Service /home/*****/.wdm/drivers/chromedriver/linux64/112.0.5615.49/chromedriver unexpectedly exited. Status code was: 127

**Comment by psvensson** [comment]
> Does not work for me: Command browse_website returned: Error: Message: Service /home/*****/.wdm/drivers/chromedriver/linux64/112.0.5615.49/chromedriver unexpectedly exited. Status code was: 127

Are you testing in docker (just want to make sure)?

**Comment by vmajor** [comment]
No, native in WSL2 in a conda venv. chrome fails with that error, firefox fails with "user profile not found" error even though it is meant to be headless and it runs fine with a gui when started manually. I will try to run Auto-GPT under windows next.

**Comment by universeroc** [comment]
Not works for me natively run on CentOS with conda env, how to fix it? help me thanks in advance:)

**Pull request merged**
