### PR TITLE
This commit fixes the JSON parser and execute_python methods so they work better with GPT-3.5 - Updated

### PR DESCRIPTION
**Pull request by SuperYeti**
I've integrated the comments from the [Previous PR](/Torantulino/Auto-GPT/pull/844) and recreating for a clean PR here. 

1. There was a bug in the JSON fixer in the parser, it was never making it to the code that tries to extract JSON if the AI returned text before the JSON packet.
2. GPT-3.5-Turbo keeps trying to execute_python_file with code. Added a execute_python_code method that saves the python code to a UUID named file, that is then passed to the execute_python_file method. Also changed the drive binding for docker that is launched to RW so that execute python code is able to write output files etc.
3. Updated the prompt to try and get GPT-3.5-Turbo to respond with just JSON more consistently.
4. execute_code.py was not using safe_join to ensure that files outside the workspace directory can't be executed. Updated.

### PR Quality Checklist
- [X] My pull request is atomic and focuses on a single change.
- [X] I have thouroughly tested my changes with multiple different prompts.
- [X] I have considered potential risks and mitigations for my changes.
- [X] I have documented my changes clearly and comprehensively.
- [X] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by brunosan** [comment]
Changes here were helpful to me. +1

**Comment by onekum** [comment]
I think this PR could be much more atomic. I'd consider separating each of the four changes into their own PRs. Then again, I'm not the one of the people who decides if this can be merged.

**Review by nponeccop — CHANGES_REQUESTED** [review]
Split it up into 3 PRs: 
- Prompt changes
- JSON parser changes
- execute_python changes

**Comment by nponeccop** [comment]
@SuperYeti There are conflicts now

**Comment by SuperYeti** [comment]
Thanks. I'll break into 3 new separate PR's and resubmit and fix the
conflicts while I'm in there.

Warren

**Pull request closed without merging**
