### PR TITLE
add mode for python execution

### PR DESCRIPTION
**Pull request by Igniscode**
divide docker mode and venv mode for python execution

### Background
To run execute_python_file, which is currently built into autogpt, user needs to install docker and create docker-image separately, which you feel is unnecessary and unreasonable. (I watched multiple issues because of this, for example #92 #1896 )
It is likely to be a difficult task for beginners or those who are not familiar with Docker use.

### Changes
Therefore, in python execution, the venv mode and the Docker mode were separated and implemented so that the user could choose how to execute the code in the .env file.

### Documentation
Relevant information is annotated in code as comments

### Test Plan
Same environment, I tested docker mode(legacy) and venv mode and they work same.

### PR Quality Checklist
- [v ] My pull request is atomic and focuses on a single change.
- [v ] I have thoroughly tested my changes with multiple different prompts.
- [v ] I have considered potential risks and mitigations for my changes.
- [v ] I have documented my changes clearly and comprehensively.
- [v ] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Boostrix** [comment]
if this is committed "as is", it would make sense for auto-gpt to run inside a separate environment - i.e. using chroot or ideally using a dedicated "autogpt" user. That way, there's another layer of security added when it comes to $HOME

**Comment by Igniscode** [comment]
> if this is committed "as is", it would make sense for auto-gpt to run inside a separate environment - i.e. using chroot or ideally using a dedicated "autogpt" user. That way, there's another layer of security added when it comes to $HOME
> 
> The same restriction should then apply for execute_shell commands obviously. if $USER is not "autogpt", the script should internally disable code execution completely.

Thank you for the excellent feedback on my request. While using venv provides some minimum security, adding a new account seems like a much safer idea.

**Comment by Boostrix** [comment]
I did copy that advice into the source tree and opened a corresponding PR: 
- #3961

**Comment by Igniscode** [comment]
> I did copy that advice into the source tree and opened a corresponding PR:
> 
> * [encourage people to use a separate user account w/o VM/docker #3961](https://github.com/Significant-Gravitas/Auto-GPT/pull/3961)

Cool! I will also consider implementing rules for executing code based on user permissions.

**Comment by Boostrix** [comment]
sure, they won't accept multiple features in a single PR anyway

**Comment by Pwuts** [comment]
Does venv provide the same degree of sandboxing as docker?

**Comment by Boostrix** [comment]
No.

**Comment by Pwuts** [comment]
Since venv does not provide the same degree of sandboxing as docker, they are only interchangeable if the user knows what they are doing and have purposefully disabled the workspace restriction.

**Pull request closed without merging**
