### PR TITLE
chore: refactor auto_fix

### PR DESCRIPTION
**Pull request by 53jk1**
### PR Quality Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [ ] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [ ] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by nponeccop — APPROVED** [review]

**Comment by richbeales** [comment]
Conflicting files
autogpt/json_fixes/auto_fix.py

**Comment by 53jk1** [comment]
@richbeales fixed

**Review by nponeccop — DISMISSED** [review]

**Comment by nponeccop** [comment]
@53jk1 CI failed

**Comment by 53jk1** [comment]
@nponeccop fixed

**Comment by nponeccop** [comment]
@53jk1 There are conflicts again

**Pull request closed without merging**
