### PR TITLE
Add webpage exploration functionality

### PR DESCRIPTION
**Pull request by c0ldWeather**
### PR Quality Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [ ] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [ ] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by drikusroor** [comment]
Could this PR perhaps have been created by an Auto-GPT instance itself, or? 😅  If not, could you please update your PR title & description so that we know your PR intends to add/change?

**Comment by nponeccop** [comment]
@drikusroor  No, it is a language model. It would have written excellent descriptions

@c0ldWeather The PR title doesn't look right. And there are conflicts now

**Comment by richbeales** [comment]
please re-title

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Pull request closed without merging**
