### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by dorelidan**
### Change Safety

- [ ] I have added tests to cover my changes
- [ ] I have considered potential risks and mitigations for my changes

### CODE REVIEW

**Review by coleyr — COMMENTED** [review]
This isnt needed as the req file gets added via the copy of the scripts folder

**Comment by ksylvan** [comment]
Duplicate of https://github.com/Torantulino/Auto-GPT/pull/228

FYI @coleyr

1. There is no requirements.txt in the scripts folder, so the `Dockerfile` currently does not work.
2. It's better to copy the top-level directory, not just the `scripts/` folder, since we then get the ai_settings.yaml and anything else we need in the image.

I'm building the docker image from my fork automatically here: https://hub.docker.com/r/kayvan/auto-gpt and the updated README in the PR #228 also gives examples of usage (including how to volume-bind your `.env` file into the container)

**Review by Lucyan11 — APPROVED** [review]

**Comment by coleyr** [comment]
Hey thanks for the correction, I see that now! I think I conflated the root dir... Anyway, thanks for pointing that out.

**Comment by nponeccop** [comment]
Duplicate of #455 as well

**Comment by nponeccop** [comment]
Note that #228 was rejected as not atomic

**Review by hogmaster — APPROVED** [review]
I have tested this change and docker build . works now.

**Review by hogmaster — COMMENTED** [review]
I have added COPY requirements.txt requirements.txt to the Dockerfile. 
docker build works.

**Comment by nponeccop** [comment]
@Torantulino Duplicate of #226

**Comment by richbeales** [comment]
closing as this is now implemented, thanks

**Pull request closed without merging**
