### PR TITLE
Added speech support from agent running in docker in linux

### PR DESCRIPTION
**Pull request by rame0**
### Background
Speech does not work when running on Docker container.

### Changes
* An additional Dockerfile (`speech_linux.Dockerfile`) has been added to provide support for audio output from a container.
* Changed `docker-compose.yml` to allow for a custom Dockerfile.
* Added volumes to `docker-compose.yml` that bind the host sound to the container.

### Documentation
Added comments to `docker-compose.yml`

### Test Plan
Tested on Manjaro Linux. 

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes 

No tests added because the actual code doesn't change.

### CODE REVIEW

**Comment by k-boikov** [comment]
I think we should find a better way to manage this than uncommenting Dockerfile lines.

**Comment by rame0** [comment]
> I think we should find a better way to manage this than uncommenting Dockerfile lines.

Agree, but that what I come up with so far. Will try to find better solution.

The reasons of uncommenting in `docker-compose.yml` right now is

1. to have different Dokckerfiles, because, I think (can't test) this sound solution will not work on Windows
2. to still have Dockerfile without sound, because it creates smaller image

The solution might be: creating second service (let's say `auto-gpt-speek`) in `docker-compose.yml` with settings for sound. And run like that: 
```bash
docker-compose run --build --rm auto-gpt-speek
```

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by ntindle** [comment]
Take a look at: https://docs.docker.com/compose/profiles/

**Comment by Pwuts** [comment]
Since there has been no activity in the past 2+ months, I'm closing this as stale. Feel free to bump, comment here or ping me (on [discord]) if you want to fix up this PR or if you want to discuss further.

[discord]: https://discord.gg/autogpt

**Pull request closed without merging**
