### PR TITLE
Correct and clean up JSON handling

### PR DESCRIPTION
**Pull request by erik-megarad**
### Background
We had a bunch of hacks to get around JSON errors. Turns out there were two issues:

The JSON coming from OpenAI is actually not JSON. It's a Python Dict that's been stringified like `str(dict)`.

The second issue is that we weren't correctly feeding the AI the JSON schema. It recognizes the same schema that we use to validate the response, so this works much better.

This may also fix the "no command given" errors but I will need to test more.

### Changes

- Use `ast.literal_eval` to reverse the `str()` process that was done by OpenAI
- Update the prompt to include the exact JSON schema
- Remove a ton of now-useless code
- Catch and log errors better

### Test Plan

- Tested a bunch locally
- Multiple challenge runs
- Added json validation tests

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes. 
- [x] I have run the following commands against my code to ensure it passes our linters:
    ```shell
    black .
    isort .
    mypy
    autoflake --remove-all-unused-imports --recursive --ignore-init-module-imports --ignore-pass-after-docstring autogpt tests --in-place
    ```

### CODE REVIEW

**Comment by merwanehamadi** [comment]
@erik-megarad ast.literal_eval doesn't work with booleans true or false. why use it ?

**Comment by erik-megarad** [comment]
Oh, it doesn't, does it. However, there aren't booleans allowed in our validation schema so it should never come up.

I'm using `ast.literal_eval` because it works with the escaped version of the JSON coming in from the OpenAI client.

**Comment by erik-megarad** [comment]
Actually I think I do need to change this. `args` is an object which could potentially have a boolean in it.

**Comment by erik-megarad** [comment]
Update from discord: Using `ast.literal_eval` is correct because OpenAI serializes the response content using python's `str` function (it's not json apparently!). Subsequently `ast.literal_eval` reverses that process.

**Review by merwanehamadi — APPROVED** [review]

**Comment by merwanehamadi** [comment]
@erik-megarad ok I reran the benchmark for JSON errors and it's 0/50.

**Review by merwanehamadi — APPROVED** [review]

**Comment by Pwuts** [comment]
Nice! Nit: I see `_test_json_parser.py` was left behind ;)

**Comment by Androbin** [comment]
Exciting news: We can finally get rid of this JSON cleanup mess entirely!

>Developers can now describe functions to `gpt-4-0613` and `gpt-3.5-turbo-0613`, and have the model intelligently choose to output a JSON object containing arguments to call those functions. This is a new way to more reliably connect GPT's capabilities with external tools and APIs.

>These models have been fine-tuned to both detect when a function needs to be called (depending on the user’s input) and to respond with JSON that adheres to the function signature. Function calling allows developers to more reliably get structured data back from the model. For example, developers can:

https://openai.com/blog/function-calling-and-other-api-updates

**Pull request merged**
