### PR TITLE
allow plugins to be loaded from folders and don't crash on exceptions

### PR DESCRIPTION
**Pull request by VPelt**
### Background
In order to make plugin development (or just plugin installing & updating) easier it should be possible to load plugins without the code be in a zib format. Furthermore changes in the template can cause a specific plugin to stop loading. This shouldn't crash autogpt as a whole.

This way i can git checkout the plugins repository into the plugins folder and it 'just works'. See also the discussion https://github.com/Significant-Gravitas/Auto-GPT/issues/3654

### Changes

- allow plugins to be loaded from regular folders in addition to be loaded from inside zib archives
- if a plugin fails to load don't crash autogpt but display a warning with the error and continue loading other plugins

### Test Plan

I tested loading plugins both in zip and non-zib format

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes. 
- [x] I have run the following commands against my code to ensure it passes our linters:
    ```shell
    black .
    isort .
    mypy
    autoflake --remove-all-unused-imports --recursive --ignore-init-module-imports autogpt tests --in-place
    ```

### CODE REVIEW

**Comment by Boostrix** [comment]
the two of you should team up - by the way, that's why it's a good idea to always communicate your plans upfront, and that is why it's possible to create "draft PRs"

**Comment by erik-megarad** [comment]
There are lots of rad refactorings, log statements, and catches in here. I think they're great but can we change this PR to be just for the improvements to logging/exceptions, and then move folder-loading to my PR? https://github.com/Significant-Gravitas/Auto-GPT/pull/4548

My PR covers just folder-loading, but none of the improvements you've made. My PR adds requirements scanning which is necessary if we're going to enable folder-loading. LMK what you think.

**Comment by Boostrix** [comment]
Sounds good to me

**Comment by VPelt** [comment]
I'm happy to work together. I'll look at it in more detail on Monday

**Comment by Boostrix** [comment]
note that it's generally a good idea to mutually review your PRs and to ensure that the CI pipeline is happy (by adding/extending tests/coverage as needed)

**Comment by Pwuts** [comment]
Closing this as resolved in #4548 :)

**Pull request closed without merging**
