### PR TITLE
Feature/pathlib for ai config

### PR DESCRIPTION
**Pull request by Back2Basics**
### Background
formerly PR #647.  I put this change in and before the PR could be accepted the file changed format and moved to a different folder.

### Changes
pathlib.Path instead of os.path for readability and removing a try/except as a bonus.

### Test Plan
Tried it with 2 different runs of autogpt one with and without a ai_settings.yaml file.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by nponeccop** [comment]
@Back2Basics, could you kindly clarify whether this is a reiteration of an earlier pull request? If so, could you please add the corresponding number to the "Background" section of the pull request description? Thank you.

**Comment by Back2Basics** [comment]
Done.  Let me know if there is more.

**Review by AdnanAhmed14 — APPROVED** [review]

**Comment by nponeccop** [comment]
@Back2Basics There are conflicts now

**Comment by dschonholtz** [comment]
I'm looking forward to this. This is gonna solve a bug I'm hitting

**Comment by Back2Basics** [comment]
> I'm looking forward to this. This is gonna solve a bug I'm hitting

Thank you for the note.  You are one other person's comments made this worth it.

**Pull request closed without merging**
