### PR TITLE
DRAFT : Project Abstraction Layer

### PR DESCRIPTION
**Pull request by ph-ausseil**
**UNFINISHED do not accept, this is to share advancements**

### Background
Implementation of ideas regrouped in #3392 for the project level. The implementation should be fully backward compatible. The implementation migrate the current ai_settings.yaml to a project structure but do not change the core , it change the back end.

* Now = AutoGPT can have 1 agent
* New back-end = AutoGPT can have 1 project with 1 agent
* Future = AutoGPT can have N project with 1 agent each 
* Future ++ = AutoGPT can have N project with N agent each 

The new back-end is further detailed in REAME.md
* AIConfig, is an empty class that inherit from AgentModel (for backward compatibility without changing core variable name)
* AgentModel, is a representation of an Agent and manage CRU of an Agent.
* Project, is a common goal to various Agent and manage CRU of this project and D of Agent (not yet implemented)
* ProjectsBroker, create & manage projects

### Changes
* ➕Documentation : Created a projects/readme.md to help user & developper alike to work on the projects
* ➕Tests : 3 new pytest files
* ⛔️ `AIConfig` : Fully removed and kept for backward compatibility so the core is not modified
* ➕ `AgentModel` : Added
* ➕ `Project` : Added
* ➕ `ProjectsBroker` : Added

Changes that affect core : 
* ⚡ `prompt.py` a consequence of the abstraction layer was that `def construct_full_prompt(ai_config, prompt_generator: Optional[PromptGenerator] = None) -> str:` had to be moved out `AIConfig` 
* ⚡ 1 line in main.py to reflect the change above

Risk : 
* Manage circular imports as the backward compatibility requires imports from Agent to ProjectBroker & the setup is designed to work with imports from ProjectBroker to Agent.

### Documentation
* Every method will be fully doc stringed
* README.md created
* Variable created in .env template should be documented if any
* Any twitch inserted for backward compatibility must have a # TODO and if possible PROJECT-DEPRECATED tag.

### Test Plan
* Unit test with pytest 
* Publication of the branch on Discord & request for testers. 

Scenarii : 

MVP : 
* [x] Start a first instance of AutoGPT without ai_settings.yaml
* [ ] Start an instance of AutoGPT with ai_settings.yaml 
* [x] For any of the instance above save & quit after after at least 1 interaction with the agent
* [ ] Start the instance above and see if the agent can load (type y)  & quit after after at least 1 interaction with the agent
* [ ] Start the instance above and see if we can create a new agent(type n)  & quit after after at least 1 interaction with the agent

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change. 
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes. **FULL BACKWARD COMPATIBILITY**
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes 

### Additional informations : 

To loop back on features gathered in #3392  : 

- [x] AgentTeam object
- [x] Dynamic / Extensible Agent (the agent is constructed dynamically allowing flexibility. & plug-ins)
- [ ] Dynamic / Extensible Project
- [ ] Dynamic / Extensible Agent Team
- [ ] Status
- [ ] State awareness
- [ ] Implement folder per agent
- [x] Agent unique ID
- [ ] Agent budget
- [ ] Agent budget consumption
- [ ] Project open_api_key

**YAML** 
Option implemented :  Option 3 
```
my_project/
├─── team
│          ├── leader : 
│          ├─────────────  agent 1
│          └── specialized_agents : 
│          ├─────────────   agent 2
│          ├─────────────   agent 3
│          ├─────────────  agent 4
```

**Folder** 
Option implemented : Option 1 , could be a MVP
```
autogpt
├── projects
│      ├── project_1
│      │   ├── settings.yaml
│      ├── project_2
│      │   ├── settings.yaml
│      └── ...
```

### CODE REVIEW

**Comment by ntindle** [comment]
Can’t review right now but make sure there’s abstractions to swap the relevant portions of this out when needed

**Comment by ph-ausseil** [comment]
To show progress : 
This is a use case for first time use (no ai_settings)
https://user-images.githubusercontent.com/303427/235340440-6d48f149-4379-49fa-8a0c-08713b57a8db.mov

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Pwuts** [comment]
What's the status of this subproject?

**Comment by Boostrix** [comment]
my 2c, working on support multiple agents/project is all nice and dandy, but probably should only be worked on once we have at least /some/ form of planning support and a way to support persistent workspaces, so that agents can be safely suspended/resumed (restarted after crashing).

Tackling this any other way will complicate this part of the re-arch IMO

**Comment by ph-ausseil** [comment]
Nah I believe you did well, ToT should be part of planning :)

But gestion of teams may be more related to the command registry .
* My attempt was : Command Registry is a list of agent somme managing tools
(such as files)
* HF implementation : Commande registry is split in a list of tool and a
list of agent

Advantage of my implementation :
Saving character when context is limited with a shorter registry because
files operations (move, copy, read, write , delete , ect...) could be
managed in an agent.
May be simpler

Advantage of HF :
May be simpler

Still I like the HF approach as I choose this path because of a technical
constraint that should disappear with augmentation of context lengths.

**Comment by Boostrix** [comment]
the re-arch channel does have a dedicated "commands" thread - however, personally, I believe we should use a "namespace" based notation (namespace.tool) - that would be a good way to give more hints to the LLM.

Currently, the LLM tends to loop/cycle unnecessarily, for example when trying to analyze a problem, it keeps calling "analyze_code"

By using a namespace prefix, we could provide additional meta information to the LLM using a well-known syntax

**Comment by ph-ausseil** [comment]
It is relevant but it can be implemented whether this lead agent has a
command_registry or an agent_registry, in my work (I'm using my memory) , I
created 2 agents for the sake of demonstration
"LeadAgent" and FileManagerAgent which names I believe will give you hint
to what they can do. There could be ImageManageragent or CoderAgent
with specific ML.

There was two reasons to put my job on hold :

   - I was quitting my job and had a lot to do until the end of my contract
   31/05 :)
   - I was extending Agent through monkey patches because this has been
   estimated out of scope since day 1

I believe there are good and bad.

### For the good,
I took some distance which is easier to criticise what got done, what could
have been done differently. For instance, __I  guess it is very hard to
figure__ , but project-related are interesting as they give a semantic
meaning to the highest level of interaction, but if we visualise Projects
as a tree/arborescences of agents , then a "Project" could be view as a
lead agent at the root of the tree, this agent having a specifics loadings
functions :)

I actually like the semanting meaning of the class, but it could be
non-necessary complexity and I actually haven't made my mind on it. I just
know that I would never had the idea if I haven't taken that distance for a
month.

### For the bad,
I think I could have make most of it in parallel to the rearch have I had
few inputs :) , this activity was not at all on the "critical path" and I
believe that the "lets do this and considers others things laters" approach
was a mistake which affected my motivation tbh.


Le jeu. 1 juin 2023 à 16:32, Pierre-Henri AUSSEIL ***@***.***> a
écrit :

> Nah I believe you did well, ToT should be part of planning :)
>
> But gestion of teams may be more related to the command registry .
> * My attempt was : Command Registry is a list of agent somme managing
> tools (such as files)
> * HF implementation : Commande registry is split in a list of tool and a
> list of agent
>
> Advantage of my implementation :
> Saving character when context is limited with a shorter registry because
> files operations (move, copy, read, write , delete , ect...) could be
> managed in an agent.
> May be simpler
>
> Advantage of HF :
> May be simpler
>
> Still I like the HF approach as I choose this path because of a technical
> constraint that should disappear with augmentation of context lengths.
>
>

**Comment by ph-ausseil** [comment]
Also for the sake of argument, I believe that ToT and agent_registry approach may have synergies

**Comment by ph-ausseil** [comment]
Checked my code, and for I wrote a dummy MidjourneyAgent . I could explain
why I believe it’s better to extend an Agent base class with a Midjourney +
a Dalle + a foo + a bar class than a generic ImageGeneratorClass.

In this view of Agent Registry, agents are like plug-ins and I can make
myself available to argue over different choices when times comes and there
is interest.

**Pull request closed without merging**
