### PR TITLE
Exclude logs files from source control

### PR DESCRIPTION
**Pull request by nicostubi**
### Background
Simply added *.log in .gitignore to avoid having all logs in staging area when working on the project

### Changes
Simply added *.log in .gitignore 

### Documentation
Simply added *.log in .gitignore 

### Test Plan
No test needed as simple change in .gitignore

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes 

No test needed as simple change in .gitignore

By submitting this, I agree that my pull request should be closed if I do not fill this out or follow the guide lines.

### CODE REVIEW

**Comment by nponeccop** [comment]
@nicostubi Can you fix the conflicts?

**Comment by nponeccop** [comment]
@nicostubi There are conflicts now

**Comment by nicostubi** [comment]
@nponeccop I can see that. Unable to reproduce them locally. I'm on it.

**Comment by nicostubi** [comment]
There has been a mix with another branch of mine. I will close this PR and open a new one.

**Comment by nicostubi** [comment]
There has been a mix with another branch of mine. I will close this PR and open a new one.

**Pull request closed without merging**
