### PR TITLE
More robust settings/onboarding stuff

### PR DESCRIPTION
**Pull request by gannonh**
### Background

Felt I need more optionality at start-up: load last settings, load setting file from your history or create new settings. The need came out of running different "missions" with changes to the settings and prompts. Wanted an easy way to recall previous settings 

### Changes

See new onboarding flow here: https://user-images.githubusercontent.com/1012888/230700981-90509b51-c38a-47d6-96bf-47519c91c6d3.mov

- Created new structure in scripts/data:
```bash
scripts/data/ai_settings
scripts/data/ai_settings/last_settings.yaml
scripts/data/ai_settings/history
scripts/data/ai_settings/history/settings_20230407-195943.yaml [every setting that is run is saved in the history dir]
```
- Refactored `main.py/construct_prompt` to support 3 onboarding options:
```bash
Welcome! Please select one of the following options:
a - Load last used settings
b - Load another settings file
c - Create new settings
```
- Refactored ai_config to support new i/o stuff

### Test Plan

- Manual testing throw each onboarding flow and i/o operation

### Change Safety

- [ ] I have added tests to cover my changes
- [ ] I have considered potential risks and mitigations for my changes

### CODE REVIEW

**Comment by coleyr** [comment]
Hey love this idea... seems like this would make it easier to share config files as you described 'missions'

**Comment by Boostrix** [comment]
I would also be interested in seeing this updated/integrated and reviewed, because it's heavily related to the benchmarking issue: #1359

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Pwuts** [comment]
Interesting proposal! Unfortunately we couldn't process it in time, and now the PR is so out of date we can't possibly merge it anymore. Thanks for submitting!

**Pull request closed without merging**
