### PR TITLE
feat: add HuggingFace API URL to .env.template

### PR DESCRIPTION
**Pull request by JeremyFabrikapp**
feat: add support for HuggingFace API URL in image_gen.py
feat: add HuggingFace API URL to Config class in config.py

### Background

The image gen could use a custom stable diffusion checkpoint, but the model url is actually hardcoded

### Changes

- Change image_gen.py to take env in account
- Change config.py to retrieve .env and set self.huggingface_api_url from HUGGINGFACE_API_URL

```python
self.huggingface_api_url = os.getenv("HUGGINGFACE_API_URL")
```

- Change .env.template
- Change README.md

### Documentation

Just adding a env, if it's not set it will fallback to current hardcoded url
```python
API_URL = CFG.huggingface_api_url or "https://api-inference.huggingface.co/models/CompVis/stable-diffusion-v1-4"
```

### Test Plan

Change .env var to one of the following, checkpoints are available here : 
[https://huggingface.co/docs/diffusers/v0.15.0/en/api/pipelines/stable_diffusion/text2img#diffusers.StableDiffusionPipeline](https://huggingface.co/docs/diffusers/v0.15.0/en/api/pipelines/stable_diffusion/text2img#diffusers.StableDiffusionPipeline)

- stable-diffusion-v1-4 (512x512 resolution) [CompVis/stable-diffusion-v1-4](https://huggingface.co/CompVis/stable-diffusion-v1-4)
- stable-diffusion-v1-5 (512x512 resolution) [runwayml/stable-diffusion-v1-5](https://huggingface.co/runwayml/stable-diffusion-v1-5)
- stable-diffusion-2-base (512x512 resolution): [stabilityai/stable-diffusion-2-base](https://huggingface.co/stabilityai/stable-diffusion-2-base)
- stable-diffusion-2 (768x768 resolution): [stabilityai/stable-diffusion-2](https://huggingface.co/stabilityai/stable-diffusion-2)
- stable-diffusion-2-1-base (512x512 resolution) [stabilityai/stable-diffusion-2-1-base](https://huggingface.co/stabilityai/stable-diffusion-2-1-base)
- stable-diffusion-2-1 (768x768 resolution): [stabilityai/stable-diffusion-2-1](https://huggingface.co/stabilityai/stable-diffusion-2-1)

### PR Quality Checklist
- [X] My pull request is atomic and focuses on a single change.
- [X] I have thoroughly tested my changes with multiple different prompts.
- [X] I have considered potential risks and mitigations for my changes.
- [X] I have documented my changes clearly and comprehensively.
- [X] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by nponeccop** [comment]
Can you put the documentation to Readme instead, to be uniform with other options?

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Pwuts** [comment]
Auto-GPT can use local Stable Diffusion instances; those have a separate section in the config. Is that not sufficient for what you're trying to achieve?

Also, this PR currently doesn't add any functionality because it only contains edits to README.md and .env.template

**Comment by Pwuts** [comment]
Since there hasn't been any activity on this PR in the past 3+ weeks, I'm closing it as stale. Feel free to ping me in the discord server if you want to discuss further. :)

**Pull request closed without merging**
