### PR TITLE
Added constraints and evaluations

### PR DESCRIPTION
**Pull request by javableu**
We can maybe improve the return message of the AI. To do this, we could give a list of straightforward instructions that can be passed to GPT-4. The text generated by a "stupid" AI will be of lower quality than the one generated by a "smart" AI. However, even a "stupid" AI can potentially produce results that match those of a "smart" AI. It certainly just needs more iteration, focus, and a list of simple instructions that he has to follow. It's important to have the AI think before he writes anything to autogpt ( critique-plan process of a single sentence).

1 Choose a sentence to work on.
2 Compose an impactful sentence.
3 Critique the sentence for clarity, coherence, grammar, and overall effectiveness. 4 Create a plan for revising the sentence, considering the critique. 5 Evaluate the plan to ensure it addresses the issues identified in the critique. 6 Refine the plan as needed.
7 Rephrase the sentence according to the refined plan. 8 Repeat steps 2-7 for additional sentences.
9 Merge the revised sentences.
10 Showcase the integrated text

For the performance evaluation, the AI has a tendency to be a bit adhd, Added refocusing criteria might help.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by nponeccop — DISMISSED** [review]

**Comment by javableu** [comment]
Since it impacts the main agent's behavior, it is really hard to understand the full implications of this update. It would be nice to have user feedback on this update to  see if people have noticed an improvement

**Comment by nponeccop** [comment]
Yes, the label "Needs benchmark" is exactly for that

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by merwanehamadi** [comment]
@javableu  we're currently building challenges and I really liked your work on this PR. Can I talk to you in voice ?

Please join use on Discord through this link https://discord.gg/autogpt (if not already)

DM me on the Auto-GPT discord channel (my discord is merwanehamadi).

**Comment by Boostrix** [comment]
> Since it impacts the main agent's behavior, it is really hard to understand the full implications of this update. It would be nice to have user feedback on this update to see if people have noticed an improvement

given that these PRs are such a common thing but due to the lack of testing data also so controversial, how about coming up with support for "prompt profiles", as in a shared folder with sub-folders that contain profiles for different prompts, so that people can tinker with different profiles without stepping on anyone's toes ?

Having this sort of infrastructure in place would also provide a good baseline for regression testing and benchmarking.
It would not directly be the solution proposed in #3858, but probably would be the only solution to have our cake and eat it, while also growing test data ?

**Comment by anonhostpi** [comment]
Constraints awareness issue - #3466

**Pull request closed without merging**
