### PR TITLE
Feature/adds taskfile

### PR DESCRIPTION
**Pull request by dbishoponline**
adds a taskfile for easier use of AutoGPT

### CODE REVIEW

**Comment by dbishoponline** [comment]
approved

**Comment by dbishoponline** [comment]
approve

**Comment by hdkiller** [comment]
There are unrelated changes in these commits.

**Comment by k-boikov** [comment]
Auto-GPT with Goodies would be your fork focused on macos and that cannot be merge in the core repo. Please get only the features you think can be useful for everybody and open separate PRs. And please follow the PR template.

**Pull request closed without merging**
