### PR TITLE
Fix JSON string escaping issue

### PR DESCRIPTION
**Pull request by PhilipAD**
Fixes an issue where double quotes were not being escaped in JSON strings, causing parse errors.

### CODE REVIEW

**Review by rmcsharry — DISMISSED** [review]
LGTM, nice quick fix! 👍

**Review by merwanehamadi — APPROVED** [review]

**Review by Arlodotexe — APPROVED** [review]

**Review by nponeccop — APPROVED** [review]
I guess this should be better documented. The current problem happens because of GPT behavior and may not be needed anymore when OpenAI improves the model or when someone improves the prompt. The PR is a clear improvement though.

**Review by richbeales — APPROVED** [review]

**Comment by nponeccop** [comment]
Resolve the conflicts.

**Review by Torantulino — APPROVED** [review]

**Comment by Torantulino** [comment]
While this does require a benchmark for definitive proof, It looks good and I'm happy to merge it.

**Comment by nponeccop** [comment]
@PhilipAD There are conflicts again

**Pull request merged**
