### PR TITLE
Improve extract_hyperlinks to honor base url

### PR DESCRIPTION
**Pull request by mharris717**

### CODE REVIEW

**Review by squishytiramisu — APPROVED** [review]

**Review by PhilipAD — DISMISSED** [review]
Lgtm

**Comment by mharris717** [comment]
@Torantulino approve/merge at your leisure.

**Comment by nponeccop** [comment]
There are no tests yet. Can you make a separate PR for CI/tests setup, with a dummy test suite?

**Comment by nponeccop** [comment]
And now there are conflicts, too.

**Review by BillSchumacher — APPROVED** [review]

**Pull request merged**
