### PR TITLE
Persuading AI to always give json in response with GPT-4

### PR DESCRIPTION
**Pull request by hbhere**
I asked GPT-4 to improve the part of the prompt about making sure it will give json in response

### Background

It would always get stuck giving one wrong line of JSON and then just keep saying "Sorry, here's the correct JSON:" and mess things up again. So I thought, why not ask GPT-4 to improve the prompt.

### Changes

Prompt improved to convince AI to always give correct json in response.

### Test Plan

Well, it's gotten better, this problem shows up less after I started using this prompt, so I thought I'd share it with everyone.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by brarrow** [comment]
Working better!

**Review by nponeccop — APPROVED** [review]

**Review by adylevy — APPROVED** [review]
👏🏻

**Comment by p-i-** [comment]
@hbhere 

Before merging, would someone care to experiment a little more rigorously with effective prompts?

This prompt seems unnecessarily verbose / token-eating.

The original prompt looks fishy:
```
Ensure the response can be parsed by Python json.loads
```
... can't json.loads parse an arbitrary string?

So it should be something like`Your response must be a valid JSON object, starting with { and ending with }`

Also, you don't say "please" when you are giving it an order. That gives it options. You don't have to be polite. You can't hurt its feelings.

**Comment by Androbin** [comment]
I totally agree with @p-i- that unnecessarily verbose prompts likely won't make things better. Early iterations of the DAN (Do Anything Now) jailbreak were unnecessarily verbose, and then people figured out the prompt could be MUCH shorter.

Maybe tell GPT-4 that its answer must be ***"machine readable"***, aka not in natural language.

**Comment by nponeccop** [comment]
@hbhere There are conflicts now

**Review by adylevy — CHANGES_REQUESTED** [review]
Checked the app many times with this new prompt, it doesn't solve the problem (nor making it worst)
it does add lots of tokens.

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by merwanehamadi** [comment]
@hbhere  we're currently building challenges and I would like to discuss with you.

Please join use on Discord through this link https://discord.gg/autogpt (if not already)

DM me on the Auto-GPT discord channel (my discord is merwanehamadi).

**Comment by Boostrix** [comment]
This is one of those prompt related PRs that could be closed immediately if auto-gpt had support for a folders with selectable "prompt profiles", as per: https://github.com/Significant-Gravitas/Auto-GPT/pull/1354#issuecomment-1537319307

**Pull request closed without merging**
