### PR TITLE
updated readme with python venv instructions

### PR DESCRIPTION
**Pull request by Salaah01**
### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by nponeccop — CHANGES_REQUESTED** [review]
Forcing venv on everyone doesn't seem right

**Comment by Salaah01** [comment]
It's bad practice to install Python packages globally as it can conflict with other packages on the system.
It's better practices to create a virtual environment per project.

**Comment by Salaah01** [comment]
There is a use case where you would want to install globally, which would typically be inside say a docker container. But these instructions are for when the use is installing them locally (evident by the fact that they are doing the whole git clone first).

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Salaah01** [comment]
When you have time to review this let me know. It's too time-consuming to keep on top of the merge conflicts.

**Comment by Pwuts** [comment]
Venv instructions are now in the docs

**Pull request closed without merging**
