### PR TITLE
[Hotfix] Fix coverage tooling

### PR DESCRIPTION
**Pull request by ntindle**
### Background

Minor issue with CI failing due to push events trying to upload coverage

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by hdkiller — APPROVED** [review]

**Comment by ntindle** [comment]
I hate that this is size/l

**Comment by Pwuts** [comment]
As mentioned in the original issue, we could just install Codecov. Easier to configure and doesn't require the same extensive permissions.

**Comment by ntindle** [comment]
Someone with full repo control would need to set that up and I’m not sure if it’s free

**Comment by richbeales** [comment]
CodeCov appears to be free for OSS projects.  We do need to fix the CI @Pwuts are you happy for this to be merged and we can check out codecov at a later date?

**Comment by ntindle** [comment]
If I get perms to add code cov, I’d love to. Otherwise I’d just like to get this working

**Comment by richbeales** [comment]
merged, better to fix CI now rather than wait for an unknown amount of time for a better solution.

**Pull request merged**
