### PR TITLE
fixed missing selenium requirements and adjusted Dockerfile COPY command

### PR DESCRIPTION
**Pull request by overkill32**
### PR Quality Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [ ] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [ ] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by nponeccop — APPROVED** [review]

**Comment by nponeccop** [comment]
@overkill32 There are conflicts now

**Review by Qoyyuum — APPROVED** [review]
I can confirm, this PR fixes the Docker build and running the docker container.

**Comment by Qoyyuum** [comment]
AutoGPT Docker PR fixes
#1406 
#1434

**Comment by nponeccop** [comment]
@overkill32 There are conflicts now

**Comment by Pwuts** [comment]
These changes are already in `master`, fixed by other PRs :)

**Comment by kala-here** [comment]
These changes got me in! Thanks!

**Comment by nponeccop** [comment]
@richbeales @p-i- Can you close if it's really a duplicate?

**Comment by overkill32** [comment]
Closing as fixed by other PRs

**Pull request closed without merging**
