### PR TITLE
Ask GPT-4 to respond with a compliant machine-readable JSON document

### PR DESCRIPTION
**Pull request by Androbin**
### Background

See #1042 @hbhere @p-i- 

### Changes

Tell GPT-4 that "Your response MUST be a compliant machine-readable JSON document."

### Test Plan

For testing, I got rid of any and all JSON cleanup code and I never experienced any issues.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by Androbin** [comment]
@p-i- I found that good word choice had a much greater effect than verbosity.

**Comment by Pegasust** [comment]
Out of curiosity, making it work with YAML instead of JSON? Since the structure of the command is not complex, the performance of parsing YAML instead of JSON shouldn't be a bottleneck.

Moreover, YAML is much much more flexible than JSON, I've had a lot of off-by-one JSON using gpt-3.5-turbo (miss comma here and there)

**Comment by Androbin** [comment]
@Pegasust I suspect that YAML would work much worse, it's actually less forgiving than JSON.

**Comment by Androbin** [comment]
@Pegasust Indentation amongst other things, GPT-4 doesn't exactly like to count. I don't think it makes sense to consider the `write_to_file` command to be a "special" case. With that being said, I do support the use of bullet points / unordered lists over ordered lists for the list of commands.

**Comment by Androbin** [comment]
@nponeccop Do we have a standard process for benchmarking?

**Comment by nponeccop** [comment]
@Androbin No. But it's an important issue. Create an issue.

**Review by nponeccop — APPROVED** [review]

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by merwanehamadi** [comment]
@Androbin   we're currently building challenges and I would like to discuss with you.

Please join use on Discord through this link https://discord.gg/autogpt (if not already)

DM me on the Auto-GPT discord channel (my discord is merwanehamadi).

**Comment by Boostrix** [comment]
I do understand that we're lacking benchmarks for this sort of thing, even though it looks/sounds plausible to me. But assuming that this is a controversial change, how about turning this into a CFG option so that it can be set up via the env by people wanting to tinker with this ? I'd suggest a dedicated category exactly for prompt engineering things like these. That way, accepting the PR should be a straightforward decision (defaulted to OFF for now), while those of us wanting to run the same ai_settings.yaml files with different prompts, could at least have the basic infrastructure in place.

If that could be considered, the PR should be safe to be reviewed/integrated regardless of the ongoing re-arch

What do you think ?

**Comment by Androbin** [comment]
Closing in favor of [Function calling](https://openai.com/blog/function-calling-and-other-api-updates)

**Pull request closed without merging**
