### PR TITLE
[DRAFT]LangChain integration

### PR DESCRIPTION
**Pull request by jonmatthis**
This PR is to start building in LangChain functionality to the Auto-GPT package. 

We'll start with a simple proof-of-viability, and then build out additional functionality from there

### Background

LangChain is a powerful, mature package that implements many of the LLM functionalities that are being used in Auto-GPT (e.g. memory, tool use, agents, etc) 

I would like to start developing an integrating LangChain into this project :D

### Changes
I made a folder called "experimental" with a (currently empty) class named "LangChain" - I will attempt to re-create some of the functionality currently implemented in Auto-GPT using LangChain methods (in preparation for using LangChain's more sophisticated methods to improve)

### Test Plan

I will start by re-creating current functionality using LangChain and validate that it gives similar function. Once this is functional, we can start building additional functionality that will extend the abilities of this package. 

I will include unit tests and end-to-end tests for each additional functionality 

### Change Safety

- [ ] I have added tests to cover my changes
- [ ] I have considered potential risks and mitigations for my changes

### CODE REVIEW

**Comment by jonmatthis** [comment]
> This should be marked as a Draft PR as it's WIP.

Yes, definitely - I edited the title to show that it's a draft. 

Is that the right way to do it, or is there another thing I should do?

**Comment by Dr33dM3** [comment]
this is not the right way to do it as we dont want to risk an merge right now when it is not ready to do this follow these steps.
1.Under your repository name, click Pull requests.
2.In the "Pull requests" list, click the pull request you'd like to convert to a draft.
3. In the right sidebar, under "Reviewers," click Convert to draft.
4.  5.Click Convert to draft.

**Comment by abcdcba3210123** [comment]
I am confused about the additional features of Auto-GPT compared to Langchain. Auto-GPT uses LLM to plan tasks and uses external APIs for execution, which seems to be the same as the “agents” in Langchain

**Comment by st4s1k** [comment]
> I am confused about the additional features of Auto-GPT compared to Langchain. Auto-GPT uses LLM to plan tasks and uses external APIs for execution, which seems to be the same as the “agents” in Langchain

@abcdcba3210123 why reinvent the bicycle? Opensource projects can help each other. If Auto-GPT project will require some changes and improvements in how agents work, then Auto-GPT team can open a PR in Langchain projects, plain and simple. This way the project can be more modular. There's beauty in separating responsibilities.

**Pull request closed without merging**
