### PR TITLE
Add Chinese Documentation & Fix Documentation Index Error

### PR DESCRIPTION
**Pull request by liyanes**
### Background

To add Chinese documentation.

### Changes

- Added the Chinese documentation.
- Fix a small error about index in documentation.

### Documentation

Nothing.

### Test Plan

Nothing.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by collijk** [comment]
We cannot commit to maintaining documentation in multiple languages. Any modern browser should be able to translate a webpage for you from English to any language you desire.

**Comment by collijk** [comment]
Hi, sorry for the miscommunication.  I see you've been talking to another maintainer in a different PR.  Give us a bit to determine what our policy is on this going forward.

**Comment by liyanes** [comment]
Emm... Actually, I don't recommend this form of documentation.
For multi-language environment, I can give an example: [Alist](https://github.com/alist-org/alist), its documentation is separatedly a [repository](https://github.com/alist-org/docs).
And it has a specialized website to host it: [https://alist.nn.ci/](https://alist.nn.ci/) (By Mkdocs)

From this perspective, we can do so to support other languages, and manage the code and docs effectively.

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by anonhostpi** [comment]
My opinion, but I think it is too early to propose localization support. This repo is 7 weeks old. We can barely support English 😅

**Comment by kinance** [comment]
I think we should just follow the [pattern](https://github.com/jonatasemidio/multilanguage-readme-pattern)

## STEPS
1. Create a README.md file in a different language
2. Name of the readme file must follow the `w3c` language pattern (README.<country IANA tag>.md). Ex README.pt-br.md
3. Link in the head of the original readme file and a link back in the current one
4. Use to be nice the shields.io style
.

**Pull request closed without merging**
