### PR TITLE
Add empty auto-gpt.json file in root folder

### PR DESCRIPTION
**Pull request by votanlean**
### Background
Too many people open issue about the warning 
`Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.`
For example: 
https://github.com/Significant-Gravitas/Auto-GPT/discussions/1057
https://github.com/Significant-Gravitas/Auto-GPT/issues/2178

### Changes
Add empty `auto-gpt.json` to the root folder

### Documentation
There is no documentation needed.

### Test Plan
I run the main script and found no more warning

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by k-boikov** [comment]
I was wondering is there a reason why the file is not in the repo? Or why doesn't the script that checks for it doesn't also create it?

**Comment by votanlean** [comment]
> I was wondering is there a reason why the file is not in the repo?

The file is in .gitignore and modified when using so it cannot put to the repo, just like .env

> Or why doesn't the script that checks for it doesn't also create it?

The default configuration is not saving local memory. Creating this file is optional and helps store local memory in the file.

**Comment by votanlean** [comment]
> I disagree, the file can be created (empty), then committed, then added to .gitignore so it will always be empty in the repo
=> Good to know, agree with this

> I agree that it is optional, but many people are asking about it and they are not expected to know how to make an empty JSON file.
=> So I think an empty `auto-gpt.json` file by default should be what most people want. If this is the case I can implement it in this PR and remove the instruction from the document so people do not need to be aware of it?

**Comment by k-boikov** [comment]
Yes, I would personally prefer to have the empty file.

**Comment by votanlean** [comment]
Just changed my PR to add an empty `auto-gpt.json` file to the root folder. Hope that will help others to not see the warning anymore.

**Comment by k-boikov** [comment]
LGTM

**Review by ntindle — APPROVED** [review]

**Comment by k-boikov** [comment]
Closing due to https://github.com/Significant-Gravitas/Auto-GPT/pull/3066

**Pull request closed without merging**
