### PR TITLE
Update prompt.txt

### PR DESCRIPTION
**Pull request by sneljeroen**
Sometimes it tries to execute commands like "Google Search" instead of "google", specifying clearly which one is the command name fixes this.

### CODE REVIEW

**Review by KendallDoesCoding — APPROVED** [review]

**Review by PhilipAD — APPROVED** [review]
lgtm

**Comment by Void-n-Null** [comment]
Thats a lot of extra tokens, but if its effective in avoiding miscommunication on command names, it might be worth it.

**Comment by fire17** [comment]
i would suggest #172 here:
https://github.com/Torantulino/Auto-GPT/pull/172/files

**Comment by mis046** [comment]
If token count is a concern, structure the data as a table might help e.g.
instead of 
```
1. Google Search; command name: "google", args: "input": "<search>"
2. Memory Add; command name: "memory_add", args: "string": "<string>"
```
might be able to use
```
command key | command name | args
Google Search | "google" | "input": "<search>"
Memory Add | "memory_add" | "string": "<string>"
```

Tried running this prompt
```
{
  "prompt": "Here is a table with | as the column delimiter and new line as row delimiter, with the first row being the header:\ncommand key|command name|args\nGoogle Search|\"google\"|\"input\": \"<search>\"\nMemory Add|\"memory_add\"|\"string\": \"<string>\", what is the value of row \"Memory Add\"'s command name field",
  ...
}
```

and this is the result
```
{
  "choices": [
    {
      "text": "?\n\n\"memory_add\"",
      "index": 0,
      "finish_reason": "stop",
      "logprobs": null
    }
  ], 
  ...
}
```

**Comment by nponeccop** [comment]
1. Make the PR title more descriptive
2. Resolve the conflicts (preferrably by rebasing on top of current master)

**Comment by k-boikov** [comment]
This PR is completely obsolete.

**Comment by BillSchumacher** [comment]
Yeah this doesn't even exist with plugins, sorry.

**Pull request closed without merging**
