### PR TITLE
Prevent docker compose to break config by creating folders

### PR DESCRIPTION
**Pull request by k-boikov**
### Background
Docker compose will create folders instead of file for volumes if they do not exist on the host. That would cause error on start:
image

### Changes
Switch the Volume type in docker-compose.yml documentation to use bind type. That would require users to have the files already created.
image
Added default values to be empty dictionary in case uses have created the files but left them empty preventing this error:
image

### Linked issues:
https://github.com/Significant-Gravitas/Auto-GPT/issues/3052

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by Wladastic** [comment]
Maybe just my 2 cents.. what if we specifically check for those files on start and tell the user specifically that those are missing?
Most users don't read the stacktrace, like ever^^

**Comment by k-boikov** [comment]
> Maybe just my 2 cents.. what if we specifically check for those files on start and tell the user specifically that those are missing? Most users don't read the stacktrace, like ever^^

The AI config is ok to be missing in the general case, it will be created. For azure - that must be there if you want to use azure. The issue is that I cannot test azure and afaik it has been broken in the last couple of releases. Feel free to make a PR if you want.

**Comment by lc0rp** [comment]
@Wladastic happy to approve and get this in v0.3.2? I'll float it by azure testers

**Comment by ntindle** [comment]
I got azure access but it costs a fortune to keep up all the time. Let me know if you need keys or me to test. Azure works fine right now as far as I can tell. The docs are just bad

**Comment by k-boikov** [comment]
> or me to test. Azure works fine right now as far as I can tell. The docs are just bad

Then I think we are good to merge. There is nothing here to test with the actual azure.

**Review by Pwuts — APPROVED** [review]
I haven't tested it but it looks good

**Pull request merged**
