### PR TITLE
Report remaining budget to user

### LINKED ISSUE #6: Make Auto-GPT aware of it's running cost
Auto-GPT is expensive to run due to GPT-4's API cost.

We could experiment with making it aware of this fact, by tracking tokens as they are used and converting to a dollar cost. 

This could also be displayed to the user to help them be more aware of exactly how much they are spending.

### PR DESCRIPTION
**Pull request by rob-luke**
### Background
Closes #6 
Following #762, this PR reports the remaining and total budget to the user.

### Changes
Reports the budget to the user if the budget is set.
The budget is report before "NEXT ACTIONS"

### Documentation
Modified `print_assistant_thoughts` to report the remaining budget and the total budget.

### Test Plan
Wrote tests. But you can also see the change in the figure below

image

### Questions to reviewers

- Is this too noisy? Would you prefer I make this only show if the user passes in a flag like `python -m autogpt --report_budget`?
- I find it useful to also include the total budget. But if this is too noisy I can remove it
- There were circular import issues. So the import is done in the function. Alternatively, I could make larger changes to the codebase, but this seemed the simplest change to make. Let me know if you want me to take another path.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by rob-luke** [comment]
FYI @Vwing

**Comment by Pwuts** [comment]
Tests fail @rob-luke

**Comment by rob-luke** [comment]
> Tests fail @rob-luke
The tests started failing when you merged main. But I have fixed the issues. So this should be good for review @Pwuts @collijk @BillSchumacher

**Comment by rob-luke** [comment]
I just fixed all the errors are #3436 was merged. Things should be good to review again @collijk

**Review by Vwing — APPROVED** [review]
I tested it out, and it looks great! Thank you for taking this on, @rob-luke.

**Review by Vwing — APPROVED** [review]
Oops, forgot to press "viewed" 😅

**Comment by rob-luke** [comment]
Thanks @Vwing and @merwanehamadi 
I’m keeping this updated with main. Is there anyone I should ping for another review/merge?

**Comment by rob-luke** [comment]
The failing test is unrelated to this change. I do not have access to restart the CI. When there is a push to main I will merge it in and that will restart the CI.

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by rob-luke** [comment]
Thanks for the info @p-i- 
I read the wiki and suggest this Pr comes under point 1 and should be merged before reintegration

**Comment by Boostrix** [comment]
>I [...] suggest this Pr comes under point 1 and should be merged before reintegration

I agree. This is a rather simple change but such a useful one. And while it's not as extensive as #3466, it solves the problem for most people for now. It may need to be revisited soonish to come up with a more generic implementation - but for now it's definitely candidate material to be considered for a review despite the ongoing re-arch effort. 

Also, it's worth keeping in mind that this change is perfectly in line with all project recommendations to monitor API usage. So, definitely do consider this for integration now:

https://github.com/Significant-Gravitas/Auto-GPT#readme
> Please note that the use of the GPT-4 language model can be expensive due to its token usage. By utilizing this project, you acknowledge that you are responsible for monitoring and managing your own token usage and the associated costs. It is highly recommended to check your OpenAI API usage regularly and set up any necessary limits or alerts to prevent unexpected charges.

**Comment by Boostrix** [comment]
it seems, there's a dedicated budget manager implementation in progress: #3919

**Comment by rob-luke** [comment]
Thanks for the info @Boostrix 
In that case I will close this PR. Thanks anyway @Vwing

**Comment by Boostrix** [comment]
Would not close it yet. Your patch looks straightforward and should work for many folks "as is" while the other stuff still is in the pipeline and might take a couple of weeks before it really arrives in the form of a functional feature

**Pull request closed without merging**
