### PR TITLE
Organize unit & integration tests

### PR DESCRIPTION
**Pull request by drikusroor**
### Background

Currently, we are having tests in the `tests` directory, the `tests/unit` directory, and the `tests/integration` directory. Aside from that, some tests are named using the `test_*.py` naming convention, while others are named using the `*_test(s).py` naming convention. The CI is set up to only execute the tests in the `tests` directory and looks for files with the `test_*.py` naming pattern by default. The inconsistency in location and naming causes the wrong tests to be executed in the CI and/or the right tests to not be executed in the CI. To address this issue, tests have been named with the `test_` prefix where needed and have relocated to the `tests/unit` or `tests/integration` folders. The CI then only executes the unit tests as they can be executed without the need of third-party services, which we currently can not run in the CI and/or for which we don't have API keys specifically meant for the CI (as far as I know).

### Changes

- Rename test files to the `test_*.py` naming pattern
- Relocate tests to either `tests/unit` or `tests/integration`
- Remove duplicate tests (`json` & `json_parse`)
- Join similar tests from different files (`browser` -> `browse_scrape_links`)

### Documentation

- README.md has been updated about test file naming convention
- README.md has been updated about difference `unit` and `integration` tests

### Test Plan

- The unit tests in the CI should succeed

### PR Quality Checklist
- [ ] My pull request is atomic and focuses on a single change. N/A
- [ ] I have thoroughly tested my changes with multiple different prompts. N/A
- [X] I have considered potential risks and mitigations for my changes.
- [X] I have documented my changes clearly and comprehensively.
- [ ] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by richbeales** [comment]
Conflicting files
tests/local_cache_test.py
tests/smoke_test.py
tests/unit/test_browse_scrape_links.py

**Review by nponeccop — APPROVED** [review]

**Comment by nponeccop** [comment]
@drikusroor There is another attempt of organize tests using pytest. Let's coordinate

**Comment by drikusroor** [comment]
@0xArty The tests are failing, supposedly because the `autogpt` module cannot be found (from `tests/unit` and `tests/integration`). On my local machine tests are succeeding and the `autogpt` module _can_ be found. Would you happen to know what's going on here and/or how to fix it?

**Comment by drikusroor** [comment]
> @0xArty The tests are failing, supposedly because the `autogpt` module cannot be found (from `tests/unit` and `tests/integration`). On my local machine tests are succeeding and the `autogpt` module _can_ be found. Would you happen to know what's going on here and/or how to fix it?

Apparently setting the Python path in `ci.yml` did the trick 🤷

**Comment by 0xArty** [comment]
> > @0xArty The tests are failing, supposedly because the `autogpt` module cannot be found (from `tests/unit` and `tests/integration`). On my local machine tests are succeeding and the `autogpt` module _can_ be found. Would you happen to know what's going on here and/or how to fix it?
> 
> Apparently setting the Python path in `ci.yml` did the trick 🤷

I just got a notification about this and was just about to say that:
`export PYTHONPATH=$PYTHONPATH:$PWD`

**Comment by Pwuts** [comment]
@drikusroor to stop the CI from failing, please add an `OPENAI_API_KEY` secret to your fork.

**Comment by Pwuts** [comment]
@drikusroor resources for mocking OpenAI API requests in CI:
* https://vcrpy.readthedocs.io/en/latest/
* https://github.com/kiwicom/pytest-recording

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Pwuts** [comment]
Many of the points from this PR have been addressed by now, and since the PR itself has deviated a lot from `master`, I think it's best to close. Thanks for submitting!

**Pull request closed without merging**
