### PR TITLE
Integrate pytest-xdist Plugin for Parallel and Concurrent Testing

### PR DESCRIPTION
**Pull request by AndresCdo**
### Background
Our current testing suite takes a significant amount of time to execute, which slows down the development process and reduces the team's productivity. To address this issue, we have decided to integrate the pytest-xdist plugin into our project. This plugin enables parallel and concurrent testing, which will help speed up our test execution and provide faster feedback to developers.

### Changes
- Added pytest-xdist to the project's requirements.txt file.
- Modified CI/CD pipeline configuration to include parallel testing options for pytest. The following files were modified in _.github_ folder:
   1. _docker-ci.yml_ 
   2. _ci.yml_

### Test Plan
GitHub CI workflow.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by AndresCdo** [comment]
#3863

**Comment by merwanehamadi** [comment]
@AndresCdo pipeline not passing

**Comment by AndresCdo** [comment]
> @AndresCdo pipeline not passing

Please review it again

**Comment by k-boikov** [comment]
LGTM

**Review by collijk — APPROVED** [review]

**Pull request merged**
