### PR TITLE
[Bug Fix] Fix size param in Dall E

### PR DESCRIPTION
**Pull request by tusharmakkar08**
### Background
Add size param in Dall E

### Changes
Add size param in Dall E

### Test Plan
Function should run properly

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by tusharmakkar08** [comment]
Issue caused by this change. https://github.com/Significant-Gravitas/Auto-GPT/commit/5576994c2c23d2c177421eb962cb6dbb61ec8da7#diff-a6c38afb44fee1a27442b5e7e1b63bb4e6b287ed90744f9481c3b85dc8dbcdd5

**Review by hdkiller — APPROVED** [review]

**Comment by tusharmakkar08** [comment]
Can we get it merged ? @hdkiller

**Comment by tusharmakkar08** [comment]
:shipit:

**Comment by tusharmakkar08** [comment]
@richbeales Can you have a look?

**Comment by k-boikov** [comment]
Fixed in another PR I can't even find...

**Pull request closed without merging**
