### PR TITLE
Update support for Azure Openai

### PR DESCRIPTION
**Pull request by Wetiqe**
### Background
MS Azure recently changed their OpenAI module to a standalone page. But they also changed the gpt-3.5-turbo, to gpt-35-turbo which is not supported.

 image

### Changes
Simply add gpt-35-turbo to the model information and update the azure api related setting.

### Documentation
Add gpt-35-turbo Cost information to autogpt/llm/modelsinfo.py, autogpt/llm/providers/openai.py, autogpt/llm/utils/token_counter.py

Pass the model parameter as well when using azure in autogpt/llm/utils/__init__.py

### Test Plan
Worked properly after change and I have made sure this is the minimal change. 
image

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes. 
- [x] I have run `black .` and `isort .` against my code to ensure it passes our linter.

### CODE REVIEW

**Comment by k-boikov** [comment]
Please run black .

**Comment by Wetiqe** [comment]
> Please run black .

Sorry, that was a mistake. I have updated the PR now.

**Comment by k-boikov** [comment]
@Wetiqe can you please switch to another branch in your fork, not master, we cannot update it with our latest master and cannot merge the PR.

**Comment by Wetiqe** [comment]
> @Wetiqe can you please switch to another branch in your fork, not master, we cannot update it with our latest master and cannot merge the PR.

I have merged the latest code and rebased my commits to one.

**Review by ntindle — APPROVED** [review]

**Comment by ntindle** [comment]
Needs updating

**Pull request closed without merging**
