### PR TITLE
Rename `evaluate_code` to `analyze_code`

### PR DESCRIPTION
**Pull request by willcallender**
### Background
As seen in #101 and #286, GPT-3.5 misinterprets "evaluate" to mean "execute" rather than "analyze". As such, I changed the name of the function to "analyze" to make the purpose of the function more clear to the AI.

### Changes
Renamed the `evaluate_code` command to `analyze_code` everywhere it appears, including the function names and the text as it's given to the AI.

### Documentation
 I tested with several simple prompts, namely hello world programs in various languages, and I haven't seen this error since making the change.

### Test Plan
I used the same basic AI personality for these tests, specifically I used Dev-GPT, an AI designed to autonomously develop, run, and test code. I gave it a single goal which was "Write and run a simple hello world program in [language]." I tested Python and Rust, it didn't always succeed but it never got confused by `evaluate_code`.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by nponeccop** [comment]
@willcallender There are conflicts now

**Review by nponeccop — DISMISSED** [review]

**Comment by willcallender** [comment]
> @willcallender There are conflicts now

Sorry, but where can I see the conflicts? Normally I'd use the resolve conflicts button but it's greyed out for me.

**Comment by willcallender** [comment]
I've tested the changes and they still work as expected.

**Review by Pwuts — DISMISSED** [review]
Looks good to me

**Review by Pwuts — APPROVED** [review]

**Pull request merged**
