### PR TITLE
Asynchronous User Interaction via Redis for AutoGPT

### PR DESCRIPTION
**Pull request by ryanpeach**
Hey everyone, I've been working on integrating Redis and a separate terminal-based CLI client with AutoGPT to enable asynchronous question-and-answer user interactions. This is just a draft PR, so any feedback or contributions are more than welcome!

This will allow the agent to ask follow up questions based on long term work done on it's goals. Checking its work against the users wishes, etc. It also allows the system to set up user notifications.

Just like a person can have an inner monologue while they talk to a person, this allows chatgpt to interact with a human without impeding its ability to live and work asynchronously, as most of the other PR's about user QA do.

### CODE REVIEW

**Comment by yousefissa** [comment]
Ooh, would love to see this across the finish-line!

**Comment by Torantulino** [comment]
@ryanpeach  This is exciting stuff! 
Really looking forward to playing with it, how close are we? 😊

**Comment by fire17** [comment]
@ryanpeach since you're on this, 
i'd like to request you make an attempt to make it generic as possible
your asynchronous workflow sounds increadible
please make it easy for me and others to add whatsapp support instead of RabbitMQ
hope that it would be easy to plug in other com libs aswell
thanks a lot!

**Comment by ryanpeach** [comment]
@fire17 So I am totally trying to make it very generic. RabbitMQ is not in competition with Whatsapp and Signal and such in this architecture, the CLI client is. Making a Whatsapp or Signal client is 100% on my roadmap.

@Torantulino I'd love to see it working by end of day but maybe unrealistic. Maybe end of week.

**Comment by ryanpeach** [comment]
So making a progress report:

The main client currently connects to the rabbitmq database but occasionally connection is being dropped. I'm having trouble to get the AI to use the commands in order for me to debug them. The qa client has been rewritten using Rich to provide a very nice UI for question answering, but I haven't tested it yet. I'm a bit bogged down at work. Still hope to work on it and be done this week, at least this weekend.

**Comment by ryanpeach** [comment]
Also, I'm starting to think redis sets and pub/sub might be better to add the questions to, because if you close the client you lose all the questions asked so far. **Upvote this post** if you'd rather see a redis, I'm sure it'd be more useful for other database related needs too.

**Comment by fire17** [comment]
@ryanpeach this might be one of the more important prs in of the more important repos 
Really hope to see this go live soon

Much love
Redis ftw!

**Comment by sberney** [comment]
I must be out of the loop, because I have no idea what RabbitMQ or QA is, and can't really tell from the code either. From what I see it looks like a cool feature, but could probably use some documentation work. Does this make it required to run RabbitMQ in order to use Auto-GPT?

**Comment by ryanpeach** [comment]
Ok so I switched to redis, it is much easier to program in.

It's now complete! See discord for some amazing examples.

@sberney QA stands for question and answer.

**Comment by ryanpeach** [comment]
Had to merge https://github.com/Torantulino/Auto-GPT/pull/142 in to make this work. We desperately need a module.

**Comment by nponeccop** [comment]
#142 is already a big change. Just extract all small changes from this and #142 and let @Torantulino merge them separately. Then rebase these ones on top. If you need help rebasing or splitting I can do, but I would like to get a confirmation from @Torantulino that my work will get reviewed and merged quickly so it won't just create more trivial PRs.

**Comment by nponeccop** [comment]
@ryanpeach Now it's out of date again (partially due to the big scope). Resolve the conflicts and rollback the unrelated changes.

**Comment by ryanpeach** [comment]
I’ll start actively maintaining it after some (any) pr making scripts a module is merged. That’s a large part of the diff, and continuing to contribute to the repo is just not worth the effort without that change.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ryanpeach** [comment]
This PR is going into draft until basic code quality is reached, and I’m contacted that it is ready to be given active attention on a day I can focus to bring it up to contribution standards. Until then, I’ll be maintaining an active fork with best practices for python development.

**Comment by merwanehamadi** [comment]
@ryanpeach I agree it would have been really nice if we had merged at least the module improvement.

**Comment by BillSchumacher** [comment]
This change looked pretty good when you were streaming the other day, I'll see if I can easily clean this up real quick.

**Comment by BillSchumacher** [comment]
This change was a bit too big, and broken for me in vscode when I tried to resolve conflicts. The functionality was great though.

**Comment by merwanehamadi** [comment]
come back @ryanpeach :) we have less conflicts now

**Comment by nponeccop** [comment]
@ryanpeach CI is red

**Comment by ryanpeach** [comment]
@merwanehamadi maybe this weekend I can work to bring this back. @nponeccop @Torantulino would this get PR attention if I fixed it?

**Comment by merwanehamadi** [comment]
Oh my god you're back @ryanpeach !!! come in discord we have to talk !

**Comment by ryanpeach** [comment]
I hear there is now a concept of core vs plugins? Please tell me exactly what you would like me to do @Torantulino and I'll have it done the weekend after.

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Boostrix** [comment]
commenting to subscribe, would also like to see this integrated

**Comment by onekum** [comment]
> commenting to subscribe, would also like to see this integrated

@Boostrix As a quick note, you can subscribe without commenting using the sidebar on the right.

**Comment by Boostrix** [comment]
yikes, thanks - my first time on this facebook for coding thingy !

**Comment by UP929312** [comment]
This would be a high upgrade, would love to see this come into fruition!

**Comment by Boostrix** [comment]
I am currently seeing a ton of redis related connection errors when using the docker image via docker-compose (from git).
Some online discussions state that it would be recommended to also set up a dedicated network bridge inside the docker-compose file so that that the redis/autogpt containers get to be on the same virtual "network"

So there's some more investigation needed at this point.

**Comment by Boostrix** [comment]
Just a heads-up: As part of the ongoing re-arch, the memory subsystem (and thus redis) got disabled, which is probably why your PR was put on the back burner. As far as I can see on Discord, some folks are currently looking into your PR. If in doubt, you may want to reach out via Discord, too.

**Comment by ryanpeach** [comment]
I'd be interested in seeing what this re-architecture is as an onlooker but I've decided not to continue on this PR. It's way too far behind by now, and I'm focused on langchain-based tooling. I also think this may have been superseded by other better-integrated chat tools and plugins like telegram clients

**Comment by Boostrix** [comment]
Thanks for getting back in touch and for clarifying.

Regarding the rearch effort, you can refer to the wiki, discord or the corresponding git branches for details

**Comment by fire17** [comment]
Hi @ryanpeach 👋 would you mind giving us an update?
Have you rebased with the new arch ?
What's your latest best version?
Have you played with Forest/Tree-of-Thought?
How about function calls ?
Are whatsapp and redis still available? 
How about generalizing and dynamic creation of commands and skills/plugins?
Atomic agents? Multi agent orchestrations?
Git integration (branch, commit, merge, etc), GitHub Issues Hook, (human guided) Self Evolving Repos ?

Hope you're still at the forefront, let me know what you think,
Take your time 😋😘
Thanks and all the best !

**Comment by Boostrix** [comment]
I believe he said on discord that he switched over to langchain, for a number of relatable reasons actually...

**Pull request closed without merging**
