### PR TITLE
(Split for PR #1805) Refactored Auth and API for future expansion. 

### PR DESCRIPTION
**Pull request by desojo**
By following these guidelines, your PRs are more likely to be merged quickly after testing, as long as they align with the project's overall direction. -->

Split 1 of 3 for PR #1805 

Background

Authorizing with the API should be outside of the post_tweet function, as to avoid code repetition with the addition of future API functions(get_replies, post_reply, twitter_search, etc.)

Changes

-Moved auth outside of the send_tweet command

Documentation

Functions are described with in-code comments

Test Plan

Ran unit tests, passed all checks. Successfully authenticated to twitter and tweeted. 

PR Quality Checklist

[ x] My pull request is atomic and focuses on a single change.
[ x] I have thoroughly tested my changes with multiple different prompts.
[ x] I have considered potential risks and mitigations for my changes.
[ x] I have documented my changes clearly and comprehensively.
[ x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by nponeccop — DISMISSED** [review]

**Comment by nponeccop** [comment]
@desojo If it's a splitting of an older PR, mention that PR number in the description

**Comment by desojo** [comment]
> @desojo If it's a splitting of an older PR, mention that PR number in the description

I edited the title and the comment, is that correct?

**Comment by nponeccop** [comment]
Yes. We only need in the description, you can keep a short title

**Comment by desojo** [comment]
By following these guidelines, your PRs are more likely to be merged quickly after testing, as long as they align with the project's overall direction. -->

Split 2 of 3 for PR #1805 

Background

Added a `reply_tweet` command, taking `tweet_text` and `tweet_id` as arguments. This commit allows 
Changes

-Added command and function call within app.py, added function reply_tweet API call within twitter.py

Documentation

Functions are described with in-code comments

Test Plan

Ran unit tests, passed all checks. Successfully authenticated to twitter and tweeted a reply. 

PR Quality Checklist

[ x] My pull request is atomic and focuses on a single change.
[ x] I have thoroughly tested my changes with multiple different prompts.
[ x] I have considered potential risks and mitigations for my changes.
[ x] I have documented my changes clearly and comprehensively.
[ x] I have not snuck in any "extra" small tweaks changes

**Comment by desojo** [comment]
By following these guidelines, your PRs are more likely to be merged quickly after testing, as long as they align with the project's overall direction. -->

Split 3 of 3 for PR https://github.com/Significant-Gravitas/Auto-GPT/pull/1805

Background

Added a get_twitter_mentions command, taking tweet_text and tweet_id as arguments. This commit allows autoGPT to get a list of mentions and interact with users on twitter 

Changes

-Added get_twitter_mentions command and function call within app.py, added function get_twitter_mentions API call within twitter.py

Documentation

Functions are described with in-code comments

Test Plan

Ran unit tests, passed all checks. Successfully authenticated to twitter and tweeted a reply to a user grabbed via mentions.

PR Quality Checklist

[ x] My pull request is atomic and focuses on a single change.
[ x] I have thoroughly tested my changes with multiple different prompts.
[ x] I have considered potential risks and mitigations for my changes.
[ x] I have documented my changes clearly and comprehensively.
[ x] I have not snuck in any "extra" small tweaks changes

**Comment by desojo** [comment]
> @desojo CI is red

Installed flake8 and made it happy on my end, should be good now

**Comment by desojo** [comment]
Not entirely sure what's going on with that CI, I haven't touched that file

**Comment by nponeccop** [comment]
> Not entirely sure what's going on with that CI, I haven't touched that file

We improved the CI strictness

**Comment by BillSchumacher** [comment]
@desojo I believe you are working on a plugin, as such I'm closing this PR. Thanks for your hard work and let me know if you get stuck on the plugin!

**Pull request closed without merging**
