### PR TITLE
Added default actions functionality

### LINKED ISSUE #236: Providing manual input in continuous mode
It would be helpful to have a feature where you can intervene and steer the continuous mode if it gets off track while watching it in action. One suggestion could be to implement a key that allows the model to finish its current task and then prompts the user for intervention to steer it back on track.

Another idea could be to add a variable that determines how many steps the model should run before pausing and asking for input. For example, the model could be set to run for 15 steps before checking in with the user to ensure it's still on the right track. This could create a more hands-off manual mode that still allows for user intervention when needed.

### PR DESCRIPTION
**Pull request by CatsMeow492**
Fixes #236
Related to #150

### Background
This pull request introduces a new functionality to the `Agent` class, allowing a default number of authorizations to be set for the `start_interaction_loop()` method. During our work, we also addressed an issue with `next_action_count`, which was being treated as a string instead of an integer, causing a `TypeError` when attempting to decrement its value.

### Changes
- Implemented a new `default_authorisation_count` parameter in the `Agent` class.
- Updated the `__init__` method of the `Agent` class to cast `next_action_count` to an integer.
- Ensured that `default_authorisation_count` is also cast to an integer when updating `next_action_count`.

### Documentation
The changes made in this pull request have been documented through in-code comments and this PR message.

### Test Plan
- Run the application with various inputs to ensure the TypeError does not occur anymore.
- Verify that `next_action_count` is correctly updated and decremented as intended during the interaction loop.
- Test the new `default_authorisation_count` functionality to ensure it works as intended.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by nponeccop** [comment]
@CatsMeow492 CI is red

**Comment by CatsMeow492** [comment]
@nponeccop CI green :)

**Comment by CatsMeow492** [comment]
༼ つ ◕_ ◕ ༽つ GIVE MERGE ༼ つ ◕_ ◕ ༽つ

**Comment by CatsMeow492** [comment]
༼ つ ◕_ ◕ ༽つ ⊂(◕_ ◕ ⊂) ⊂༼ ◕_ ◕ ༽つ WHERE MERGE?

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Pwuts** [comment]
This is an interesting but multi-faceted PR, some of which would be better as a plugin and some of which has improperly resolved conflicts such as `.env.template`. We would be happy to have your contributions, but please submit unrelated changes separately. :)

**Pull request closed without merging**
