### PR TITLE
Implement plain speech

### PR DESCRIPTION
**Pull request by dayofthedave**
### Background
The speech feature is very helpful for monitoring Auto-GPT as it chugs through multiple commands in continuous mode or when using the y -N prompt. The current language used for speaking commands is a bit clunky, however, and a more natural choice of words would be nice.

### Changes
1. Move CommandRegistry.import_commands logic out of main.py and into CommandRegistry.\_\_init__ so the registry can be accessed by both main.py and app.py
2. Add get_command_speech() function to app.py to generate wording for a command via its description in the registry, along with a few hard-coded phrases for unregistered commands
3. Call get_command_speech from agent.py instead of using default text
4. Refine some command descriptions for use in speech

### Documentation
The new get_command_speech function is easy to understand without documentation.

### Test Plan
I ran through several different scenarios with speech enabled. Note that I did not test every possible command.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by anonhostpi** [comment]
Man you are going ham on adding TTS/STT support. I saw your other pull just now - #3568

**Comment by dayofthedave** [comment]
Yeah, I use the speech feature quite a bit to monitor jobs in continuous
mode, and it helps to have multiple voices and less robotic language.

**Comment by k-boikov** [comment]
> Refine some command descriptions for use in speech

That would change the prompt, please split it to another PR since it would affect a bunch of things.

**Comment by k-boikov** [comment]
> Sure. Should I pull those changes out of this branch or just close this PR and start over?

Yes, you can just remove them an put them in a separate PR.

**Comment by Pwuts** [comment]
> Sure. Should I pull those changes out of this branch or just close this PR and start over?

Are you still planning to do this?

**Comment by dayofthedave** [comment]
Yes, probably not until next week though.

**Pull request closed without merging**
