### PR TITLE
Add more options that correspond to "y" and "n"

### PR DESCRIPTION
**Pull request by sampaiodias**
### Background

Very small change just to add more options for Y and N answers (more flexibility)

### Changes

Adds "yep" and "1" for Y, and "0" for N

### Documentation

N/A

### Test Plan

N/A

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [ ] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by edcohen08** [comment]
There's a couple similar prs for this - see #3178

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Boostrix** [comment]
> There's a couple similar prs for this - see #3178

Yes, it seems there's a bunch of similar PRs now - it would be better for people to post their draft PRs here and then team up together:
- #335
- #2252
- #3773
- #3178

**Comment by gravelBridge** [comment]
This is not necessary, y and n have no problems, nor has anyone reported or complained about only using y and n. It is also already well integrated into the system, and adding this would add unnecessary complications.

**Comment by edcohen08** [comment]
> This is not necessary, y and n have no problems, nor has anyone reported or complained about only using y and n. It is also already well integrated into the system, and adding this would add unnecessary complications. We highly appreciate your feature suggestion, and keep up the great work!

Good move on closing but just fyi this same functionality has been merged. It was an open issue for a while that users with non english keyboards were running into

**Comment by gravelBridge** [comment]
I see, thanks for letting me know.

**Pull request closed without merging**
