### PR TITLE
adding tests to the dev Dockerfile build

### PR DESCRIPTION
**Pull request by CholoTook**
### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by CholoTook** [comment]
Er... I did... a.. thing.

**Comment by collijk** [comment]
Please read the contribution guide: https://github.com/Significant-Gravitas/Auto-GPT/wiki/Contributing

We do not accept PRs without a description.

**Comment by CholoTook** [comment]
I put the tests in the dev docker build...

**Comment by ntindle** [comment]
I don't understand why you would do that. Please fill out the pr with the relevant background, as it makes the dockerfile take longer to build. What scenarios would this help with? The PR description allows all the reviewers to have an ability to review your pr.

**Comment by CholoTook** [comment]
I don't know your CI/CD platform, perhaps the tests are guaranteed to have
run before the Docker image is created?

If not, it seems essential to run the tests before packaging up the docker
file...

**Comment by k-boikov** [comment]
The Dockerfile is not the place to auto run tests.

**Comment by CholoTook** [comment]
OK, When I try to run the docker image, how do I check if the build has
passed all tests? It wasn't working out of the box for me, so knowing the
tests had been run would be useful.

**Pull request closed without merging**
