### PR TITLE
get_mentions and post_reply command,

### PR DESCRIPTION
**Pull request by desojo**
By following these guidelines, your PRs are more likely to be merged quickly after testing, as long as they align with the project's overall direction. -->

### Background
Allows AutoGPT to check for mentions and reply to said users mentions using their tweet's ID

### Changes
-Moved auth outside of the `send_tweet` command as to avoid repeating auth code in every function
-Added function `get_mentions`, which returns a list of mentions including the tweet ID, tweet text, and user handle
-Added function `post_reply`, which takes a `tweet` and `tweet_id` argument

### Documentation
Functions are described with in-code comments

### Test Plan
I created a new AutoGPT instance and interacted with it on my twitter
Name: AutoGPTweeter
Purpose: An AI designed to autonomously solve tasks for users on twitter
Goal 1: Use the get_mentions command to retrieve a list of mentions
Goal 2: Select the first task from the list of mentions
Goal 3: Complete the task
Goal 4: Use the post_reply command to respond to the original mention
Goal 5: Celebrate!

### PR Quality Checklist
- [ x] My pull request is atomic and focuses on a single change.
- [ x] I have thoroughly tested my changes with multiple different prompts.
- [ x] I have considered potential risks and mitigations for my changes.
- [ x] I have documented my changes clearly and comprehensively.
- [ x] I have not snuck in any "extra" small tweaks changes 

I do not know how to add automatic tests🥺 🥺 🥺 🥺, but I have sent tweets using this code!

### CODE REVIEW

**Comment by hdkiller** [comment]
I believe this should be re-factored to use the V2 API. This [PR](https://github.com/Significant-Gravitas/Auto-GPT/pull/1806) addresses that.

**Comment by desojo** [comment]
> I believe this should be re-factored to use the V2 API. This [PR](https://github.com/Significant-Gravitas/Auto-GPT/pull/1806) addresses that.

Noted, but the V2 API only allows free read, not free write. It was changed recently, now read is $100 a month with v2, hence the v1 calls. 

Only way I could get it working on my bot.

**Comment by sjnt1** [comment]
the send_tweet command is not working for me: Unknown command 'send_tweet'. Please refer to the 'COMMANDS' list for available commands and only respond in the specified JSON format.

tweet.py is in the commands folder , updated twitter api credentials in env and reran requirements after i downloaded the last version of AutoGPT

**Review by nponeccop — CHANGES_REQUESTED** [review]
I suggest you to split refactorings and new features into different PRs

**Comment by BillSchumacher** [comment]
I'll be helping turn this into a plugin, closing for now.

**Pull request closed without merging**
