### PR TITLE
Modified the default prompt. 

### PR DESCRIPTION
**Pull request by javableu**
The AI was trying to be the best in the world no matter what was being asked. This should fix the issue https://github.com/Significant-Gravitas/Auto-GPT/issues/4144#issue-1708101550

### PR Quality Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [ ] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [ ] I have not snuck in any "extra" small tweaks changes. 
- [ ] I have run the following commands against my code to ensure it passes our linters:
    ```shell
    black .
    isort .
    mypy
    autoflake --remove-all-unused-imports --recursive --ignore-init-module-imports --ignore-pass-after-docstring autogpt tests --in-place
    ```

### CODE REVIEW

**Comment by merwanehamadi** [comment]
@javableu we don't have a way to benchmark that, but I don't think that your improvement will make the experience worse. So thanks for this contribution.
So I am going to merge, and thanks for the challenges too
Join the R&D team so you can help us benchmark Auto-GPT. You can ping me.

**Comment by merwanehamadi** [comment]
@javableu you have a test failing

**Comment by javableu** [comment]
@merwanehamadi. Just made a commit removing two empty lines and two typos. I still have one test failing but I don't understand the test. Is this line supposed to be there?  "T&GF£OIBECC()!*",

=========================== short test summary info ============================
FAILED tests/integration/test_setup.py::test_generate_aiconfig_automatic_fallback - AssertionError: assert 'TGFCCGPT' == 'Chef-GPT'
  - Chef-GPT
  + TGFCCGPT
= 1 failed, 281 passed, 8 skipped, 12 xfailed, 29 warnings in 263.24s (0:04:23) =
Error: Process completed with exit code 1.

@pytest.mark.vcr
@requires_api_key("OPENAI_API_KEY")
def test_generate_aiconfig_automatic_fallback(patched_api_requestor):
    user_inputs = [
        "T&GF£OIBECC()!*",
        "Chef-GPT",
        "an AI designed to browse bake a cake.",
        "Purchase ingredients",
        "Bake a cake",
        "",
        "",
    ]
    with patch("autogpt.utils.session.prompt", side_effect=user_inputs):
        ai_config = prompt_user()

    assert isinstance(ai_config, AIConfig)
    assert ai_config.ai_name == "Chef-GPT"
    assert ai_config.ai_role == "an AI designed to browse bake a cake."
    assert ai_config.ai_goals == ["Purchase ingredients", "Bake a cake"]

**Review by Torantulino — COMMENTED** [review]
I am concerned that this might produce worse results, but we also aren't currently benchmarking from the early in the programs execution yet.

I agree that the existing example seems wildly overcomplicated though, but intuition on performance has lead to us taking a step backwards before.

I don't want us to be held back from potential progress however, so perhaps some manual testing is the solution here?

**Comment by javableu** [comment]
I agree, the results might be worse in some situations. It might be best to reject the commit and come up with a better solution.  Also, I just noticed that gpt4 crashes with this commit and gpt3 doesn't...

Overcomplicate the prompt and the ai won't be able to give a clear answer for simple problems like what is the answer of 2+2
Oversimplify it and the ai will try to focus on small objectives, it might achieve the goals quite fast and will then stop. The oversimplification might also be a bit frustrating for the user since the end results might just be "too simple" and not really interesting. 
I think if we come with 2-3 examples of various difficulties the ai will be able to adapt relatively well.

**Pull request closed without merging**
