### PR TITLE
Introduce the usage of langchain

### PR DESCRIPTION
**Pull request by Pireax**
### Background
While it is good to have diversity of code to be able to explore different directions, especially since all of this is so new, a lot of the basics could be done using langchain. Using this library where possible would consolidate some of the community effort. Since the development of Auto-GPT is so fast it's not feasible to move everything to langchain at once, hence this PR only introduces a minimal set of changes.

### Changes
- Replaced the openai api calls with the langchain model interfaces to call models.
- Removes the token counter implementation and tests as this is already implemented in langchain.
- Uses the structured messages found in `langchain.schema` for the model chat input.

### Documentation
No changes to the docs were necessary as this is an internal change.

### Test Plan
Ensured the tests ran and functionality was not lost by:
1. Running the system and checking it works.
2. Comparing the inputs and outputs of the system with these changes and without these changes for equality.
3. Running it without an internet connection to ensure the retry mechanism still functioned as expected.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by TheVexy** [comment]
I second this! 

Langchain can ease a lot of scaffolding building. They recently made a blog post about this type of integrations : https://blog.langchain.dev/agents-round/

**Comment by farrael004** [comment]
I personally prefer avoiding langchain whenever creating something that is not a small tech demo. It is an unnecessary abstraction layer that does something extremely simple that is better off done explicitly in code so it is clear what the intention is. Since langchain is still in constant change, adding it to this project won't make it more understandable in the future when inevitably they change their mind on how to implement things.

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Pwuts** [comment]
This pull request was far ahead of its time for us. It took us a while to decide on a strategy w.r.t. importing functionality from LangChain and similar libraries.

The concept of this PR is still relevant, but almost all of the code it touches has been rewritten or moved. I would be interested to see what functionality in Auto-GPT we could replace by LC now without a problem. My guess: most of the custom classes that have to do with making requests to OpenAI and managing the message history.

I'll close this PR as it is not mergeable and fixing it up into mergeable state is more work than making a new PR from current `master`. Please tag me if you end up doing that. :)

**Pull request closed without merging**
