### PR TITLE
Make y/n configurable

### PR DESCRIPTION
**Pull request by edcohen08**
### Background

Targets issue #753  to make auto-gpt more accessible internationally
Big shoutout to #766 i like how you code
### Changes

Allows 1/0 as alternative inputs to y/n

### Documentation

Documented in the readme

### Test Plan

I started writing a test for the interaction loop but was struggling with all of the mocking involved, tested running it and it worked fine

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by Pwuts** [comment]
1. #766 is a pull request, not an issue
2. This PR is basically a copy of #766, but without any attribution. 👎🏼

**Comment by edcohen08** [comment]
> * [Fix issue #753: Add 1/0 as an alternative to y/n for non-english users #766](https://github.com/Significant-Gravitas/Auto-GPT/pull/766) is a pull request, not an issue
> * This PR is basically a copy of that PR, but without any attribution. 👎🏼
> * Because of 2., this PR is subject to the same request for changes.

An honest mistake, I just started typing the title and clicked what came up first, I meant to link #1753 
Given 766 exists first I can close this or happy to finish it but give the right credit

**Comment by Pwuts** [comment]
```log
WARNING:  You are running on `add-1/0-as-alternative-to-y/n` branch - this is not a supported branch.
Welcome back!  Would you like me to return to being WebDevGPT?
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/autogpt/cli.py", line 90, in main
    run_auto_gpt(
  File "/app/autogpt/main.py", line 121, in run_auto_gpt
    ai_config = construct_main_ai_config()
  File "/app/autogpt/prompts/prompt.py", line 108, in construct_main_ai_config
    Continue ({config.authorise_key}/{config.exit_key}): """
AttributeError: 'AIConfig' object has no attribute 'authorise_key'
```

**Review by Pwuts — CHANGES_REQUESTED** [review]
```log
WARNING:  You are running on `add-1/0-as-alternative-to-y/n` branch - this is not a supported branch.
Welcome back!  Would you like me to return to being WebDevGPT?
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/autogpt/cli.py", line 90, in main
    run_auto_gpt(
  File "/app/autogpt/main.py", line 121, in run_auto_gpt
    ai_config = construct_main_ai_config()
  File "/app/autogpt/prompts/prompt.py", line 108, in construct_main_ai_config
    Continue ({config.authorise_key}/{config.exit_key}): """
AttributeError: 'AIConfig' object has no attribute 'authorise_key'
```

**Review by Pwuts — APPROVED** [review]
Works after fixing that error :)

**Pull request merged**
