### PR TITLE
Simple resumption of tasks on startup from long-term memory

### PR DESCRIPTION
**Pull request by jondwillis**
### Background

Every new run of auto-gpt results in an empty memory line `"This reminds you of these events from your past:\n\n\n"` In order to better resume goals based on previous long term memories, I was having to do a lot of error-prone goal-prompt engineering. This makes the agent more self-aware if it has long-term memory, but also less deterministic.

Related pull-request: https://github.com/Significant-Gravitas/Auto-GPT/pull/2530
This is an alternative approach to the above PR. If one like that or similar is merged, this can be closed.

### Changes

Agents will now have relevant memories based on their agent settings file prompt and user input on startup.

### Documentation

Inline in the code.

### Test Plan

Existing tests pass. 

### Risks

- If Auto-GPT has done something Mal-adaptive, or the ai settings files change, and incorrectly recalls memory from previous runs, it could "poison" present and future runs. It is not always easy / not all users know how to clear memory.
- This may break certain existing use-cases or change prompt output unexpectedly for existing users.

### Risk Mitigation 

- Add `--wipe-memory` and/or env var (like `WIPE_REDIS_ON_START`). Or, add something like `MEMORY_RESTART_RECALL_MODE=prompt|file_history|None` (file_history could be from this PR https://github.com/Significant-Gravitas/Auto-GPT/pull/2530)
- Add documentation about whatever path above is chosen

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by dreadful-dev** [comment]
This has logical conflicts with #2530. If that pr gets merged, the conditional used in this PR will never evaluate to `true`. Just something to keep in mind! Maybe a broader discussion is needed around agent resumption.

**Comment by ntindle** [comment]
Can you cover this with a bit of testing

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Pwuts** [comment]
Thanks for submitting! This is an interesting and seemingly useful addition. At the moment the long-term memory is not in use: it was disabled and mostly removed/reworked (#4208) for lack of performance. I have labeled this with `fridge` so we can find it back and process it when the dust settles.

**Pull request closed without merging**
