### PR TITLE
Support proxy env variable

### PR DESCRIPTION
**Pull request by RadixIsatidis**
### Background
Running behind a socks5 proxy.

### Changes
1. Add proxy settings when openai config init.
2. Using a custom http client witch has a correct socks5 proxy setting in google cloud api.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by youkaichao** [comment]
I think just setting `https_proxy` environment as https://github.com/Significant-Gravitas/Auto-GPT/pull/1541 this pr should work? I have tested it and it works.

**Comment by nponeccop** [comment]
@RadixIsatidis There are conflicts now

**Review by nponeccop — APPROVED** [review]

**Review by nponeccop — DISMISSED** [review]

**Comment by z-x-x136** [comment]
> > @RadixIsatidis现在有冲突
> 
> 我已经解决了。

How did you solve the problem?

**Comment by z-x-x136** [comment]
> > > @RadixIsatidis现在有冲突
> > 
> > 
> > 我已经解决了。
> 
> 你是如何解决这个问题的？

win10 cmd:set http_proxy=http://127.0.0.1:33210 & set https_proxy=http://127.0.0.1:33210

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Pull request closed without merging**
