### PR TITLE
Fix list files function to accept more arguments

### PR DESCRIPTION
**Pull request by bassie661**
### Background
A lot of times agents come up with arguments against the list_files() function (former search_files) which are not accepted, this makes the agent end up in a loop, not finding anything but an error.

### Changes
While a lot of times the args are just a replacement of the original "filename" argument i've also seen extension as an argument, with literally an ".ext" as search query.

I changed the function to accept all, although it might be better to take care of this on the agent side which makes up all the arguments, but in the meantime I couldn't take it anymore :)

### Documentation
Mainly in-code comments:

directory (str): The directory to search in
extension (str, optional): The file extension to filter by. If provided, all other arguments except 'directory' and 'keywords' will be ignored. Defaults to None.
filename (str, optional): A partial file name to filter by. If provided and 'extension' is not, all other arguments except 'directory' will be ignored. Defaults to None.
query (str, optional): A query to filter by. If provided and 'extension' and 'filename' are not, all other arguments except 'directory' will be ignored. Defaults to None.
filename_query (str, optional): A query to filter file names by. If provided and 'extension', 'filename', and 'query' are not, all other arguments except 'directory' will be ignored. Defaults to None.
filename_substring (str, optional): A substring to filter file names by. If provided and 'extension', 'filename', 'query', and 'filename_query' are not, all other arguments except 'directory' will be ignored. Defaults to None.
keywords (list[str], optional): A list of keywords to filter by. If provided and 'extension', 'filename', 'query', 'filename_query', and 'filename_substring' are not, 'extension' will be appended to each keyword before filtering. Defaults to None.

### Test Plan
Tested for a week with continuously changing file and creating file goals and I haven't seen an error or stall since.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Boostrix** [comment]
indeed, that looks like an excellent little addition that is very useful (keep seeing the exact behavior you described) - I'd suggest to consider this PR as a candidate for being reviewed/integrated regardless of the ongoing re-arch effort

**Comment by Boostrix** [comment]
indeed, that looks like an excellent little addition that is very useful (keep seeing the exact behavior you described) - I'd suggest to consider this PR as a candidate for being reviewed/integrated regardless of the ongoing re-arch effort

**Comment by bassie661** [comment]
Is anything needed for this or has it been solved already from another angle ?

I have been using this function for over 2 weeks now and hadn't had any search query errors since.

**Comment by Boostrix** [comment]
would also like to see this reviewed and integrated - if you haven't done so already, you should consider adding the corresponding pytest files to test all aspects of your changes. You can usually use autogpt/gpt itself to come up with the corresponding stubs, so should not take you very long.
If in doubt, you can copy/paste relevant unit tests into GPT and adapt them based on your changes.

**Pull request closed without merging**
