### PR TITLE
Automated self feedback

### PR DESCRIPTION
**Pull request by konraddroeske**
Draft to resolve: https://github.com/Significant-Gravitas/Auto-GPT/issues/4220

### Background
In continuous mode, we should provide an option to trigger automated self-feedback based on some configurable threshold, such as number of errors/warnings the system is seeing (for instance when executing commands that don't exist), to "self-correct". Self-correction should include a list of valid commands/parameters.

Updates (to-do):
- Initial heuristics would include: does the command exist? Is the argument supported? Is the argument provided in the proper form?
- Being able to optionally change the temperature in cases where the LLM is obviously hallucinating command/parameter combinations, might actually come in handy. That also applies to being able to use the smart_llm_model if available.
- In theory, the LLM trying to execute an invalid action (defined by the command/parameter combination not being supported), we could optionally refuse to run the command (without even having to execute it) and tell the LLM that its command is invalid/unsupported, which should save us steps/API tokens. In other words, the agent would receive/identify such a command and directly refuse it with an error, so that the LLM gets to try again.
we need to keep the interactive use-case in mind, as well as the one where this is triggered by sub-agents.
- For testing purposes, we could use a new custom command with an incorrect description string, so that its name/arguments are incorrect. Alternatively, we could modify any of the standard commands at runtime by using a timer and changing the name/arguments or description string, so that the LLM would inevitably have to make an error and adapt to the situation.

### Changes
- Added an error_threshold flag, to be used in combination with continuous mode. 
- Added error_counter to config based on error_threshold value, which triggers get_self_feedback() when threshold has been met, then resets the counter.
- Added _handle_self_feedback(), which is called when a user presses 's' or when error threshold is met in continuous mode.
- Updated message to sent to LLM from get_self_feeback() to include commands and valid arguments.
- Fixed conversion of feedback message in get_self_feedback()
- If command_result is a failure or not found, saved to result as a failure and included text to avoid using command with same arguments (similar to when output is too large).
- Set model default to "gpt-3.5-turbo" in call_ai_function() to prevent errors.
- Refactored agent class to make it more readable
- Added CommandMessage dataclass comprised of name, args, and user_input
- Added CommandError dataclass comprised of name, args, and error_message
- Added errors dict where key is command and value is a list of CommandErrors
- Updated feedback prompt to include goals, constaints, commands, and a list of previous errors to avoid

### Documentation
- TBD

### Test Plan
- TBD

### PR Quality Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [ ] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [ ] I have not snuck in any "extra" small tweaks changes. 
- [ ] I have run `black .` and `isort .` against my code to ensure it passes our linter.

### CODE REVIEW

**Comment by Boostrix** [comment]
Some random observations/considerations:

- there's ongoing work to generalize support for multiple prompts as part of #3937 - therefore, it would make sense to encapsulate anything related to prompting, so that this work can be updated/integrated once it's ready.
- being able to optionally change the temperature in cases where the LLM is obviously hallucinating command/parameter combinations, might actually come in handy.
- we might be generally interested in having/providing a way to gather warnings/errors and evaluate those via self-feedback - for instance, referring to errors related to malformed json or exceeded token limits.
- likewise, if we were to maintain an error log specific to command/parameter combinations, the LLM could use this log (its errors) to adapt itself, even in cases where a command stops working, and where an alternative might be needed.
- in theory, the LLM trying to execute an invalid action (defined by the command/parameter combination not being supported), we could optionally refuse to run the command and tell the LLM that its command is invalid/unsupported, which should save us steps/API tokens. In other words, the agent would receive/identify such a command and directly refuse it with an error, so that the LLM gets to try again.

**Comment by merwanehamadi** [comment]
@konraddroeske great stuff, you're improving the current self feedback, because it's currently broken

**Comment by merwanehamadi** [comment]
@konraddroeske let me just check if you provide an argument for people to choose what they want, this is also safer for us, to first make it optional

**Comment by AbTrax** [comment]
@Boostrix  Sorry, I should have responded as soon as I saw this a week ago, this looks quite promising I was doing Toran's implementation but memory issues arose. And will continue to keep a close eye on this one.

**Comment by Boostrix** [comment]
If you're seeing any problems or have suggestions what to keep in mind, please do leave corresponding feedback

**Comment by konraddroeske** [comment]
@Boostrix @AbTrax  Apologies for the delay, got tied up this week. All this feedback is great, but this is starting to become a pretty large update.

- Validating and Rejecting Commands + Arguments prior to self-feedback
- Error Management (categorizing and using for self-feedback)
- Updating temperature (after repeated failures?)
- Encapsulating the feedback prompt w/ an adaptor class

I feel like we should turn these into additional issues, and in the meantime I should just get an non-broken, somewhat naive version going.

I'm open to making these additional changes, but let me know what you think I should prioritize.

**Comment by merwanehamadi** [comment]
@konraddroeske I really like this work, can you jump on a voice with me on discord: https://discord.gg/autogpt (same username)
I have questions about the PR.

**Comment by Boostrix** [comment]
If you're seeing any problems or have suggestions what to keep in mind, please do leave corresponding feedback

See the following related links:

https://discord.com/channels/1092243196446249134/1103756242943492148/1113621858105970698

https://arxiv.org/pdf/2305.16291.pdf

**Comment by konraddroeske** [comment]
After reviewing the feedback - both in this thread and privately with reviewers - I believe this solution might exceed the intended scope. I'll be closing this branch for now, in case are others with alternative approaches.

**Pull request closed without merging**
