### PR TITLE
Cleaned up the memory functionality

### PR DESCRIPTION
**Pull request by Riddle1001**
I moved the memory functionality into it's own file, and made it a singleton. Works as expected.

### CODE REVIEW

**Comment by jfhutchi** [comment]
Why did you remove .env.template?

**Comment by sberney** [comment]
Why did you make it into a class if it's also a singleton? What new functionality or capability does this add?

**Comment by bnuttall** [comment]
I think this commit is now overtaken by events, as Pinecone seems to have been merged into the master branch

**Comment by Riddle1001** [comment]
> Why did you remove .env.template?

I will fix this, didnt notice thanks,

> Why did you make it into a class if it's also a singleton? What new functionality or capability does this add?

In python, you cannot make a singleton without it being a class, and vice versa. Singleton is a design pattern and wouldn't add any functionality.

**Comment by nponeccop** [comment]
@Riddle1001 Fix the .env issue and resolve the conflicts

**Comment by k-boikov** [comment]
This PR is completely obsolete, memory module has been rewritten.

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Pwuts** [comment]
As @k-boikov mentioned, the memory module has been rewritten completely (#4208), so this PR is obsolete. Thanks for submitting though!

**Pull request closed without merging**
