### PR TITLE
Added Send Telegram Message Functionality

### PR DESCRIPTION
**Pull request by Reno-Codes**
### Background

While waiting for AutoGPT to do tasks, It's useful to receive a notification message on Telegram when some task is done.
I know it's a potential plugin, but many people will find it essential to receive notifications on Telegram about their AutoGPT status.

### Changes

Added telegram.py in the commands folder.
Added entries for it in app.py and prompt.py.

### Documentation

Create a bot on telegram by contacting @BotFather.
Give your Telegram bot a name, like "AutoGPT Notifier" or whatever.
Copy bot token from telegram and paste it into TELEGRAM_BOT_TOKEN in your .env file. 

While setting up a GOAL for AutoGPT, just write something like "Send telegram message when done with previous tasks." or whatever you'd like to receive as a notification from your AI.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by k-boikov** [comment]
I very well see that PR transforming into a Plugin, since we are getting a bunch of them, please check on https://github.com/Significant-Gravitas/Auto-GPT/pull/757 it is expected to be 
 ready for the end of the week

**Comment by Reno-Codes** [comment]
> I very well see that PR transforming into a Plugin, since we are getting a bunch of them, please check on #757 it is expected to be ready for the end of the week

Yeah, it's more suitable as a plugin. I'll convert it when plugin.py is released :)

**Comment by Pwuts** [comment]
@Reno-Codes plugin support will ship very soon, it was just merged to `master`. I'm closing this PR and hoping to see it return as a plugin :)

**Comment by Wladastic** [comment]
please check this PR first:
https://github.com/Significant-Gravitas/Auto-GPT/pull/1135

**Comment by Reno-Codes** [comment]
> please check this PR first: #1135

@Wladastic Your Telegram bot requires too much effort for an average user. The average user wouldn't be able to `curl https://api.telegram.org/bot<your-telegram-bot-token>/getUpdates` and from JSON response find their chatID.

Why not just paste the bot token and AutoGPT should handle getting chatID automatically.

**Comment by Wladastic** [comment]
the average user just has to visit https://api.telegram.org/bot<your-telegram-bot-token>/getUpdates with their browser.
But i am already planning a setup script for that

**Comment by Wladastic** [comment]
Also the gathering method is very insecure, please also keep in mind that your bot receives messages by everyone.

**Comment by Reno-Codes** [comment]
> the average user just has to visit https://api.telegram.org/bot/getUpdates with their browser. But i am already planning a setup script for that

Yeah, that would work, AutoGPT handling this by itself...

I know the gathering method is insecure, I made it that way for bots that are only made for purpose of notifying users who made that bot specifically for this purpose, and not for bots that receive messages from other users too.

Your approach seems pretty solid, looking forward to seeing it as a plugin since I'm using it in pretty much every AutoGPT goal.

**Comment by Wladastic** [comment]
As a headsup, this will work soon as a plugin.
One PR merged soon and we have to wait a few hours for the owner to update the python dependency of the plugin template :)

Context: otherwise there are a few methods missing on the class the object of the plugin is casted to.

**Pull request closed without merging**
