### PR TITLE
Used a regex expression for simple URL validation and added tests

### PR DESCRIPTION
**Pull request by OmriGM**
### Background

- Used a regex expression for simple URL validation
- Added additional tests to url validators
### Changes

The expression before:
```python
url.startswith("http://") and not url.startswith("https://"):
```
The expression after: 
```py
re.match(r"^https?://", url):
```
Also, added unit test to `tests/unit/test_url_validation.py` module, specifically to `validate_url()` which is the main function in the module 
### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by Boostrix** [comment]
this sort of regex-based validation routine would also be useful in other places, like file name/path validation (for shell command execution)
A number of folks keep reporting that Auto-GPT is trying use absolute paths and even the ~ (home dir) inside the workspace.

**Comment by OmriGM** [comment]
@ntindle BTW, there is a failing test (`tests/integration/test_execute_code.py: test_execute_python_file()`) that is dependent on the docker daemon running on the local machine, was that on purpose?
Here is the error message of the failing test (before I started the docker daemon on my local computer)
```bash
./tests/integration/test_execute_code.py::test_execute_python_file Failed: [undefined]assert 'Error: Error...directory\'")' == 'Hello udaxihhexd!\n'
  - Hello udaxihhexd!
  + Error: Error while fetching server API version: 500 Server Error for http+docker://localhost/version: Internal Server Error ("b'dial unix docker.raw.sock: connect: no such file or directory'")
python_test_file = '/private/var/folders/58/jb5nf1y51b1btsjnnsn9jsdc0000gn/T/pytest-of-omrigrossman/pytest-13/test_execute_python_file0/home/users/monty/auto_gpt_workspace/tmph3oy_5_j.py'
random_string = 'udaxihhexd'

    def test_execute_python_file(python_test_file: str, random_string: str):
        result = sut.execute_python_file(python_test_file)
>       assert result == f"Hello {random_string}!\n"
E       assert 'Error: Error...directory\'")' == 'Hello udaxihhexd!\n'
E         - Hello udaxihhexd!
E         + Error: Error while fetching server API version: 500 Server Error for http+docker://localhost/version: Internal Server Error ("b'dial unix docker.raw.sock: connect: no such file or directory'")
```

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by anonhostpi** [comment]
I think it maybe smarter to use a library for validation. The repository may find URL/URI/Path validation useful in other areas.

**Comment by ntindle** [comment]
Are we sure Regex is the way to go here? Aren’t there entire libraries for validation?

**Comment by Boostrix** [comment]
This would at least seem like a start, maybe the OP would like to adopt the feature and extend it over time?

**Review by richbeales — APPROVED** [review]

**Pull request merged**
