### PR TITLE
Finished Twitter.py 

### PR DESCRIPTION
**Pull request by WellnessSupplyCo**
This commit adds various utility functions for interacting with the Twitter API using Tweepy library. The functions include sending tweets, getting user tweets, searching for tweets, getting trending topics, following and unfollowing users, sending direct messages, liking and unliking tweets, retweeting and unretweeting tweets, getting user profile information, getting user followers and friends, getting tweets by ID, getting tweet replies, getting user timeline, getting trending topics by location, getting user mentions, getting user's liked tweets and retweets, getting tweet retweeters, searching for users, getting user follow counts, and getting blocked users. Each function has been documented with a brief description of its purpose and usage.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [ ] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by WellnessSupplyCo** [comment]
Twitter functions updated

**Comment by k-boikov** [comment]
The two files you are trying to update are in another folder, please rebase.

**Comment by hdkiller** [comment]
This will not get merged unfortunately, I suggest you convert it into a plugin, since your implementation seems complete.

**Comment by hdkiller** [comment]
@BillSchumacher I think this PR should be closed.

**Comment by hdkiller** [comment]
There is another one which already implemented as a plugin: https://github.com/desojo/autogpt-twitter 

Maybe you should push a PR there?

**Comment by frissle** [comment]
Just tested. Seems to be working as expected.

**Comment by WellnessSupplyCo** [comment]
> The two files you are trying to update are in another folder, please rebase.

https://github.com/WellnessSupplyCo/autogpt-twitter

**Comment by Pwuts** [comment]
This PR is broken (`./app.py` has been moved and this PR tries to recreate it) and, as of #757, outside the scope of this core project. As mentioned in the comments above, there are plugins available for this functionality, and that is also the preferred way to add non-essential features. :)

**Comment by WellnessSupplyCo** [comment]
> This PR is broken (`./app.py` has been moved and this PR tries to recreate it) and, as of #757, outside the scope of this core project. As mentioned in the comments above, there are plugins available for this functionality, and that is also the preferred way to add non-essential features. :)

Old codebase; has been updated to work via plugin and merged with an existing twitter plugin to complete it.

**Comment by sjnt1** [comment]
> > This PR is broken (`./app.py` has been moved and this PR tries to recreate it) and, as of #757, outside the scope of this core project. As mentioned in the comments above, there are plugins available for this functionality, and that is also the preferred way to add non-essential features. :)
> 
> Old codebase; has been updated to work via plugin and merged with an existing twitter plugin to complete it.

Is it necessary to be on master for your plugin to work?

**Pull request closed without merging**
