### PR TITLE
Draft: feat: allow running multiple commands at once

### PR DESCRIPTION
**Pull request by yangkyeongmo**
### Background

https://github.com/Significant-Gravitas/Auto-GPT/issues/3945

### PR Quality Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [ ] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [ ] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by Boostrix** [comment]
This could be really useful and as long as this is not supported we need to prime the llm to tell it that it can by default only execute a single action/command and needs to await a response before being able to execute a new action. Actions and commands also cannot be conditional directly. 

That it is running in a REPL and that it would need to use shell commands or python scripts to get around this limitation.

**Comment by Boostrix** [comment]
This looks interesting and just so that you know: I kinda implemented a similar scheme to run multiple commands at once with less code by allowing pre/post execution hooks to be registered at the Command manager layer - and then added a new command to allow a chain of commands to be registered as "one" command.

Unlike you, I didn't bother with  handling async stuff - I just wanted "shell-like" behavior:
- be able to do the equivalent of command1 && command2
- ideally with the option to return not just the output, but also an error code 
- currently looking at supporting the equivalent of pipes: command1 | command2

Like you, my motiviation is to set up/prepare commands locally at the agent side via the LLM, which are then implicitly executed that way.

Overall, this might be something that should better be reviewed/discussed by the folks reworking the command system currently, see @DarylRodrigo :

- #3824

**Comment by yangkyeongmo** [comment]
@Boostrix Cool. Would be helpful if you share your result!

**Comment by Boostrix** [comment]
> @Boostrix Cool. Would be helpful if you share your result!

you can look at the diff here: #4063 
This is based on the old/original plugin interface where you could register pre/post execution callbacks.

That way, we can implement all sorts of fancy stuff with very little code - including new commands that are simply lists of other commands

**Comment by yangkyeongmo** [comment]
@Swiftyos I see, thanks for your confirmation!

I was wondering if I should close this PR after peeking the re-arch figma. I'm really looking forward to result of re-arch :smile:

**Pull request closed without merging**
