### PR TITLE
Updated git clone in README to pull from stable branch

### PR DESCRIPTION
**Pull request by Josh-XT**
### Background
With changes to master branch, changing git clone to stable branch in the README seems ideal.

### Changes
Added `-b stable` to the git clone in README.

### Documentation
Updating it with this PR.

### Test Plan
Works on my machine TM.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by nponeccop — APPROVED** [review]

**Review by nponeccop — COMMENTED** [review]
This isn't necessarily good.

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by anonhostpi** [comment]
@nponeccop what's wrong with specifying the cloned branch?

**Comment by Pwuts** [comment]
These instructions are no longer in the README, and have been fixed in the docs. Thanks for the submission!

**Pull request closed without merging**
