### PR TITLE
Add launcher for Auto-GPT with language selection feature

### PR DESCRIPTION
**Pull request by Laodeus**
### Description

This pull request adds the launcher.py script for launching Auto-GPT. The script provides an interactive command-line interface for selecting Auto-GPT options and generating the appropriate command line whit multi-language support.

### Changes Made

The launcher.py script has been added to the repository. It contains the functions for launching Auto-GPT with user-specified options. The script uses the curses library to provide an interactive command-line interface for selecting options and building the command line.

### Testing

The script has been tested on Linux using Python 3.8 and 3.9. The script has been manually tested by selecting various Auto-GPT options and verifying that the generated command line is correct.

### Documentation

The docs/launcher.md file has been created and include instructions for using the launcher.py script. The file includes a brief overview of the script and instructions for running the script.

### PR Checklist

Please check off the following items to ensure that your pull request meets the necessary criteria:

- [x] The pull request focuses on a single, specific change.
- [x] The changes made are well-documented and explained clearly.
- [x] The code has been tested thoroughly and meets the expected requirements.
- [x] The `README.md` file has been updated to reflect the changes made.
- [x] The pull request does not include any unrelated or "extra" modifications.

### CODE REVIEW

**Review by z-x-x136 — COMMENTED** [review]
I used the code from launche.py, and in cmd I just executed python E:\chatGPT\AutoGPT\Auto-GPT\autogpt\launcher.py, how to use with autoGPT

**Comment by Laodeus** [comment]
documentation available in docs/ folder

**Review by z-x-x136 — COMMENTED** [review]
E:\chatGPT\AutoGPT\Auto-GPT>python E:\chatGPT\AutoGPT\Auto-GPT\autogpt\launcher.py      
Traceback (most recent call last):
  File "E:\chatGPT\AutoGPT\Auto-GPT\autogpt\launcher.py", line 206, in <module>
    cmdline = curses.wrapper(main)
  File "D:\anaconda\Anaconda\lib\curses\__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "E:\chatGPT\AutoGPT\Auto-GPT\autogpt\launcher.py", line 178, in main
    stdscr.addstr(i +6, len(argument) + 2, descriptions[language][i])

_curses.error: addwstr() returned ERR

An error has occurred.

**Comment by Laodeus** [comment]
Could you please provide more information about your system environment? Specifically, what version of Python are you using and what operating system are you running? This information will help me better understand the context of the issue you're experiencing. Thank you!

**Comment by z-x-x136** [comment]
> 您能否提供有关您的系统环境的更多信息？具体来说，您使用的是什么版本的 Python，运行的是什么操作系统？这些信息将帮助我更好地了解您遇到的问题的背景。谢谢你！

python3.9 win10

I just ran python E:\chatGPT\AutoGPT\Auto-GPT\autogpt\ launche.py from the command line

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Pwuts** [comment]
Look @ntindle, a TUI!

**Comment by Pwuts** [comment]
We're currently not looking to implement i18n, but will do so in the future.

**Pull request closed without merging**
