### PR TITLE
Feat  set token limits based on model

### PR DESCRIPTION
**Pull request by BaseInfinity**
### Background
Every day we see people come into the discord explaining how they ran into a token limit because most people are still on a 3.0/3.5 key. The maintainer's built the app to assume 8000 token limit due to gpt4 key and atm this just causes friction because in reality, most people do not have a 4.0 key

To meet in the middle we will respect the user's token limit but compare it to the max token limit based off the smart/fast llvm model and set a limit 15% less to ensure we take into account the prompt and package

### Changes
Use the model's max_token_limits for both fast/smart llvm

### Test Plan
i updated failing tests

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by BaseInfinity** [comment]
Not sure what to do with this pull request, essentially waiting to see if we should allow users to set the token limits still or always infer them by model

@Pwuts / @Boostrix / @ntindle / @k-boikov 

I also understand this is probably low priority but figured I'd keep the conversation going =)

**Comment by Boostrix** [comment]
Low priority is relative, it's one of the more frequent issues on discord and github

https://discord.com/channels/1092243196446249134/1092243196798582930/1115737448580907180

**Review by Pwuts — DISMISSED** [review]
Looks good to me :)

**Comment by Pwuts** [comment]
Conflict is because `test_config.py` has been moved in `master`

**Comment by erik-megarad** [comment]
Hell yeah, nice one

**Review by Pwuts — APPROVED** [review]

**Comment by Boostrix** [comment]
We may still want to support changing this at runtime so that the agent can exit gracefully using a corresponding error message, in order for the LLM to change some variables at runtime: https://discord.com/channels/1092243196446249134/1092423060923101304/1115963736642035732

**Comment by BaseInfinity** [comment]
Thanks @Pwuts for getting this merged! I went away for a couple days and was pleasantly surprised to see this merged lol

**Pull request merged**
