### PR TITLE
Create install.bat

### PR DESCRIPTION
**Pull request by nekohacker591**
### Change Safety

- [x ] I have added tests to cover my changes 
- [ x] I have considered potential risks and mitigations for my changes

becuase this does not modify the functionality of the project

### CODE REVIEW

**Comment by nponeccop** [comment]
Should it be `install.cmd`? `.cmd` has an extended language, so `.bat` is legacy at this point and as such it should never be used. (Well, cmd is still legacy, but people persist).

Also, the script is literally 1 line of `pip install -r install.txt` with extra checks. If you want to package Auto-GPT for users incompetent enough to failing to run pip, there are better packaging methods, and/or the instruction on how to install Python might be helpful (through the store?)

**Comment by richbeales** [comment]
Agreed this script doesn't seem to add much value.

**Comment by nekohacker591** [comment]
> Agreed this script doesn't seem to add much value.

i just want to make it more accesable to people who are less tech savy

**Comment by richbeales** [comment]
closing as we now have batch/scripts to run Auto-GPT

**Pull request closed without merging**
