### PR TITLE
update type annotation

### PR DESCRIPTION
**Pull request by youkaichao**
### Background
Fix wrong type annotations:
Use Tuple instead of tuple;
Use List instead of List;

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by youkaichao** [comment]
@nponeccop Please check the PR for correcting some type annotations.

**Review by nponeccop — APPROVED** [review]

**Review by richbeales — APPROVED** [review]

**Comment by AndroidDev77** [comment]
Can we slipstream this commit to stable?

**Comment by SecretSanta007** [comment]
still same error

**Comment by ronbiggs** [comment]
still same error for me too

**Comment by mc856** [comment]
This error is raised in the stable 0.3.0 version

(venv) (base) junliu@JundeMBP Auto-GPT-0.3.0 % ./run.sh
All packages are installed.
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/junliu/Documents/code/Auto-GPT-0.3.0/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/Users/junliu/Documents/code/Auto-GPT-0.3.0/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/junliu/Documents/code/Auto-GPT-0.3.0/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/junliu/Documents/code/Auto-GPT-0.3.0/venv/lib/python3.8/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/Users/junliu/Documents/code/Auto-GPT-0.3.0/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/junliu/Documents/code/Auto-GPT-0.3.0/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/junliu/Documents/code/Auto-GPT-0.3.0/venv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/junliu/Documents/code/Auto-GPT-0.3.0/autogpt/cli.py", line 87, in main
    from autogpt.main import run_auto_gpt
  File "/Users/junliu/Documents/code/Auto-GPT-0.3.0/autogpt/main.py", line 8, in <module>
    from autogpt.agent.agent import Agent
  File "/Users/junliu/Documents/code/Auto-GPT-0.3.0/autogpt/agent/__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "/Users/junliu/Documents/code/Auto-GPT-0.3.0/autogpt/agent/agent.py", line 3, in <module>
    from autogpt.app import execute_command, get_command
  File "/Users/junliu/Documents/code/Auto-GPT-0.3.0/autogpt/app.py", line 5, in <module>
    from autogpt.agent.agent_manager import AgentManager
  File "/Users/junliu/Documents/code/Auto-GPT-0.3.0/autogpt/agent/agent_manager.py", line 7, in <module>
    from autogpt.llm import Message, create_chat_completion
  File "/Users/junliu/Documents/code/Auto-GPT-0.3.0/autogpt/llm/__init__.py", line 1, in <module>
    from autogpt.llm.api_manager import ApiManager
  File "/Users/junliu/Documents/code/Auto-GPT-0.3.0/autogpt/llm/api_manager.py", line 7, in <module>
    from autogpt.logs import logger
  File "/Users/junliu/Documents/code/Auto-GPT-0.3.0/autogpt/logs.py", line 12, in <module>
    from autogpt.speech import say_text
  File "/Users/junliu/Documents/code/Auto-GPT-0.3.0/autogpt/speech/__init__.py", line 2, in <module>
    from autogpt.speech.say import say_text
  File "/Users/junliu/Documents/code/Auto-GPT-0.3.0/autogpt/speech/say.py", line 34, in <module>
    def _get_voice_engine(config: Config) -> tuple[VoiceBase, VoiceBase]:
TypeError: 'type' object is not subscriptable

**Comment by SecretSanta007** [comment]
I finally figured out the solution to my problem after spending three hours trying to fix it, and it turns out that using **Docker** was the way to go. It was a bit frustrating at first, but I'm glad I was able to find a solution in the end.

**Comment by rousseau-funble** [comment]
still same error for me too

**Comment by sdimantsd** [comment]
@rousseau-funble 
How do you manage to run it with python3.10?
When I try to install the requirements it's say:
AttributeError: module 'collections' has no attribute 'MutableMapping'

**Comment by rousseau-funble** [comment]
> @rousseau-funble How do you manage to run it with python3.10? When I try to install the requirements it's say: AttributeError: module 'collections' has no attribute 'MutableMapping'

@sdimantsd 
in my case, such an issue did not occur. 
in my wsl ubuntu, python 3.8, 3.11 had been installed.
i was just noticed autogpt requires 3.10 or higher 
and i changed default python 3.8 to 3.11.

there were some other problems for the version confusion. (pip did not work properly)
i asked to chatgpt, and it provided scripts like this:
```
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.11 1
wget https://bootstrap.pypa.io/get-pip.py
sudo python3.11 get-pip.py
```
after running the commands, all was well.

in your case, i think this thread will be an help:
https://stackoverflow.com/questions/70943244/attributeerror-module-collections-has-no-attribute-mutablemapping

**Comment by sdimantsd** [comment]
@rousseau-funble  Thanks

**Pull request merged**
