### PR TITLE
Add SEARCH_LANGUAGE_CODE env configuration and support search google with google translation.

### PR DESCRIPTION
**Pull request by Jun10ng**
https://github.com/Significant-Gravitas/Auto-GPT/issues/1629

### CODE REVIEW

**Review by azure1016 — DISMISSED** [review]

**Comment by richbeales** [comment]
requirements.txt conflicts.

**Comment by Jun10ng** [comment]
> requirements.txt conflicts.

@azure1016 @richbeales  Resolved conflicts

**Comment by Jun10ng** [comment]
googletrans lib has an issue which across many version(I encounter it from 3.0 -> 4.0) https://github.com/ssut/py-googletrans/issues/234
so I decided to change my implementation to a simple way

**Review by nponeccop — CHANGES_REQUESTED** [review]
I suggest splitting the google translate replacement and env configuration into separate PRs. Or at least renaming the PR to reflect its scope.

**Comment by nponeccop** [comment]
@Jun10ng There are more linter errors

**Review by Jun10ng — COMMENTED** [review]
fixed

**Comment by sakurafly123** [comment]
> what's the chinese SEARCH_LANGUAGE_CODE?zh_CN,is it correct?

简体中文 zh-CN,繁体zh-TW

**Comment by Jun10ng** [comment]
> sakurafly123

zh-CN

**Comment by sakurafly123** [comment]
> > sakurafly123
> 
> zh-CN

老哥你只是搜索的时候准备把母语翻译成英语搜索，你会把结果再翻译回母语吗

**Comment by Jun10ng** [comment]
> 
This PR only supports translating `google search input text`.
And this PR  https://github.com/Significant-Gravitas/Auto-GPT/pull/1880 support outputs(Think, Action and so on)  in multi-language.

**Comment by Jun10ng** [comment]
Hi @nponeccop, could add this PR into PR7? I think this feature would have a better effect with another feature [ai_output_language_code](https://github.com/Significant-Gravitas/Auto-GPT/pull/1880), user can input and output in their native language.

**Review by nponeccop — APPROVED** [review]

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by anonhostpi** [comment]
I'd also like to add that I don't believe the repository is looking to add localization quite yet, at least not until the end of the re-arch.

**Comment by kinance** [comment]
Relates to #1563

**Comment by Pwuts** [comment]
Closing this together with #1880, for the same reason:

> see https://github.com/Significant-Gravitas/Auto-GPT/pull/1880#issuecomment-1711601610

**Pull request closed without merging**
