### PR TITLE
Caching!

### PR DESCRIPTION
**Pull request by thepok**
This adds a new start option --caching
all the requests to OpenAI are cached if this option is used, and if the same request is made again (because you restarted AutoGTP with the same start config) its reuseing the old results.

New starts are verry fast this way, and enable it to interupt the agent

### CODE REVIEW

**Comment by thepok** [comment]
what needs to be done to make it mergable?

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by anonhostpi** [comment]
@thepok don't get too discouraged. The re-arch is currently very hot on the repo right now. There has already been significant progress this morning and yesterday on the re-arch. The workspace, agent, plugin, and command structures in the repo have already been reworked, and it hasn't been a full 24 hours yet.

**Comment by Boostrix** [comment]
that would solve quite a few problems for many users - at least until there's proper checkpointing support.

In the meantime, I would also be in favor of getting this discussed, reviewed and hopefully integrated.
Memoization is a cheap thing these days - and the agent process is most of the time idle anyway, so it could just as well do something sensible.

**Pull request closed without merging**
