### PR TITLE
Ensure Python 3.10 & 3.11 compatability

### PR DESCRIPTION
**Pull request by drikusroor**
### Background

The requirements section of `README.md` says this project requires Python 3.8 _or higher_. Let's make sure that this is at least reflected in the CI.

### Changes

- Added Python versions 3.9, 3.10 & 3.11 to the Python version matrix in `ci.yml`

### Documentation

The documentation already said the requirements are "Python 3.8 or higher", and this is now also reflected in `ci.yml`.

### Test Plan

The CI should succeed for all configured Python versions.

### PR Quality Checklist
- [X] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts. **N/A**
- [X] I have considered potential risks and mitigations for my changes.
- [X] I have documented my changes clearly and comprehensively. **(docs were already there)**
- [X] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by nponeccop — APPROVED** [review]
It slows down the review process. But at some point will be nice to have. Also I'm not who decides on priorities I only check the basic requirements.

**Comment by drikusroor** [comment]
> It slows down the review process. But at some point will be nice to have. Also I'm not who decides on priorities I only check the basic requirements.

I'm not entirely sure if it actually slows down the review process. Aren't the jobs run in parallel? Is there an easy way to check this?

**Comment by nponeccop** [comment]
They are but there is concurrency limit. I guess with merge queues the impact will be smaller. So it's discussible.

**Comment by Androbin** [comment]
#2040 @Pwuts updated the requirements section of README.md to say this project requires Python **3.10** or higher.

See #2107

**Comment by Androbin** [comment]
Don't forget to update `.github/workflows/benchmark.yml` and `.devcontainer/Dockerfile`, see #2107

**Review by Pwuts — APPROVED** [review]

**Pull request merged**
