### PR TITLE
Docs - installation guide - docker compose: fix the mount path of workspace volume

### PR DESCRIPTION
**Pull request by mAlaliSy**
### Background

Docker compose file has a wrong mount path for the workspace volume

### Changes

Correct the mount path of workspace volume

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by anonhostpi** [comment]
PRs are pretty much on hold at the moment. See https://github.com/Significant-Gravitas/Auto-GPT/discussions/3856#discussioncomment-5818746

**Comment by Boostrix** [comment]
the mount path issue was mentioned recently, and it would be a "non-code" fix, and if it works, would solve the problem (of not being able to run) for probably hundreds of people (if not more), so this should probably be considered a potential candidate for review regardless of the ongoing re-arch effort - simply because it should not introduce new code, and because it should make the tool available to more folks again (=more potential contributors)

**Review by lookbeat — APPROVED** [review]
LGTM

**Comment by ntindle** [comment]
fixed in another pr

**Pull request closed without merging**
