### PR TITLE
Unused Functions removed from commands.py

### PR DESCRIPTION
**Pull request by sagarishere**
removed 3 unused functions:
:arrow_right: not used anywhere in the whole codebase of the repo.
:arrow_right: represent an abandoned approach which is no longer taken, most probably.

### Background
The 3 unused functions represent abandoned approach and contribute to clutter.

### Changes
Deleted / removed 3 unused functions.

### Test Plan
Unused functions. Do not need tests

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes.

### CODE REVIEW

**Comment by nponeccop** [comment]
@sagarishere There are conflicts now

**Comment by sagarishere** [comment]
@nponeccop I think this person who has write access to master combined everyone's pull request into one. So that's what is happening. https://github.com/Significant-Gravitas/Auto-GPT/commit/4bb7a598a502b9f9642bda63eb1c44c4663e5bff

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Pwuts** [comment]
The clean-up is appreciated, but they're already gone (by now). Thanks for submitting!

**Pull request closed without merging**
