### PR TITLE
Add defaults to env file for the AI Name and Role

### PR DESCRIPTION
**Pull request by joeswann**
### Background
Happy to close if not useful, was just the first change that came to mind and thought it might be nice to share.

### Changes
Changing a few lines to allow for name and role to be added to the env file (and thus not need to be filled in manually if they are often the same)

Note: Request is on stable as I am not up to speed on status of master, however happy to request there if preferable

### Documentation
Added lines to general settings in .env.template

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by arrenv — COMMENTED** [review]
Nice suggestion @joeswann, there is a lot of discussions about the encapsulation of the AI agents, for some discussion on this you can check out this https://github.com/Significant-Gravitas/Auto-GPT/discussions/3392

**Comment by Jabaar** [comment]
Maybe I don't quite understand the goal of your request, but how does this behave differently than using the `ai_settings.yaml` file? There are fields for `ai_goals`, `ai_name`, and `ai_role` where the defaults are stored.

**Comment by Boostrix** [comment]
This looks like a straightforward and useful change that is primarily about adding a new config option and appyling that as a default, which probably makes it a good candidate to be considered for review prior to/during the ongoging re-arch effort.

**Review by k-boikov — COMMENTED** [review]
Recently we moved the prompts to a .yaml, might be better to have those there too.

**Review by lc0rp — COMMENTED** [review]
@joeswann, thanks for your submission.

IMO, 
- AutoGPT remembers the most recently used AI name, role, and goals. Therefore, the proposed defaults might be obsolete after the first run. 
- For new users, setting these values during setup is more accessible than editing a file.
- One might as well edit the ai_settings.yaml rather than edit in two places: ai_settings and .env.

Instead, would you consider extending the current behavior to cover the following user story, which may cater to the challenges you outlined:
- As the user: I should skip the interstitial "see last settings" step. Instead, I should be able to accept or decline using the "last settings" individually for "AI Name," Role, and Goals and immediately access the "Choose AI Name" prompt with pre-filled settings for each of these items.

``` shell
$ python -m autogpt
... intro ...
> Select options, or Enter for previous values:
> AI Name [ResearchGPT]: ________________
> AI Role [An AI designed to autonomously ...]: _____________
> Goals [- World Peace, - Maximum Profit, - Zero Hunger] 
1. _________________ (Enter a blank line to accept previous values)
```

**Comment by ryanniccolls** [comment]
To edit autoGPT's AI Goals, Ai Name, Ai role and Ai budge edit the file "ai_settings.yaml" in the root folder.
That root folder is "AutoGPT version in numbers".
It is best to get an example of what to do by after starting Autogp set what you want to do. I will then set and save the AI_settings file. if you do not like how it is progressing you can stop by pressing "n" at the next opportunity to shut it down, and you will a good example to edit. . You can then edit the ai settings, then save it! 
on starting auto gpt again it will read the ai setting to you , and ask if you want it to continue.
The name of the AI does not matter, just the role and goals. GL 

good luck

example
`ai_goals:
- one of about 5 steps to achieve a goal.
ai_name: gptname
ai_role: the sentence about who and what you want it to be doing.
api_budget: 0.0
`

**Pull request closed without merging**
