### PR TITLE
Logs output to console if we're not on speak mode 

### PR DESCRIPTION
**Pull request by Zorinik**
I had a PR approved for this some weeks ago, but I think it got lost the very same night against another PR that did a major refactor. I think it is an important point so I am proposing it again, feel free to approve or discard of course.

### Background
I noticed that if we're not on speak mode, what the assistant want to say gets lost because it is not logged to console, sometimes losing precious info

### Changes
I added an "else" so that if the assistant doesn't speak directly (because we're not in speak mode), at least it is printed to console like the rest of the output.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by k-boikov** [comment]
Do we have an example where SPEAK actually has some more information value than THOUGHTS? Because I think with printing THOUGHTS we really don't need to print SPEAK. The idea in the prompt for SPEAK is to be used only for say_text imo.

**Comment by collijk** [comment]
you don't need this if/else.  Just log the thoughts.  The typewriter log has internal speak logic: https://github.com/Significant-Gravitas/Auto-GPT/blob/master/autogpt/logs.py#L90

**Comment by Zorinik** [comment]
> Do we have an example where SPEAK actually has some more information value than THOUGHTS? Because I think with printing THOUGHTS we really don't need to print SPEAK. The idea in the prompt for SPEAK is to be used only for say_text imo.

The LLM doesn't really know if we have speak mode enabled or not, so it often happens that it puts relevant info in that section, because that is the section that communicates with the user. I actually had the LLM asked me things over several tasks or claryfing what she was about to do better than the previous thoughts. That's why I think that info should not be lost, no reason to lose some of the output of the LLM.

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Review by k-boikov — APPROVED** [review]

**Review by k-boikov — APPROVED** [review]

**Pull request merged**
