### PR TITLE
Use latest alpine image for code execution

### PR DESCRIPTION
**Pull request by rickythefox**
### Background
Currently code execution uses a fat python 3.10 image.

### Changes
This PR replaces it with the smaller and newer 3.11 alpine image. This also ensures that an update to newer python versions will happen automatically as the `alpine` tag uses the latest stable python version.

### Documentation
N/A

### Test Plan
Integration test included.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by nponeccop — CHANGES_REQUESTED** [review]
Tests and image name changes are unrelated. Submit them apart in separate PRs.

Also besides alipne there are debian slim images and other options. At least keep Python version pinned.

**Comment by rickythefox** [comment]
@nponeccop I've split the PRs, will submit the test separately. 

Alpine is the smallest image, hence I chose alpine. 

When it comes to the version - the code generated by GPT can be reasonably assumed to use the latest python features, that's why I think we should use the latest version. I've pinned the major (3) although Python 4 ever coming out is (according to Guido) rather doubtful.

**Comment by nponeccop** [comment]
> code generated by GPT can reasonably be assumed to use the latest python features

Latest as of the training data, that is Sep 2021. I've just asked GPT+ if you are curious.

Q: What is the latest version of Python you are aware of?

3.5: As of my knowledge cutoff date of September 2021, the latest version of Python is 3.10.0, which was released on October 4, 2021.

4: As of my knowledge cutoff date in September 2021, the latest version of Python was Python 3.9.

Further investigation is needed, maybe 4 is just smarter to detect the contradiction but it's actually aware of 3.10

So this particular argument for the latest version doesn't hold.

**Review by nponeccop — DISMISSED** [review]

**Comment by rickythefox** [comment]
> So this particular argument for the latest version doesn't hold.

3.x should be backwards-compatible anyway.

**Comment by nponeccop** [comment]
Yes, there are other arguments in favor of the latest python, just not the GPT generated code one.

**Comment by rickythefox** [comment]
> Yes, there are other arguments in favor of the latest python, just not the GPT generated code one.

You're right.

**Comment by rickythefox** [comment]
@nponeccop same change applied to the refactored code, please review again. Sorry to bother you, but the codebase is changing from right under me.

**Comment by nponeccop** [comment]
@rickythefox There are conflicts now

**Comment by rickythefox** [comment]
@nponeccop fixed

**Comment by nponeccop** [comment]
@rickythefox There are conflicts now

**Comment by rickythefox** [comment]
@nponeccop fixed (jesus christ this is changing fast)

**Comment by nponeccop** [comment]
@rickythefox There are conflicts now

**Comment by rickythefox** [comment]
@nponeccop fork synked

**Comment by rickythefox** [comment]
@nponeccop merged again

**Review by p-i- — APPROVED** [review]
👍

**Pull request merged**
