### PR TITLE
Add 1/0 as an alternative to y/n for non-english users

### PR DESCRIPTION
**Pull request by Francisco-Montanez**
### Background

A user can communicate with Auto-GPT in a language other than English that does not contain the letters y, n. In this case, the user have to change the keyboard layout between simple and text response to English and back. The numbers are (most likely) the same in any layout.

### Changes

The addition of 1/0 has been added as alternatives to y/n in the main.py script to allow non-English speaking users to communicate with Auto-GPT more easily.

### Documentation

In the main.py script, a comment has been added to explain that 1/0 can be used as an alternative to y/n for non-English speaking users.

### Test Plan

To test this functionality, I performed the following steps:
- Changed the keyboard layout to a language other than English that does not contain the letters y, n.
- Prompted Auto-GPT for a response that requires a y/n input.
- Verified that entering 1/0 instead of y/n returned the expected response from Auto-GPT.

As this is a relatively small and straightforward change, no new test cases were added.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thouroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by nponeccop — APPROVED** [review]

**Review by Pwuts — DISMISSED** [review]

**Comment by Pwuts** [comment]
Doing a final check whether this is actually necessary..

**Review by coditamar — APPROVED** [review]
looks good to me. (why not)

**Comment by Pwuts** [comment]
@Francisco-Montanez can you give an example of a keyboard layout where y/n would be a problem?

**Comment by coditamar** [comment]
I have a suggestion:
To move it to the config file.
Anyone can configure these anyway they want, but the default is y/n

**Comment by Pwuts** [comment]
@Francisco-Montanez we would love to have some version of this to improve i18n. But instead of adding a hard-coded 1/0 option, please make the y/n configurable in the settings as @coditamar suggests. That way it doesn't cause extra clutter on users' screens, but can still be used by users who really have trouble typing y/n.

**Comment by Pwuts** [comment]
Closing in favor of #3178

**Pull request closed without merging**
