### PR TITLE
add proxy function

### PR DESCRIPTION
**Pull request by Weltolk**
### Background

Some features can only be accessed through a proxy in some countries

### Changes

1. Added proxy support for OpenAI
2. Added proxy support for ElevenLabs
3. Added proxy support for PINECONE
4. Added proxy support for Google API
5. Added proxy support for Hugging Face API
6. Added related instructions in README.md

### Documentation

1. Modifications are modelled on the existing sibling code with comments added
2. Added relevant notes in README.md

### Test Plan

1. In a network environment where certain features are not accessible
2. Configure proxies for these functions in .env
3. Run the project
4. Run successfully

### PR Quality Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [x] I have thouroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by Jeandoom — COMMENTED** [review]
well done

**Review by Jeandoom — APPROVED** [review]
well done

**Comment by mabooooo** [comment]
we need this update

**Comment by merwanehamadi** [comment]
@Weltolk please solve conflicts I will test it

**Comment by Weltolk** [comment]
> @Weltolk There are conflicts now

I'm sorry, I don't have enough time to commit the new code at the moment

**Comment by Weltolk** [comment]
> @Weltolk please solve conflicts I will test it

I'm sorry, I don't have enough time to commit the new code at the moment

**Pull request closed without merging**
