### PR TITLE
Stable

### PR DESCRIPTION
**Pull request by ehei**
### Background
While running with the 'y -XXX' prompt, I found myself wanting to know how many steps had been performed, and how many were left out of how many I had authorized. Additionally, I wanted a way to interrupt the process without resorting to crashing the system or killing a process outright.

### Changes
I created several variables to track both if an interrupt of the process was desired, by checking for the CTRL key being held down, and provided feedback in the output to show how many steps have been completed out of the total, and what the percentage done was.

### Documentation
I add several comments like at line 472 (check for CTRL press, interrupt) and a comment where the addition to the prompt for feedback was created, as well as where the percentage done was calculated. Atomic tests for those could be pulled out, but I didn't want to continue falling being all the development. Happy to follow this up with pulling out methods and/or developing some decent tests if warranted.

### Test Plan
Ran the app with several scenarios, including:
- Run with just 'y'
- Run with 'y -1' and let it complete
- Run with 'y -2' and let it complete
- Run with 'y -10' and stop with CTRL part way, then use 'c' to continue
- Run with 'y -500' and stop someplace without continuing

### PR Quality Checklist
- [X] My pull request is atomic and focuses on a single change.
- [X] I have thoroughly tested my changes with multiple different prompts.
- [X] I have considered potential risks and mitigations for my changes.
- [X] I have documented my changes clearly and comprehensively.
- [X] I have not snuck in any "extra" small tweaks changes 

As stated earlier, I did not add any tests for this PR, but would be happy to revisit tests and refactoring the user prompting and feedback if desired.

Looking forward to any and all feedback. Thanks!

### CODE REVIEW

**Comment by merwanehamadi** [comment]
@ehei hey sorry for the recent conflicts, if you push we'll definitely prioritize this.

**Comment by Pwuts** [comment]
We can't merge into `stable` though, so please change the base branch to `master`.

**Comment by ehei** [comment]
Ah, sorry,  I'll switch it over.  Looked like stable was the new
main/master.

**Comment by Pwuts** [comment]
Overlaps with #2069

**Comment by Pwuts** [comment]
@ehei please reopen and @BillSchumacher will fix it

**Comment by Pwuts** [comment]
Blocked by #2481

**Pull request closed without merging**
