### PR TITLE
Refactor ai functions

### PR DESCRIPTION
**Pull request by Riddle1001**
Moved all the ai functionality into one place - ai_functions.py.

To test: Run it for a little while, you will see no errors.

### CODE REVIEW

**Review by nponeccop — APPROVED** [review]
LGTM but the scope is too big. We can try splitting, but I guess it's better to wait until the trivial PRs get all merged.

**Comment by nponeccop** [comment]
@Riddle1001 Resolve the conflicts

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Pwuts** [comment]
Closing this PR because no activity since original submission and huge conflicts with `master`. Still, we would be happy to keep you involved; feel free to join in on the action via discord!

**Pull request closed without merging**
