### PR TITLE
Use ruff

### PR DESCRIPTION
**Pull request by khadrawy**
### Background
[Ruff](https://beta.ruff.rs/) is a fast linter for Python that aims to be orders of magnitude faster than alternative tools while integrating more functionality behind a single, common interface.

### Changes
- Use Ruff precommit hook.
- Fix some violations.

### Documentation
No logic changes, just formatter with precommit.

### Test Plan
No logic changes, just formatter with precommit.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes 

No logic changes, just formatter with precommit.

### CODE REVIEW

**Comment by nponeccop** [comment]
@richbeales @BillSchumacher This is a duplicate of #1136 closed as wontfix. People keep insisting.

**Comment by khadrawy** [comment]
> @richbeales @BillSchumacher This is a duplicate of #1136 closed as wontfix. People keep insisting.

My bad, I didn't search closed PRs.
I see from comments on other PR that flake8 is sufficient right now or the focus is not on adapting new linter and that's totally understandable.
Just for discussion, do you think that current linter is sufficient? I have already some violations that was either not caught or ignored. wouldn't it be better to set up a strong linter rules (with ruff or any other tool) before the codebase gets more and more complicated?

**Comment by nponeccop** [comment]
It isn't sufficient. With a big backlog, we introduce stricter linting gradually, in order not to break too many PRs with relatively silly required changes. See for exampe #1151 and the planned tightening in the last comment there

**Comment by khadrawy** [comment]
Thanks @nponeccop for clarification. I will close this PR for now.

**Pull request closed without merging**
