### PR TITLE
Add aiohttp server

### LINKED ISSUE #1222: Consider providing API?
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Is it in consideration to provide an API?

### Examples 🌈

_No response_

### Motivation 🔦

So that people can create applications using auto-gpt.

### PR DESCRIPTION
**Pull request by Androbin**
### Background

Fixes #1222
See #1216

### Changes

Added an aiohttp server that can be used to build alternative frontends and use cases for Auto-GPT.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by itaim** [comment]
Hi, 
Could you take a look at: https://github.com/Torantulino/Auto-GPT/pull/386?

**Comment by Androbin** [comment]
@Pwuts Please do correct me if I'm wrong but it is my understanding that the plugin system is about AutoGPT calling into a backend extension, whereas this PR is about a frontend extension calling into AutoGPT via an API.

**Comment by Pwuts** [comment]
We're looking into it. Question for us is mainly whether this fits into our more long-term plan, which does involve an API but in a different architecture.

**Comment by p-i-** [comment]
We're moving forwards async-ing the code with trio.
We're also working on achieving 'stateless'.
We should get these things in place before we consider implementing a webserver.
@Androbin You're welcome to ping me on the AutoGPT Discord pi#8377

**Comment by ntindle** [comment]
I love the idea and agree it's needed, but we need to make some changes for this to work. I'm going to go ahead and close this, for now, to help clear our backlog of PRs.

**Pull request closed without merging**
