### PR TITLE
fix shirt-sizing workflow permissions

### PR DESCRIPTION
**Pull request by Pwuts**
### Background
Apparently this needs some more permissions (even though the `conflicts` labeler doesn't)

### Changes
* Added `issues: write` permission to the `size` workflow

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by Pwuts** [comment]
cc @ntindle

**Comment by ntindle** [comment]
Duplicate this pr on your fork to test it

**Comment by Pwuts** [comment]
Works: https://github.com/Pwuts/Auto-GPT/actions/runs/4749517856/jobs/8436856578?pr=2

**Review by ntindle — APPROVED** [review]
LGTM

**Review by p-i- — APPROVED** [review]

**Comment by ntindle** [comment]
Now we wait for a pr to see if it gets sized

**Comment by ntindle** [comment]
A pr got sized size/l

**Pull request merged**
