### PR TITLE
Update commands.py to support bitcoin commands

### PR DESCRIPTION
**Pull request by dbscooper**
Bitcoin handling for payments via bitcoin_utils.py

### PR Quality Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have thouroughly tested my changes with multiple different prompts.
- [ ] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [ ] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by MeditationMatt** [comment]
i have never participated in github before.  But this is the beginning of AGI.  Let's go.  with bitcoin blockchain and AGI.  The Moon is a Harsh Mistress is now a baseline.

**Review by nponeccop — APPROVED** [review]

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by anonhostpi** [comment]
Now this should be very interesting.

**Comment by Boostrix** [comment]
This is something that would be almost certainly better implemented as a separate plug-in extending the new command manager

**Comment by anonhostpi** [comment]
See https://github.com/Significant-Gravitas/Auto-GPT/pull/3824

**Comment by ntindle** [comment]
Hello!  We sincerely appreciate your contribution to our project. Please note that only essential features will be merged into the main repository. Thus, we encourage you to open a pull request in the [Auto-GPT-Plugins](https://github.com/Significant-Gravitas/Auto-GPT-Plugins) repository.  If you encounter difficulties converting your code into a plugin, please do not hesitate to seek assistance from the #plugins-chat on our Discord Server.  We look forward to your contribution to the Plugins repository and apologize for any inconvenience this may have caused.

**Pull request closed without merging**
