### PR TITLE
Refactorization  : changes ai_ to agent_

### PR DESCRIPTION
**Pull request by ph-ausseil**
### Background
Setting bases for: #3316 

### Changes
* Change occurrence of ai_ to agent_
* Move ai_config.py to project/project_config_broker setting bases for project creation

### Test Plan
runned the app several times with no issue

### PR Quality Checklist
- [ x] My pull request is atomic and focuses on a single change.
- [ x] I have thoroughly tested my changes with multiple different prompts.
- [ x] I have considered potential risks and mitigations for my changes.
- [x ] I have documented my changes clearly and comprehensively.
- [x ] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by collijk** [comment]
This just does a find and replace on `ai` -> `agent` which

1. Is done without intention, so we get bad maps like `openai` -> `openagent`
2. Is unmotivated
3. Most importantly: breaks a user contract by renaming a public facing file `ai_config.yaml`.  

We are working on a concrete plan and the infrastructure to add multi-agent systems. It is a regularly requested feature and we get many PRs/issues about it. There are several very important and very difficult problems to solve along the way.  We will loop you in to the planning process when some key staff are back and available.  Thanks!

**Comment by ph-ausseil** [comment]
> This just does a find and replace on `ai` -> `agent` which
> 
> 1. Is done without intention, so we get bad maps like `openai` -> `openagent`
> 2. Is unmotivated
> 3. Most importantly: breaks a user contract by renaming a public facing file `ai_config.yaml`.
> 
> We are working on a concrete plan and the infrastructure to add multi-agent systems. It is a regularly requested feature and we get many PRs/issues about it. There are several very important and very difficult problems to solve along the way. We will loop you in to the planning process when some key staff are back and available. Thanks!

Allow me to disagree : 
1 - Did you look for an "openagent" , there is none I looked for it. 
3 - I have also added 2 line for the .gitignore.

2 - it is motivated actually and I got encouraged to do it by @merwanehamadi 
Finally it is mo

**Comment by Pwuts** [comment]
> Allow me to disagree :
> 1 - Did you look for an "openagent" , there is none I looked for it.

The config property `openai_api_key` is renamed to `openagent_api_key`.
There are also a couple of items you missed, such as `AI_SETTINGS_FILE`.

> 3 - I have also added 2 line for the .gitignore.

That doesn't change the fact that this is a breaking change for users. Their `ai_settings.yaml` file will no longer be recognized by Auto-GPT.

> 2 - it is motivated actually

Then please add the motivation to the PR description :)

**Comment by ph-ausseil** [comment]
Hey Pwuts, 

> That doesn't change the fact that this is a breaking change for users. Their ai_settings.yaml file will no longer be recognized by Auto-GPT.

This was a bad PR, lead by too much frustration are having to redo things I would have made cleanly when I was head cold. In a situation, where I rushed myself to get something going. I've been able to express that absence of visibility was frustrating & it's a lesson learned. 

Your feedbacks where helpful @Pwuts , `AI_SETTINGS_FILE` was as is on purpose because it is in .env and .env is in the gitignore. I also let all ai_settings in `cli.py` & `main.py` to avoid significative change.

There was actually no break (I deleted my agent_settings.yaml files to tests), however doing so I added inconsistency.

You feedback where helpful as I identified two minors glitch with error messages been static : 
image
image

**Pull request closed without merging**
