### PR TITLE
[Bugfix] Fix memory add

### PR DESCRIPTION
**Pull request by tusharmakkar08**
### Background
Adding memory add back

### Changes
Memory add was removed from prompt during refactoring

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by hdkiller** [comment]
I believe this PR needs to be refactored according to the new structure introduced by the plugins merge.

**Comment by tusharmakkar08** [comment]
@hdkiller Can you PTAL? I have resolved merge conflicts.

**Comment by tusharmakkar08** [comment]
@richbeales Can you have a look?

**Comment by richbeales** [comment]
Please run "black ." to fix formatting

**Comment by tmakkar-eightfold** [comment]
@richbeales Added black formatting. PTAL.

**Comment by tmakkar-eightfold** [comment]
Any updates on this? @richbeales

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Pwuts** [comment]
This is incompatible with the new memory system, which is tracked in #3536. It may take a while to finish, but once it's done, should boost Auto-GPT's performance a huge deal.

**Pull request closed without merging**
