### PR TITLE
Use `@command()` function decorator

### PR DESCRIPTION
**Pull request by Androbin**
### Background

See #1272 @rhernaus
> Optimize the `execute_command` function. The original function used a series of `if-elif` statements to determine the appropriate action based on the given command name. This structure made the code lengthy, harder to read, and difficult to maintain. By refactoring the function to use a dictionary that maps command names to their respective functions, we can improve readability, conciseness, and maintainability.

### Changes

See https://github.com/Significant-Gravitas/Auto-GPT/pull/1272#issuecomment-1510688932

Commands are now registered like this:

```python3
@command()
def start_agent(name: str, task: str, prompt: str) -> str:
    ...
```

Or alternatively:

```python3
@command(name="start_agent", aliases=["start_new_agent"])
def do_start_agent(name: str, task: str, prompt: str) -> str:
    ...
```

They're later called with `command(**arguments)` syntax, meaning arguments are assigned by name.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [X] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by Androbin** [comment]
`Python CI / build (3.8)` currently fails due to Python 3.8 choking on some type hints.
With Python 3.10 (New minimum version since #2040), there are no issues.

**Comment by Androbin** [comment]
@nponeccop PTAL at this and #2107

**Comment by Androbin** [comment]
`Python CI / build (3.8)` currently fails due to Python 3.8 choking on some type hints.
With Python 3.10 (New minimum version since #2040), there are no issues.

**Comment by BillSchumacher** [comment]
This is a duplicate of the command registry that is included in #757 but less advanced. Sorry but this is going to make it.

**Pull request closed without merging**
