### PR TITLE
Wikipedia Search Command

### PR DESCRIPTION
**Pull request by pierluigi-failla**
### Background

Wikipedia Search could provide the capability of searching for encyclopedia-like information and, in this sense, I think is a very relevant and general command to have. I will be more than happy to update it later to the plugin template once will be merged to stable.

### Changes

Added Wikipedia Search command.

### Documentation

The new command `wikipedia_search` will search in Wikipedia for relevant information. The resulting string is a `json.dumps` of a list of len `num_results` containing dictionaries with the following structure: `{'title': <title>, 'summary': <summary>, 'url': <url to relevant page>}`.

### Test Plan

As far as this is a very simple functionality I not added tests as per some other similar functionality.  

### PR Quality Checklist
- ✔️ My pull request is atomic and focuses on a single change.
- ✔️ I have thoroughly tested my changes with multiple different prompts.
- ✔️ I have considered potential risks and mitigations for my changes.
- ✔️ I have documented my changes clearly and comprehensively.
- ✔️ I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by pierluigi-failla** [comment]
@rocks6 my2cents are: Google indexes website while Wikipedia is an online encyclopedia. Your point is correct and indeed in my tests GPT discriminates quite well when to use `google_search` (e.g. searching articles, news, general comments...) or `wikipedia_search` (e.g. look for definition, factual information, historical facts...), if we have only `google_search` relevant Wikipedia pages may be not in the top few results.

**Comment by rocks6** [comment]
That makes sense, if the model knows wikipedia is an authoritative source for information it may be more inclined to search it directly to improve its results

**Comment by pierluigi-failla** [comment]
I messed up with conflicts I will create a clean pr.

**Comment by hdkiller** [comment]
Hello!

We sincerely appreciate your contribution to our project. Please note that only essential features will be merged into the main repository. Thus, we encourage you to open a pull request in the [Auto-GPT-Plugins](https://github.com/Significant-Gravitas/Auto-GPT-Plugins) repository.

If you encounter any difficulties in converting your code into a plugin, please do not hesitate to seek assistance from the #plugins-chat on our [Discord Server](https://discord.gg/autogpt).

We look forward to your contribution to the Plugins repository, and we apologize for any inconvenience this may have caused.

**Pull request closed without merging**
