### PR TITLE
web server with create agent endpoint

### PR DESCRIPTION
**Pull request by merwanehamadi**
### Background

REST API because:
- soap is old, graphql is oftentimes overkill and not very beginner friendly, gRPC is not yet supported widely by web browsers
- websockets endpoints will be needed but only to complement the REST API to get live updates. For example if I want to create an agent as a frontend engineer, I don't need to do it through websockets. But websockets will be needed to subscribe to channels (conversations, debugging info, logs, I have many of these channels ready in a branch). These channels will allow a human to understand what his agents are doing, but they can also be used by a mother autoGPT to orchestrate its children.

### Changes

Added:
- the POST /agents endpoint
- the docker-compose.dev.yml and dockerfile_dev because we need one.

### Documentation

Repo of the api following this structure:
```
Auto-GPT/
├─ autogpt/
│  ├─ models/ ## defines the class that will interact with the DB
│  │  └─ agent.py
│  ├─ tests/ ## tests within the main module, this is very common
│  │  ├─ v1/ ## versioning is key
│  │  │  ├─ features/
│  │  │  │  ├─ agents/
│  │  │  │  │  ├─ create_agents
│  │  │  │  │  ├─ start_agents
│  │  │  │  │  └─ stop_agents
│  │  │  │  ├─ conversation/
│  │  │  │  │  └─ create_conversation
│  │  │  │  ├─ commands/
│  │  │  │  │  └─ create_commands
│  │  │  │  ├─ prompt/
│  │  │  │  │  └─ create_prompts
│  │  │  │  ├─ goals/
│  │  │  │  │  └─ create_goals
│  │  │  │  ├─ metrics/
│  │  │  │  │  └─ create_metrics
│  │  │  │  ├─ events/
│  │  │  │  │  └─ subscribe_events
│  │  │  │  └─ etc...
│  │  │  └─ unit/
│  │  └─ conftest/ ## configuration for tests
├─ v1/
│  ├─ endpoints/ ## all the routes here
│  │  └─ agents.py
│  └─ router/
└─ static/ ## api documentation, very useful to integrate
```
### Test Plan

Screenshot 2023-04-13 at 6 08 39 AM
Screenshot 2023-04-13 at 8 50 25 AM

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by nponeccop — APPROVED** [review]

**Comment by merwanehamadi** [comment]
@Torantulino we can discuss about these additions, I know it's a lot of things added, but that's what we need to set a good direction for the future backend development. I still think autogpt should remain a great CLI, and I will make sure the API and the CLI use the same components.
You can trust me to maintain this api, along with the FastAPI community, which I am sure will be very excited to see AutoGPT use this framework. FastAPI is not very complicated, people that know flask can also maintain it.

**Comment by 0xArty** [comment]
I've been thinking that reorganizing the project by moving the code from **scripts** into an **autogpt** module could be beneficial. This modular approach would enhance the organization and maintainability of the codebase, effectively separating concerns and promoting code reusability.

We then could incorporate the API server as a submodule of the **autogpt** module or as a separate module named **server** which would further streamline the project structure. This would allow for a clear distinction between the core functionalities and the server component, making it easier to manage and maintain each part independently.

**Comment by nponeccop** [comment]
@BillSchumacher will improve the organization without breaking things.

**Comment by 0xArty** [comment]
@nponeccop and @BillSchumacher  I created a PR which starts on the reorg path whilst keeping changes to a minimum:
https://github.com/Torantulino/Auto-GPT/pull/1191

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Pull request closed without merging**
