### PR TITLE
Lets agent get number of astronauts in space.

### PR DESCRIPTION
**Pull request by sr5434**
### Background
The current agent cannot access real-time information about how many astronauts are in space.

### Changes

This uses the open notify api to get information about how many astronauts are in space.

### Documentation

I included a docstring for the function that fetches the data.

### Test Plan

I haven’t tested it, as I added my code on the main branch which is currently broken

### PR Quality Checklist
- [ x ] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [ x ] I have considered potential risks and mitigations for my changes.
- [ x ] I have documented my changes clearly and comprehensively.
- [ x ] I have not snuck in any "extra" small tweaks changes 

I didn’t add tests because I forked master which is broken

### CODE REVIEW

**Review by nponeccop — APPROVED** [review]

**Comment by nponeccop** [comment]
CI will be red.

**Comment by sr5434** [comment]
Is that going to be a problem?

**Comment by nponeccop** [comment]
Yes you are supposed to fix it. Usually it's extra space, or broken tests

**Comment by sr5434** [comment]
Can you reapprove the changes so that the CI job can rerun?

**Review by nponeccop — APPROVED** [review]

**Review by nponeccop — APPROVED** [review]

**Comment by sr5434** [comment]
Can you merge this? It passed the CI

**Comment by nponeccop** [comment]
@richbeales ? Should he wait for plugins?

**Comment by sr5434** [comment]
If we wait for plugins, will I have to rewrite my code?

**Comment by nponeccop** [comment]
Yes, unfortunately.

**Comment by sr5434** [comment]
Ok, it is not too much code to reimplement.

**Comment by sr5434** [comment]
@richbeales should I wait for plug-ins to come out?

**Comment by hdkiller** [comment]
Hello!

We sincerely appreciate your contribution to our project. Please note that only essential features will be merged into the main repository. Thus, we encourage you to open a pull request in the [Auto-GPT-Plugins](https://github.com/Significant-Gravitas/Auto-GPT-Plugins) repository.

If you encounter any difficulties in converting your code into a plugin, please do not hesitate to seek assistance from the #plugins-chat on our [Discord Server](https://discord.gg/autogpt).

We look forward to your contribution to the Plugins repository, and we apologize for any inconvenience this may have caused.

**Pull request closed without merging**
