### PR TITLE
README: Explain OpenAI billing for API key (Fixes issue about "API Rate Limit Reached. Waiting 20 seconds ... Failed to get response after 5 retries")

### PR DESCRIPTION
**Pull request by JuroOravec**
### Background

There's multiple issues, where people hit OpenAI API rate limiting error, where the true cause of the rate limiting is that people have not set up billing (paid account) on their OpenAI profile.

The truth is, one has to:

1. Opt in to "paid account" on https://platform.openai.com/account/billing/overview and enter their billing info
2. Only now request the API key (in my case it took about 5-10 mins after opting into paid account before the API key started to work via AutoGPT.

As of 12:00 14/04/2023, I found these related issues:

Examples:
- https://github.com/Torantulino/Auto-GPT/issues/75
- https://github.com/Torantulino/Auto-GPT/issues/79
- https://github.com/Torantulino/Auto-GPT/issues/189
- https://github.com/Torantulino/Auto-GPT/issues/235
- https://github.com/Torantulino/Auto-GPT/issues/425
- https://github.com/Torantulino/Auto-GPT/issues/585
- https://github.com/Torantulino/Auto-GPT/issues/1047
- https://github.com/Torantulino/Auto-GPT/issues/1073
- https://github.com/Torantulino/Auto-GPT/issues/1174
- https://github.com/Torantulino/Auto-GPT/issues/1189
- https://github.com/Torantulino/Auto-GPT/issues/1203
- https://github.com/Torantulino/Auto-GPT/issues/1227
- https://github.com/Torantulino/Auto-GPT/issues/1248
- https://github.com/Torantulino/Auto-GPT/issues/1252
- https://github.com/Torantulino/Auto-GPT/issues/1262

Possibly also
- https://github.com/Torantulino/Auto-GPT/issues/1010
- https://github.com/Torantulino/Auto-GPT/issues/815
- https://github.com/Torantulino/Auto-GPT/issues/1013

### Changes

Make this explicit in the README file. I've moved the sentence on OpenAI API key to it's own section, so we can also include an image showing exactly what one has to do

Screenshot 2023-04-14 at 12 32 56

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by JuroOravec** [comment]
CC @Torantulino 

(Or @nponeccop, are you a maintainer too? Because I just saw that you were active around :D)

**Comment by JuroOravec** [comment]
And this is how the README section looks now

Screenshot 2023-04-14 at 13 45 58

**Comment by nponeccop** [comment]
@JuroOravec I'm not but I'm coordinating the merges and do preliminary reviews and conflict resolution notifications. The maintainers are @p-i- and @richbeales and @Torantulino obviously.

**Comment by DHRUV-CODER** [comment]
Sent a [pull request](https://github.com/Torantulino/Auto-GPT/pull/1286/commits/13b2912bf097784e15ef12412dae1aa5cc84b88e) which shows the error regarding the billing problem (but only in debug mode) ,there are more errors which are not shown in detail. Would love to see more updates regarding this problem .

**Review by jpollard-cs — APPROVED** [review]
Looks good to me! Thank you for also doing the cleanup work!

**Review by nponeccop — APPROVED** [review]

**Review by sarat9 — APPROVED** [review]

**Review by nponeccop — APPROVED** [review]

**Review by richbeales — APPROVED** [review]

**Comment by KunLiam** [comment]
> 这就是 README 部分在更改后的样子
> 
> 屏幕截图 2023-04-14 at 13 45 58

OpenAI can set up paid accounts, is there a limit for the region, which regions can set up?

**Pull request merged**
