### PR TITLE
Migrate to poetry

### PR DESCRIPTION
**Pull request by rickythefox**
### Background
Based on https://github.com/Torantulino/Auto-GPT/pull/367

### Changes
Migrate to poetry for requirements management.

### Documentation
README.md is updated to reflect the change.

### Test Plan
```
$ docker build . -t autogpt-fork
$ docker run -it --rm autogpt-fork   
```

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by rickythefox** [comment]
@nponeccop please have a look

**Comment by nponeccop** [comment]
Cross-link the PR numbers.

**Review by nponeccop — APPROVED** [review]

**Review by nponeccop — APPROVED** [review]

**Comment by rickythefox** [comment]
I will sync the fork once we agree on the version handling per above.

**Comment by rickythefox** [comment]
@p-i- @richbeales any chance for input on the version resolution question so I can rebase this PR onto the latest master?

**Comment by p-i-** [comment]
@rickythefox My vote would be for letting Poetry figure the versions out, rather than pinning versions.

Yes it's possible that some version update could cause an issue, but it feels so much cleaner to keep it floating and fix in the unusual event of a conflict.

How about we stick with (1) for now?

**Comment by rickythefox** [comment]
@p-i- perfect, then my last update handled that  II will rebase within a free hours

**Comment by rickythefox** [comment]
Updated and pushed. Note that I pinned `playsound = "1.2.2"` as 1.3.0 does not seem to build the wheel and 1.2.2 was the version used in requirements.txt anyway. If you want I can also include deleting requirements.txt into this PR. @nponeccop @p-i-

**Comment by 0xArty** [comment]
@rickythefox 
2 deps that are in master are missing from the poetry deps:
```
pymilvus
redis
```

Please can you add them

**Comment by richbeales** [comment]
Conflicting files
Dockerfile

**Comment by rickythefox** [comment]
Fixed and added pymilvus and redis. Dev dependencies are not installed when building docker image.

**Review by richbeales — APPROVED** [review]

**Comment by merwanehamadi** [comment]
@rickythefox thank you very much ! there was some issues on some pipelines plus recent dependencies commented so we kept your work commits and created 
https://github.com/Significant-Gravitas/Auto-GPT/pull/1736

**Comment by merwanehamadi** [comment]
https://github.com/Significant-Gravitas/Auto-GPT/pull/1736

Hey @rickythefox we started implementing poetry, and I am personally a fan of it.
And then I started thinking about how it could affect regular users and this is my concern: 
- this is a mainstream project, people might not know poetry, they might just have 2 hours of python code behind them (again, I am not sure about that)
- more things to type for users
- overhead (when you know poetry you can fix it, but a lot of users don't)

So I am not saying no (in fact I can't we can all push to the repo technically).

I am just saying I am not so sure about this being a good move for all users.

**Comment by rickythefox** [comment]
@merwanehamadi well, the way I see it poetry will be more user-friendly. 
1. Virtual environments are created by default. For someone not familiar with the venv, just using pip to install from requirements.txt would pollute the global python installation and likely lead to conflicts.
2. Dependency resolution is nicely handled by poetry.
3. Typing `poetry run` takes 10 keystrokes.
4. I'm not sure you would be able to alter the codebase with 2 hours of python behind you, poetry or no poetry (prose?).

**Comment by happysalada** [comment]
@merwanehamadi I'm coming to this issue trying to package this for a linux distribution.
Packaging with poetry would make maintainers life much easier, ultimately if you want distribution, having this installable on any distribution with a simple command would be the best IMO.
poetry will on top of that enable build reproducibility, in turn you could check binaries with a sha256 to verify noone tempered with it. I realise this is a minor benefit, but it reproducibility enables several linux distribution to actually package this. For example, it won't be possible to package this into nixos without poetry.

**Comment by merwanehamadi** [comment]
I am fine if we move forward with that, I love poetry. As long as we have all users in mind, not just maintainers.

**Comment by nponeccop** [comment]
@rickythefox CI is red

**Comment by rickythefox** [comment]
@nponeccop should be ok now

**Comment by rickythefox** [comment]
@nponeccop so will this be merged or should I close the PR?

**Comment by rickythefox** [comment]
@nponeccop ok, I'll hold off merging any conflicts until you say go.

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Pwuts** [comment]
Related:
* #1179 
* #1955

**Comment by Miuler** [comment]
Any news on poetry adoption?

**Comment by Pwuts** [comment]
Getting this up-to-date was too complicated, so I started over in #5219. I've credited you as co-author @rickythefox :)

**Pull request closed without merging**
