### PR TITLE
Fix Command send_tweet error

### PR DESCRIPTION
**Pull request by doutv**
**Most contributions go to @mossy426 @Kendhal7, they provide the code and detailed documents.**

### Background

Problem: 
The following error occurs while using the `send_tweet` command using the stable version.
```
NEXT ACTION: COMMAND = send_tweet ARGUMENTS = {'text': 'Test'}
SYSTEM: Command send_tweet returned: Error: 'Forbidden' object has no attribute 'reason'
```

Solution:
1. For Free Twitter API account, it can only use Twitter API v2 for tweet creation. Use `tweepy.Client` instead of `tweepy.API`, which supports Twitter API v2.
2. Twitter API V2 requires a bearer token and will need to setup OAuth 2.0 in dev portal.

See this issue for details: #2194 
### Changes

1. `send_tweet` command in `twitter.py`: change to Twitter API V2 and OAuth 2.0. Use `tweepy.Client` instead of `tweepy.API`. Add a bearer token.
2. `README.md`: add Twitter API settings guide in details.
3. `.env.template`: add a new variable `TW_BEARER_TOKEN`.

### Documentation

I add detailed Twitter API settings guide in README.

### Test Plan

Since the change is small, I didn't add any test case. 
It requires Twitter API settings and manual testing, I hope more people test this solution and give me more feedback.

One quick way to test:
1. Set up Twitter API follow the guide in README, and set 5 Twitter variables in `.env`.
2. Paste the below content in `ai_settings.yaml`.
```yaml
ai_goals:
ai_name: Twitter-GPT
ai_role: send a tweet "Hello World! I am Auto-GPT."
```
3. Run `python -m autogpt`.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by JamesFincher — APPROVED** [review]

**Review by JamesFincher — APPROVED** [review]
Looks good!

**Review by JamesFincher — DISMISSED** [review]

**Review by mossy426 — DISMISSED** [review]
Have the same implementation and this works for me!

**Review by mossy426 — APPROVED** [review]
Code is accurate for the fix I made for using Twitter API V2 for sending tweets

**Comment by doutv** [comment]
@Pwuts @BillSchumacher 
Could you help me approve this pr? Thanks a lot!

**Comment by desojo** [comment]
Extended Twitter functionality will be covered under plugins in the future, and the baked in twitter integrations will likely become deprecated.

The v2 API is good for simply posting tweets, but you can't pull any information from twitter without paying $100/mo for 10k read ops. 

The plugin I'm currently working on uses the v1.1 API and is capable of carrying on conversations and taking tasks from twitter users. Although this v1.1 API will likely become deprecated in the future, it's currently the only way for users to allow their Auto-GPT instance to fully interact with the Twitter API.

**Comment by BillSchumacher** [comment]
Yeah this needs to be fixed here: https://github.com/Significant-Gravitas/Auto-GPT-Plugins

**Comment by doutv** [comment]
Got it. I will move to the plugin system and close this pr.

**Pull request closed without merging**
