### PR TITLE
Fix/dockerfile permissions

### LINKED ISSUE #1274: Main.py fail into Docker for permissions
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

docker build -t autogpt:0.1.0 .
docker run -it --env-file .env autogpt:0.1.0

### Current behavior 😯

image (1)

### Expected behavior 🤔

image (3)

### Your prompt 📝

_No response_

### PR DESCRIPTION
**Pull request by DVentas**
### Background

With the last changes in Dockerfile, autogpt doesnt work correctly because need permission over path ".."

Closes #1274 

### Changes

Add ownership over path ".." (or /home)

### Test Plan

Working after change in docker

### PR Quality Checklist
- [X] My pull request is atomic and focuses on a single change.
- [X] I have thoroughly tested my changes with multiple different prompts.
- [X] I have considered potential risks and mitigations for my changes.
- [X] I have documented my changes clearly and comprehensively.
- [X] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by richbeales — APPROVED** [review]

**Comment by richbeales** [comment]
Needs review from someone who's using Docker before we merge.

**Comment by mikekelly** [comment]
@richbeales yep thanks this issue is caused by how docker is mounted into containers, there's no need to give the user access to the entire home directory as per this PR - I've resolved it here: https://github.com/Torantulino/Auto-GPT/pull/1199

**Comment by claytondukes** [comment]
Is this file even needed once #1177 is merged?

**Comment by mikekelly** [comment]
@claytondukes that PR is likely to take a while to get merged because it's messy and it includes a whole new directory structure tailored to your specific environment. We can fix what we have here (https://github.com/Torantulino/Auto-GPT/pull/1199) and then have a separate discussion about your new ideas

**Comment by claytondukes** [comment]
> @claytondukes that PR is likely to take a while to get merged because it's messy and it includes a whole new directory structure tailored to your specific environment. We can fix what we have here (#1199) and then have a separate discussion about your new ideas

How is it "messy"? It's literally *2 files needed to run*. The other files are a readme, template files (for settings and env) and empty directories.

I've been using it and it works perfectly.
It also protects against runaway issues like the AI trying to modify the local FS or install programs, etc.

**Comment by mikekelly** [comment]
ok - I think we should discuss your PR there, rather than here 🙏

**Pull request closed without merging**
