### PR TITLE
Fix speak mode with elevenlabs falling into error

### PR DESCRIPTION
**Pull request by dannaward**
### Background

Running speak mode with elevenLabs on not only stable branch but also master fails with a config error like below.
```
  File "/Users/danna/Desktop/Personal/Auto-GPT/autogpt/speech/eleven_labs.py", line 46, in _setup
    if config.elevenlabs_voice_2_id in voice_options:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Config' object has no attribute 'elevenlabs_voice_2_id'. Did you mean: 'elevenlabs_voice_id'?
```

I just followed the guide on [docs](https://docs.agpt.co/configuration/voice/), and encountered this issue, so I think either the docs or the code should be updated.

### Changes

I saw the commit history in which the `elevenlabs_voice_2_id` was deleted on .env.template, thus instead of adding it again on config.py, I decided to remove `elevenlabs_voice_2_id`-related-codes on eleven_labs.py. (I assumed eleven_labs.py is the legacy one here)
It's now all synchronized and is not running into errors anymore.

### Test Plan

It worked fine on both my local environment and docker.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes. 
- [x] I have run the following commands against my code to ensure it passes our linters:
    ```shell
    black .
    isort .
    mypy
    autoflake --remove-all-unused-imports --recursive --ignore-init-module-imports --ignore-pass-after-docstring autogpt tests --in-place
    ```

### CODE REVIEW

**Comment by dannaward** [comment]
@ntindle It seems like the commits have disappeared and merged, resulting in no changes made in the master branch. Can you sort out this issue?

**Comment by ntindle** [comment]
I didn't merge this to the best of my knowledge

**Comment by ntindle** [comment]
It appears something force pushed to your branch, did you?

**Comment by dannaward** [comment]
No, I didn't do anything with it in the meantime. Should I create a new pull request?

**Comment by dannaward** [comment]
maybe something related to this log?
image

**Pull request merged**
