### PR TITLE
Removed baked-in twitter functionality.

### PR DESCRIPTION
**Pull request by desojo**
### Background
Twitter functionality is now included in the [plugins repository](https://github.com/Significant-Gravitas/Auto-GPT-Plugins). The inclusion of a send_tweet command confuses Auto-GPT and takes up tokens. Any future PRs related to twitter should be directed there. 

### Changes
Removed baked-in twitter functionality.

### Documentation
Self documenting 😉

### Test Plan
Ran it and it didn't break.

### PR Quality Checklist
- [ x] My pull request is atomic and focuses on a single change.
- [ x] I have thoroughly tested my changes with multiple different prompts.
- [ x] I have considered potential risks and mitigations for my changes.
- [ x] I have documented my changes clearly and comprehensively.
- [ x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by hdkiller — APPROVED** [review]

**Comment by hdkiller** [comment]
@BillSchumacher LGTM

**Comment by Pwuts** [comment]
This is a breaking change and should not be merged without advance notice to users.

**Comment by hdkiller** [comment]
What about using the existing News functionality to announce changes like this?

**Comment by desojo** [comment]
> This is a breaking change and should not be merged without advance notice to users.

It should probably be discussed in the next meeting, along with a guideline for removing any other baked in commands that are to be replaced by plugins. 

The real issue with leaving things in that can be covered by plugins is that the duplicate functionality allows more opportunities for Auto-GPT to become confused, as well as wasting tokens.

**Comment by ntindle** [comment]
Would like to also do all the plugin scaffolding and move at once. @desojo would you want to help move all the plugins?

**Comment by desojo** [comment]
I noticed the files have been removed, anything to do with this PR?

**Comment by ntindle** [comment]
Yeah hop in the plugins chat on discord

**Pull request closed without merging**
