### PR TITLE
#2645 fix: image generation with dalle

### PR DESCRIPTION
**Pull request by csymonds**
### Background

This is a bug fix for issue #2645 
There was a mismatch in parameters used in calling generate_image_with_dalle

### Changes

I modified generate_image_with_dalle to accept the third argument being passed: size (int) which the code was already looking for.

### Documentation

Documentation and code already existed for the missing parameter, it simply needed to be added back

### Test Plan

No test required

### PR Quality Checklist
- [ x] My pull request is atomic and focuses on a single change.
- [x ] I have thoroughly tested my changes with multiple different prompts.
- [x ] I have considered potential risks and mitigations for my changes.
- [x ] I have documented my changes clearly and comprehensively.
- [x ] I have not snuck in any "extra" small tweaks changes 

The code already existed for the missing parameter, it just needed to be added back.
However I did run autogpt and ask it to generate an image using the "generate_image" command at it was able to correctly generate the image using the dalle api

### CODE REVIEW

**Comment by csymonds** [comment]
Apologies, I originally indicated the wrong branch in my PR and apparently got hit with labels that do not apply. I fixed the branch, but I guess the labels do not go away...

**Comment by richbeales** [comment]
PR Raised against wrong branch

**Comment by csymonds** [comment]
> PR Raised against wrong branch

Apologies; New to this: what was  the correct branch I was supposed to target with the PR? The "Contributing" docs did not specify unless I completely missed it...

**Comment by csymonds** [comment]
Ok so I see now that this bug exists in stable but not in master. Is this a pipeline process and the fix has not made it over  to stable yet?

**Comment by csymonds** [comment]
> Ok so I see now that this bug exists in stable but not in master. Is this a pipeline process and the fix has not made it over to stable yet?

Ok I think I see the queued work on master that I presume is pending a merge into stable at some point. I will check there first next time and work from that branch.

**Comment by Pwuts** [comment]
Closing as duplicate fix

**Pull request closed without merging**
