### PR TITLE
Filepath fixes and docs updates to specify when relative paths are expected

### PR DESCRIPTION
**Pull request by lc0rp**
### Background

1. #5026 moved cli.py down one level into the app directory causing the workdir fix from  #5032 to break.
2. In cli.py, the AIConfig.load() method is called `workdir / ai_settings_file` but AIConfig.save() was called with 'ai_settings_file' which causes ai_settings.yaml to be skipped on start, and then overwritten by the AI generated goals.

### Changes

This PR fixes those two issues and updates the documentation in docs/configuration/options.md and env.template.yaml to specify when relative paths are expected.

The changes affecting the following config and settings files, which are now loaded using `workdir / <file>`
- ai_settings_file
- azure_settingS_FILE
- plugins_config_file
- prompt_settings_file

### Documentation
This PR updates the docs as well

### Test Plan
Run automated test suite.

### PR Quality Checklist
- [X] My pull request is atomic and focuses on a single change.
- [X] I have thoroughly tested my changes with multiple different prompts.
- [X] I have considered potential risks and mitigations for my changes.
- [X] I have documented my changes clearly and comprehensively.
- [X] I have not noticed any "extra" small tweaks changes. 
- [S] I have run the following commands against my code to ensure it passes our linters:
    ```shell
    black .
    isort .
    mypy
    autoflake --remove-all-unused-imports --recursive --ignore-init-module-imports --ignore-pass-after-docstring autogpt tests --in-place
    ```

### CODE REVIEW

**Comment by Pwuts** [comment]
Duplicate of #5042

**Comment by ntindle** [comment]
@Pwuts  they target different branches

**Comment by Pwuts** [comment]
@ntindle the release branch is merged back into master after releasing, so unless the fix can't wait a day, it's duplicate

**Comment by lc0rp** [comment]
Closed as duplicate

**Pull request closed without merging**
