### PR TITLE
Extract the longest content enclosed by valid curly braces to improve the JSON parser

### PR DESCRIPTION
**Pull request by apssouza22**
… json parse

### Background
This change helps to parse the openai response with multiple JSON objects or text before or after the JSON

### Changes
Instead of simply looking at single JSON objects in the string response, we extract the longest content enclosed by curly braces

### Documentation
The new function contains detailed doc comments

### Test Plan
It is already covered by unit tests. I just replaced the simpler approach

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by DdondD** [comment]
👍

**Review by nponeccop — DISMISSED** [review]

**Comment by apssouza22** [comment]
@nponeccop there was a lint issue. Could you approve it again, please?

**Comment by nponeccop** [comment]
@apssouza22 There is one again

**Comment by apssouza22** [comment]
@nponeccop 
`python -m unittest discover tests` 
`python -m flake8 autogpt/ tests/ --select E303,W293,W291,W292,E305,E231,E302`

Both jobs passed successfully now

**Pull request closed without merging**
