### PR TITLE
command clone github repository

### PR DESCRIPTION
**Pull request by edcohen08**
### Background

Enables cloning repositories via the gitpython library. This enables pulling down a repo in the docker container.

### Changes

Adds a `clone_repository` command and environment variables for github api key and username.

### Documentation

Documented in code

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [ ] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by nponeccop** [comment]
@edcohen08 There are conflicts now

**Comment by edcohen08** [comment]
rebased

**Comment by nponeccop** [comment]
@edcohen08 There are conflicts now

**Comment by edcohen08** [comment]
@nponeccop rebased

**Review by nponeccop — APPROVED** [review]

**Comment by nponeccop** [comment]
@edcohen08 CI failed

**Comment by edcohen08** [comment]
@nponeccop linted

**Review by nponeccop — APPROVED** [review]

**Review by richbeales — APPROVED** [review]

**Pull request merged**
