### PR TITLE
updated the execute_shell method

### PR DESCRIPTION
**Pull request by sudouser777**
### Background
In `execute_shell`  some condition trying to compare `Path` object with the string, this is raising an exception

### Changes
Updated the condition to convert the path object to string and comapre

### PR Quality Checklist
- [x ] My pull request is atomic and focuses on a single change.
- [x ] I have thoroughly tested my changes with multiple different prompts.
- [ x] I have considered potential risks and mitigations for my changes.
- [ x] I have documented my changes clearly and comprehensively.
- [ x] I have not snuck in any "extra" small tweaks changes 

By submitting this, I agree that my pull request should be closed if I do not fill this out or follow the guide lines

### CODE REVIEW

**Comment by sudouser777** [comment]
closes #1611

**Comment by qizwiz** [comment]
Can confirm that (so far) this works.

**Review by nponeccop — DISMISSED** [review]

**Comment by nponeccop** [comment]
@sudouser777 There are conflicts now

**Comment by sudouser777** [comment]
@nponeccop fixed the conflicts

**Review by nponeccop — APPROVED** [review]

**Review by nponeccop — APPROVED** [review]

**Comment by nponeccop** [comment]
@sudouser777 There are conflicts now

**Comment by sudouser777** [comment]
closing the pull request, change already exists in the master branch

**Pull request closed without merging**
