### PR TITLE
Large embedding fix

### PR DESCRIPTION
**Pull request by pabstaaron**
Fixes a crash that occurs when Auto tries to create an embedding for a very large text input.

On receiving a large string, create_embedding now recursively divides the text into overlapping windows and averages the output embeddings together. (Not a perfect approach and may result in some loss of context, but it preserves the relationship between the original text's words reasonably well.)

### CODE REVIEW

**Comment by k-boikov** [comment]
Duplicate of https://github.com/Significant-Gravitas/Auto-GPT/pull/3222

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by kinance** [comment]
This one can also be closed. It duplicates #3222 that fixed the issue. Thanks for your contribution! Please reopen if mistaken.

**Comment by kinance** [comment]
@Pwuts I closed this, as it's duplicate. The issue has been fixed in master. Please reopen if disagree.

**Pull request closed without merging**
