### PR TITLE
[prompt_user] Check AuthenticationError-like errors and throw them di…

### PR DESCRIPTION
**Pull request by standbyme**
### Background

Users may incorrectly set the key of the LLM service provider. In this case, we should prompt the user as early as possible to avoid invalid communication between the user and the system.

### Changes

In order to achieve this goal, I advance the error reporting of errors such as AuthenticationError to the setup stage. This means that if there is an error in the call to LLM at this stage, and it is an `AuthenticationError` type error, AutoGPT will report this error to the user, saving the user's time.

Before this PR, AutoGPT will try to allow users to manually set AI Config, and will report errors in subsequent interactions, resulting in invalid communication.

### Documentation

The changes are easy to understand and are self-documenting.

### Test Plan

- Set the OpenAI key normally, and the AutoGPT can run normally.
- Set the OpenAI key to a random value, and AutoGPT will throw an exception directly during the setup phase and will not continue to run.
### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by anonhostpi** [comment]
2 things:

- I agree. Working with other GPT tech, this is a common end-user problem that devs for some reason always forget to remediate.
- This needs to not just cover OpenAI's token, but the rest of the supported APIs

**Comment by anonhostpi** [comment]
With that second point being said, this probably won't be fixed until after the re-arch

**Comment by standbyme** [comment]
I agree with you. I will follow up the progress of re-arch and improve this PR.

**Comment by anonhostpi** [comment]
Here's the current issues tagged with the re-arch https://github.com/Significant-Gravitas/Auto-GPT/labels/re-arch

**Comment by standbyme** [comment]
@anonhostpi Could we first merge this PR for a fast fix? I will follow up the progress of `re-arch` to improve it.

**Comment by lc0rp** [comment]
Incorporated into #4279 - Let's add @standbyme as a collaborator there. @standbyme Allow us to close this and collaborate on #4279?

**Comment by standbyme** [comment]
@lc0rp Sure, I would like to join in!

**Pull request closed without merging**
