### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by bigsk1**
adding security policy as repo didn't have one. Update as needed.

### PR Quality Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [ ] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [ ] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by ntindle — APPROVED** [review]

**Review by hdkiller — APPROVED** [review]

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Boostrix** [comment]
looks like a definite non-code PR that coud be reviewed and accepted despite the ongoing re-arch, probably should be reworded to explicitly read "draft version" for now, and then take it from there by incrementally reviewing it and adding/changing the policy document as needed. Having a stub is definitely better than having no security policy at all. We should probably go throgh some issues and PRs to see how the policy should be adapted

**Comment by lc0rp** [comment]
Any reason not to merge this? @Significant-Gravitas/maintainers

**Comment by Pwuts** [comment]
I'll process this today

**Comment by bigsk1** [comment]
going to close this as nothing was not merged

**Comment by Pwuts** [comment]
To be continued... :)

**Pull request closed without merging**
