### PR TITLE
Pause  continuous loops and give feedback

### PR DESCRIPTION
**Pull request by adrianegraphene**
### Background
**This is a resubmit of PR #2069, which got a little messy. This is a cleaner version of that. Tested & working.**

Added the ability to pause a continuous loop. When we input "y -X", where X is some number, there is a desire to be able to pause the AI and input some human feedback, then have the AI continue on its trajectory, as noted here  #563 

### Changes
Uses can pause a long loop with just 3 key presses. Hold "SHIFT" and press "P" twice. Then users can enter feedback + have the loop automatically continue.

"Shift + P + P"

**User friendly UX**
On the 2nd iteration of a loop, the message _"Thinking...."_ changes to _"Thinking... Hold Shift & press 'P' twice to give feedback to the AI"_

### Documentation
The person must click into the same code window where the code originally ran, then hold "Shift" + hit "p" twice
"SHIFT + P + P" will bring pause the loop on the next run, so that someone can entire feedback to the AI.
This way, instead of having to stop a long loop, you can just pause it, give feedback, and have the loop continue.

The clicks will not be detected if the active windows is something besides the running code window.

### Test Plan
Tested several iterations on Windows, to ensure that expected behavior is experienced (it is).

Request that someone tests this on Linux.

### PR Quality Checklist
- [✔️] My pull request is atomic and focuses on a single change.
- [✔️ ] I have thoroughly tested my changes with multiple different prompts.
- [ ✔️] I have considered potential risks and mitigations for my changes.
- [ ✔️] I have documented my changes clearly and comprehensively.
- [ ✔️] I have not snuck in any "extra" small tweaks changes 

Edit: Updated with documentation on README

### CODE REVIEW

**Comment by hdkiller** [comment]
CI is failing. You have linter errors.

**Comment by adrianegraphene** [comment]
Thanks @hdkiller I just fixed the linter issues. I'll keep my eyes on this to see if there's more I need to do, please let me know if so, thank you.

**Comment by sneibarg** [comment]
I wanted this feature earlier today when autogpt got stuck dealing with things like an interactive prompt or a bash shell on another host with no other way to run commands once logged in and trying to edit a file with a text editor. It needs to be told it's blind and cannot see nano.

**Comment by adrianegraphene** [comment]
@sneibarg - it does feel great being able to pause autogpt and re-align it! Especially on those longer runs.
Hopefully we can get this submitted soon. If you're open to testing it, I'd love to get feedback on this. I think you'll enjoy it.

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Boostrix** [comment]
this should probably be tackled from not just the perspective of a human being the top-level "agent", but also so that it would work for agent/sub-agent chains, where the agent would need "guide/direct" the sub-agent as needed ?

**Comment by Wladastic** [comment]
Please remove changes that have nothing to do with this topic, I saw a couple like the readme change with docker-compose

**Comment by adrianegraphene** [comment]
> Please remove changes that have nothing to do with this topic, I saw a couple like the readme change with docker-compose

Gladly. Can you confirm if this PR would be merged if that's updated? I spent some time keeping this updated, but stopped due to unclear merging requirements.

**Comment by Boostrix** [comment]
Hi, just a short update - thanks for taking the time to update your PR, your PR was today discussed on Discord by several devs and it's being assigned to be reviewed right now!

So, given that there seem to be at least 5+ different PRs in the pipeline currently using similar but still a different method, it is likely that we're going to take parts from each and every one of these PRs, to ensure that the feature is well-aligned with the ongoing re-arch effort.

This means, you will end up in the credits automagically - but won't have to do any more work from now on.

If there are remaining questions, someone is going to contact you, the PR is being reviewed by @gravelBridge

**Comment by adrianegraphene** [comment]
>Hi, just a short update - thanks for taking the time to update your PR...
 If there are remaining questions, someone is going to contact you, the PR is being reviewed by @gravelBridge

Thanks for the update. Just to clarify, my understanding = "don't do any further work right now, unless @gravelBridge asks". I will refrain from making any changes as @Wladastic requested. Happy to make changes as needed, just let me know. 

> This means, you will end up in the credits automagically - but won't have to do any more work from now on.

Thanks! That's exciting 👯 Happy to contribute. Again, just let me know if anything needs cleaning.

**Comment by gravelBridge** [comment]
Hello! Thank you so much for your contribution and feature suggestion! I have finished implementing our version of this feature here: https://github.com/Significant-Gravitas/Auto-GPT/pull/4230. Once again, thank you!

**Comment by gravelBridge** [comment]
Reopening to allow credit to adrianegraphene since I prematurely closed it. After credit has been registered, I will re-close this PR.

**Comment by gravelBridge** [comment]
Hello! Thank you so much for your contribution and feature suggestion! I have finished implementing our version of this feature here: https://github.com/Significant-Gravitas/Auto-GPT/pull/4230. Once again, thank you!

**Pull request closed without merging**
