### PR TITLE
Make working directory part of global config with env var

### PR DESCRIPTION
**Pull request by mikekelly**
### Background
The working directory was hardcoded in a few separate bits of the codebase

### Changes
Made working directory part of global config and possible to set via env variable

### Documentation
added to `.env.template`

### Test Plan
Smoke tested locally after refactor and works ok

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by joshmarsden1994 — APPROVED** [review]
Great addition

**Review by Onigam — APPROVED** [review]
+1 ❤️

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by subwindow** [comment]
This is already available in `Workspace.root`, and is set in `main.py`. I think if we add this as a configuration item it would be best to update main.py to use the config variable and to have everything else use `Workspace.root`.

I think that this would need to change: https://github.com/Significant-Gravitas/Auto-GPT/blob/master/autogpt/main.py#L110-L117

**Review by lc0rp — CHANGES_REQUESTED** [review]
This could be a useful feature. Do you think you could resolve conflicts and adapt it to work with the new config module?

Also, consider the command line "-w", "--workspace-directory" option in cli.py. If set, it should override the env variable.

Lastly, please write some tests.

**Pull request closed without merging**
