### PR TITLE
ElevenLabs Voice ID's

### PR DESCRIPTION
**Pull request by Bentlybro**
For all the people who are using ElevenLabs for your TTS I have gone through and gotten all the premade voice ID's so its a bit easier to add them 

here is an example of the "Rachel" voice ID
ELEVENLABS_VOICE_1_ID=21m00Tcm4TlvDq8ikWAM

Rachel : 21m00Tcm4TlvDq8ikWAM
Domi : AZnzlk1XvdvUeBnXmlld
Bella : EXAVITQu4vr4xnSDxMaL
Antoni : ErXwobaYiN019PkySvjV
Elli : MF3mGyEYCl7XYWbV9V6O 
Josh : TxGEqnHWrfWFTfGW9XjX
Arnold : VR6AewLTigWG4xSOukaG
Adam : pNInz6obpgDQGcFmaJgB
Sam : yoZ06aMxZJJ28mfd3POQ

### CODE REVIEW

**Comment by BillSchumacher** [comment]
Looks like you're trying to commit some stuff you probably didn't want to.

**Comment by BillSchumacher** [comment]
Do you want me to put these in the correct spot?

**Comment by BillSchumacher** [comment]
Ah actually, if I don't that I would nuke the files in your repo since you committed from master.

**Comment by Bentlybro** [comment]
@BillSchumacher yeah if you wouldn't mind, sorry I'm still some what getting using GitHub so my bad for the mistakes

**Comment by BillSchumacher** [comment]
> @BillSchumacher yeah if you wouldn't mind, sorry I'm still some what getting using GitHub so my bad for the mistakes

No problem =)

**Review by BillSchumacher — APPROVED** [review]

**Pull request merged**
