### PR TITLE
Update setup.md

### PR DESCRIPTION
**Pull request by tomfurrier**
### Background
Following https://docs.agpt.co/setup/ will result in an empty mounted auto_gpt_workspace folder. The files are written to a non-mounted directory inside the container. This small change should fix it, making it straightforward to get started with Auto-GPT with Docker.

### Changes
update the doc for setup with Docker

### Test Plan
running locally on a Windows 11 machine with 
`docker compose run auto-gpt`

### PR Quality Checklist
- [x ] My pull request is atomic and focuses on a single change.
- [ x] I have thoroughly tested my changes with multiple different prompts.
- [ x] I have considered potential risks and mitigations for my changes.
- [ x] I have documented my changes clearly and comprehensively.
- [ x] I have not snuck in any "extra" small tweaks changes. 
- [ x] I have run the following commands against my code to ensure it passes our linters:
    ```shell
    black .
    isort .
    mypy
    autoflake --remove-all-unused-imports --recursive --ignore-init-module-imports --ignore-pass-after-docstring autogpt tests --in-place
    ```

Only changed doc

### CODE REVIEW

**Comment by collijk** [comment]
@NeonN3mesis is this something you can validate and sign off on?  I'm less familiar with the docker workflow, but this would be good to get in if it fixes a bug.

**Comment by NeonN3mesis** [comment]
I can check it out when I get home in about an hour

**Comment by NeonN3mesis** [comment]
@collijk I talked with @Pwuts about the workspace directory in that docker compose example and he said the workspace itself is currently in the wrong place and the doc reflects where it should be. I don't know what the plan is from there.

**Comment by Pwuts** [comment]
I'm working on a PR to fix path processing, which should stop these folders from wandering around.

**Comment by Pwuts** [comment]
#5032

**Comment by Pwuts** [comment]
Fixed in #5032 :)

**Pull request closed without merging**
