### PR TITLE
Cleanup azure parameters in env.template and remove unused env in config.py

### PR DESCRIPTION
**Pull request by suensummit**
### Background

There are some unused azure environment variables left in the `env.template` as they are already moved to `azure.yaml.template`.

### Changes

- Cleanup Azure related env from `env.template`.
- Remove unused azure parameters from `config.py`, also fix the yaml loader syntax with some preset values.

### Documentation

There are notes in `env.template` and the codes in `config.py` is clear enough.

### Test Plan

Tested with azure configurations.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by suensummit** [comment]
@richbeales please take a look thanks.

**Comment by suensummit** [comment]
conflicts resolved, please review while available, thanks @nponeccop @sweetlilmre @richbeales @Torantulino

**Comment by nponeccop** [comment]
@suensummit There are conflicts again

**Comment by suensummit** [comment]
> @suensummit There are conflicts again

Resolved

**Review by nponeccop — APPROVED** [review]

**Review by richbeales — APPROVED** [review]

**Pull request merged**
