### PR TITLE
Add OSSRank badge to README

### PR DESCRIPTION
**Pull request by ryw**
### Background

Amazing to see the explosion of Auto-GPT. I analyze open source projects via OSSRank, just added the project to our index. We have a badge that tracks the project's rank within our platform. Hope you accept the PR :)

### Changes
Add OSSRank badge to README

### Documentation
None required

### Test Plan
None required

### PR Quality Checklist
- [X] My pull request is atomic and focuses on a single change.
- [X] I have thoroughly tested my changes with multiple different prompts.
- [X] I have considered potential risks and mitigations for my changes.
- [X] I have documented my changes clearly and comprehensively.
- [X] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by richbeales — APPROVED** [review]

**Comment by richbeales** [comment]
Not sure I like that this infers a link by username to LinkedIn and scrapes that

**Comment by ryw** [comment]
There is no scraping, I do all research on people manually.

**Comment by nponeccop** [comment]
@ryw There are conflicts now

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Review by Pwuts — APPROVED** [review]

**Pull request closed without merging**
