### PR TITLE
Feature: Added Self Feedback

### PR DESCRIPTION
**Pull request by AbTrax**
### Background
The rationale behind adding the self-feedback feature in the Agent class is to enhance the AI's ability to verify and validate its own thoughts, reasoning, plans, and criticism. This will help improve the AI's decision-making process and allow it to autonomously generate better responses over time. The self-feedback feature is aligned with the project's overall direction of creating an efficient and intelligent AI agent.

### Changes
The specific changes made in this pull request involve adding a new method called get_self_feedback() to the Agent class. This method takes in a dictionary of thoughts containing keys such as 'reasoning', 'plan', 'thoughts', and 'criticism'. It combines these elements into a single feedback message and uses the create_chat_completion() function to generate a response based on the input message. This allows the AI to verify and validate its own thoughts before executing a command.

### Documentation
The changes are documented through in-code comments and this explanation. The get_self_feedback() method has a docstring that explains its purpose, input, and output. Additionally, the rationale and changes sections above provide further context and explanation.

### Test Plan
Testing the self-feedback functionality can be challenging due to the open-ended nature of the responses. 

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single charge.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes 

 Due to the open-ended nature of the Self-feedback getting continuous exact answers and negative answers is quite hard whilst getting good open answers is not always the same and can vary differ.

### CODE REVIEW

**Comment by AbTrax** [comment]
@merwanehamadi Here is the Adverse/Feedback

**Comment by AbTrax** [comment]
If it's merged I can add it to the usage.md

**Comment by ntindle** [comment]
> If it's merged I can add it to the usage.md

Can you add it in the PR so the docs get updated instantly?

**Comment by AbTrax** [comment]
Your right I'll do it now

**Comment by AbTrax** [comment]
> > If it's merged I can add it to the usage.md
> 
> Can you add it in the PR so the docs get updated instantly?

You are right I'll do it now

**Review by richbeales — APPROVED** [review]

**Comment by richbeales** [comment]
Tested locally, LGTM

**Pull request merged**
