### PR TITLE
Update spinner.py

### PR DESCRIPTION
**Pull request by DevangRadadiya**
https://github.com/Torantulino/Auto-GPT/issues/656#issue-1660550311

Fix from updated line 20 from \r to \n

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thouroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by Torantulino** [comment]
This doesn't seem right, wouldn't this make the spinner keep moving down the console instead of overwriting and printing on top of itself?

Have you tested this change?

**Comment by DevangRadadiya** [comment]
It will goes down and take a history of the old command.

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Pwuts** [comment]
Spinner works fine currently :)

**Pull request closed without merging**
