### PR TITLE
Driver customization options

### PR DESCRIPTION
**Pull request by thehunmonkgroup**
### Background
Basically, the way the selenium drivers are set up doesn't allow flexibility for older installs (I'm on Debian 10 headless), or customizing the driver options to work around issues (like my requirement for the `--no-sandbox` option).

### Changes
This adds two new configuration variables:
* `DRIVER_EXECUTABLE_PATH`: Allows specifying a custom driver binary.
* `DRIVER_EXTRA_OPTIONS`: Allows passing other needed options to the driver.

### Documentation
They are clearly documented with comments in `.env.template`

### Test Plan
The changes are quite simple, I didn't do any testing beyond making sure the features work as intended, and that no errors happen when the new configuration options are not used.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by nponeccop** [comment]
@thehunmonkgroup There are conflicts now

**Review by nponeccop — APPROVED** [review]

**Comment by BTCompKSU** [comment]
Hello - First comment on GitHub! I've installed Python 3.10 on Linux / Ubuntu with the latest stable release of Auto-GPT.  It is working good except for the browse_website command, which is currently throwing the following error: 

```
System: Command browse_website returned: Error: Message: unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x7fbd90bfbfe3 <unknown>
#1 0x7fbd9093ad36 <unknown>
#2 0x7fbd90963b20 <unknown>
#3 0x7fbd9095fa9b <unknown>
#4 0x7fbd909a1af7 <unknown>
#5 0x7fbd909a111f <unknown>
#6 0x7fbd90998693 <unknown>
#7 0x7fbd9096b03a <unknown>
#8 0x7fbd9096c17e <unknown>
#9 0x7fbd90bbddbd <unknown>
#10 0x7fbd90bc1c6c <unknown>
#11 0x7fbd90bcb4b0 <unknown>
#12 0x7fbd90bc2d63 <unknown>
#13 0x7fbd90b95c35 <unknown>
#14 0x7fbd90be6138 <unknown>
#15 0x7fbd90be62c7 <unknown>
#16 0x7fbd90bf4093 <unknown>
#17 0x7fbd904b5609 <unknown>

```
It sounds like this branch might resolve the issue, but I figured I'd add my two cents just in case it's helpful!

**Comment by thehunmonkgroup** [comment]
Can we get this in? It's a simple patch that I've had to fix conflicts on several times, would really like to close this sucker out.

**Comment by thehunmonkgroup** [comment]
Done. I really hope you guys get this in now, this is the fourth time I've fixed merge conflicts, probably not gonna do any more of that.

**Review by superherointj — DISMISSED** [review]

**Comment by thehunmonkgroup** [comment]
At this point, I have to be approaching the most times anyone has resolved a conflict on a PR for this project, right??

**Review by superherointj — APPROVED** [review]

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Boostrix** [comment]
> At this point, I have to be approaching the most times anyone has resolved a conflict on a PR for this project, right??

Note this looks like a useful change to be reviewed/integrated despite the ongoing re-arch effort, it's primarily config-level, with very few code changes (and those primarily are about adding selenium options for people on older systems). So definitely do consider for review/integration to help close some PRs. Thanks

**Comment by anonhostpi** [comment]
I don't agree with merging right now.

https://github.com/Significant-Gravitas/Auto-GPT/pull/1988#issuecomment-1537340291

**Comment by thehunmonkgroup** [comment]
Is it worth it to keep updating this PR? Could it still be under consideration? Are y'all done with the big refactor?

**Pull request closed without merging**
