### PR TITLE
Make prompt parameters configurable

### LINKED ISSUE #3954: Prompt Profiles
### Duplicates

- [X] I have searched the existing issues

### Summary 💡
Based on previous comments: https://github.com/Significant-Gravitas/Auto-GPT/issues/3858#issuecomment-1537439701

- We have roughly 10+ open PRs that are all about augmenting/replacing hard-coded prompts. 
- Many of these cannot be committed due to the lack of testing/benchmarks
- However, this causes a ton of potentially useful contributions to end up in the backlog

Thus, the idea is to add support for so called "Prompt Profiles". A profile would be the equivalent of a sub-directory that contains a single profiles.json file to list sub-directories with other prompt configs.

Given that prompt-related PRs are such a common thing but due to the lack of testing data also are so controversial, how about coming up with support for "prompt profiles", as in a shared folder with sub-folders that contain profiles for different prompts, so that people can tinker with different profiles without stepping on anyone's toes ?

This will enable people to experiment with different "prompt profiles", without affecting the stability/usefulness of the whole project. Also, this would present an option to benchmark (#1359) different prompft profiles against each other (#1354). So, if/when a prompt is promoted to become the official/main one, we can simply change a "default_profile" property.

Having this sort of infrastructure in place would also provide a good baseline for regression testing and benchmarking.
It would not directly be the solution proposed in https://github.com/Significant-Gravitas/Auto-GPT/issues/3858, but probably would be the only solution to have our cake and eat it, while also growing test data ?

Ideally we'd support a dedicated sub-folder for "prompt profiles" with the corresponding json to map directories to each profile - that way, we can have our cake and eat it, and still close 10+ PRs in the process, because these would then all become custom prompt profiles - without any chance to step on anyone's toe. Besides, this would also mean having 10+ different ways to benchmark/test the system in conjunction with different prompts EASILY

Background:
- #3858
- #3937 
- 

### Examples 🌈

_No response_

### Motivation 🔦

_No response_

### PR DESCRIPTION
**Pull request by DGdev91**
Loading prompt constraints, resources and performance evaluation from a yaml file (default prompt_settings.yaml) 
Can be set from .env (PROMPT_SETTINGS_FILE) or by commandline (--prompt-settings or -P)

potentially resolves #3954

### Background
The main reason for proposed this changes is because they can help with with different LLM models, we talked about that in #25 #567 #2158.
They don't handle the prompts in the same way as GPT3.5/GPT4, and they often get confused. this way can be easy to create and share prompts made specifically for them.

Also, it can be useful for models made for different languages, like for example https://github.com/FreedomIntelligence/LLMZoo

....Or just for people who want to have more control on what AutoGPT can do without having to modify the code

### Changes
Moved the hardcoded default prompt constraints, resources and performance evaluation form prompt.py to the new file prompt_settings.yaml, wich will be used as default file.

Added the new configuration variable PROMPT_SETTINGS_FILE in .env.template and modified config.py to handle it

Added the new file autogpt/config/prompt_config.py, wich contain the PromptConfig class, wich is initialized passing the file path and contains the datas from the configuration file

Moved the hardcoded default prompt constraints, resources and performance evaluation form prompt.py to the new file prompt_settings.yaml, wich will be used as default file.

Modified prompt.py to use the values from the PromptConfig instead of hardcoded datas

Modified cli.py, main.py and configurator.py to handle the new --prompt-settings / -P commandline args

### Documentation
The new .env variable PROMPT_SETTINGS_FILE is described there, while the new --prompt-settings/-P comd line args are described both in cli.py and in usage.md.
I followed the same policy used for the ai.settings.yaml file

### Test Plan
- Start AutoGPT without modifying any configurations, should work just as before
- Start AutoGPT using --prompt-settings (file) (ex. python -m autogpt -P prompt_settings_ex.yaml), where file doesn't exists or isn't valid. AutoGPT should give a validation error and stop
- Start AutoGPT using after setting PROMPT_SETTINGS_FILE=(file), where file doesn't exists or isn't valid. AutoGPT should give a validation error and stop
- Copy the prompt_settings.yaml file and change it a bit, while keeping it still valid. Run AutoGPT normally, it should still run as expected

To check if the prompt have actually changed, i also used those changes in my fork (see #2594) while connecting to https://github.com/keldenl/gpt-llama.cpp
I know it isn't something officially supported, but it's still a good and quick way to see what's going on, since the webservice prints the prompt on the standard output

### PR Quality Checklist
- * [x] My pull request is atomic and focuses on a single change.
- * [x] I have thoroughly tested my changes with multiple different prompts.
- * [x] I have considered potential risks and mitigations for my changes.
- * [x] I have documented my changes clearly and comprehensively.
- * [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Boostrix** [comment]
Please see #3954

**Comment by DGdev91** [comment]
@Boostrix i really like the idea. And my PR pretty much already covers it

**Comment by Boostrix** [comment]
Would this also handle the current issue where the GPT4 default fails for people who only have access to GPT3.5 (e.g. #4229) ?
Or more generally: how does this deal with multiple LLMs as part of a single profile ?

**Comment by DGdev91** [comment]
> Would this also handle the current issue where the GPT4 default fails for people who only have access to GPT3.5 (e.g. #4229) ? Or more generally: how does this deal with multiple LLMs as part of a single profile ?

I've not really clear what are you referring to, but it doesn't seem related

**Comment by Boostrix** [comment]
sry, you're right, I was meaning to respond in the issue where someone is working on abstracting out the OpenAI API

**Comment by lc0rp** [comment]
@DGdev91 if you edit the description and reference [3954](https://github.com/Significant-Gravitas/Auto-GPT/issues/3954) it'll link them and transition the issue.

Adding "potentially resolves #3954" should do it.

**Comment by DGdev91** [comment]
> @DGdev91 if you edit the description and reference [3954](https://github.com/Significant-Gravitas/Auto-GPT/issues/3954) it'll link them and transition the issue.
> 
> Adding "potentially resolves #3954" should do it.

K, done

**Comment by Wladastic** [comment]
Please update the branch.
Otherwise looks very good! :)

**Review by Wladastic — APPROVED** [review]

**Review by Pwuts — APPROVED** [review]

**Comment by merwanehamadi** [comment]
@DGdev91 https://discord.gg/autogpt

**Comment by katmai** [comment]
good change

**Comment by katmai** [comment]
this doesn't seem to cover the hardcoded prompts in `autogpt/config/ai_config.py`

**Comment by DGdev91** [comment]
> NICE thanks @DGdev91 BIG BIG BIG are you on discord ? Join us if not.

Yes, i'm already there. DGdev91#8061

> this doesn't seem to cover the hardcoded prompts in `autogpt/config/ai_config.py`

True. And there's also still some hardcoded stuff in generator.py.
Also, i don't really like the autogpt/prompts/default_prompts.py, it can be included too

But i wanted to keep this PR simple, and eventually add other stuff to the new yaml config file later

**Comment by katmai** [comment]
> > NICE thanks @DGdev91 BIG BIG BIG are you on discord ? Join us if not.
> 
> Yes, i'm already there. DGdev91#8061
> 
> > this doesn't seem to cover the hardcoded prompts in `autogpt/config/ai_config.py`
> 
> True. And there's also still some hardcoded stuff in generator.py. Also, i don't really like the autogpt/prompts/default_prompts.py, it can be included too
> 
> But i wanted to keep this PR simple, and eventually add other stuff to the new yaml config file later

i have found another prompt that is hardcoded

`autogpt/memory_management/summary_memory.py`

**Pull request merged**
