### PR TITLE
Include pyobjc in requirements.txt

### PR DESCRIPTION
**Pull request by dayofthedave**
### Background
When I'm setting up Auto-GPT (on MacOS using PyCharm), I get this error:

> ModuleNotFoundError: No module named 'AppKit'

This issue is resolved by installing pyobjc.

### Changes
Add pyobjc to requirements.txt.

### Documentation
Simple change, no documentation necessary.

### Test Plan
Built project before installing pyobjc: failed. Built project after installing pyobjc: success.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Review by lc0rp — COMMENTED** [review]
pyobjc only supports macOS. Does it ignore or fail gracefully if installed on another platform?

Since this is platform-specific; I suggest adding sys_platform == 'darwin' to make it conditional

```text
pyobjc; sys_platform == 'darwin'
```

**Comment by Boostrix** [comment]
any updates on this by people on Mac OS ?

**Comment by merwanehamadi** [comment]
I have asked on our discord if anyone had this issue in the past, I can't reproduce it and I use mac.
This is the discord thread where I asked
https://discord.com/channels/1092243196446249134/1092243197117337675/1108046954111443005

join discord: https://discord.gg/autogpt

**Comment by merwanehamadi** [comment]
@dayofthedave we're having trouble finding people that had the issue on their mac.
Let's do something: we close it and we will reopen once we find someone that has the issue, ok ?

**Comment by dayofthedave** [comment]
Sure!

**Pull request closed without merging**
