### PR TITLE
add edge to browser options for selenium

### PR DESCRIPTION
**Pull request by Amraki**
### Background

I received errors related to selenium not locating the default chrome binary. 
Instead of installing it and possibly troubleshooting file paths, I wanted to use my current browser.

### Changes

Added 'edge' as a browser option for selenium.

### Documentation

Updated .env.template to reflect the additional option. Kept changes consistent with existing code.

### Test Plan

Auto-GPT has opened a new MS Edge browser instance, navigated to the provided URL, scraped the content, and closed the browser instance. This has successfully occurred in multiple runs without related errors.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by cryptidv** [comment]
While you're at it can you also add opera? Just to complete everything lol

**Comment by Amraki** [comment]
I can look it up, but I can't test it myself. 

Also, I just noticed a few changes that aren't mine. Mostly likely from the last pull I did. Still new to PR's and first time doing it from VS Code. I'll try to fix.

**Review by nponeccop — DISMISSED** [review]

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by anonhostpi** [comment]
> While you're at it can you also add opera? Just to complete everything lol

Not recommended. Create a separate PR. See:

image

**Comment by Boostrix** [comment]
Note this looks like a useful change to be reviewed/integrated despite the ongoing re-arch effort, it's primarily config-level, with very few code changes. So definitely do consider for review/integration to help close some PRs. Thanks

**Comment by anonhostpi** [comment]
While, I do agree that this probably has no affects on the rearch, as chrome is available at the moment, I think this is low priority until after the rearch.

This could also open a whole new can of worms with webdriver. This repo keeps running into problems with getting chromedriver to cooperate. Adding msedgedriver to the mix probably isn't a good idea _right now._

Though I do think we still inevitably need this. I feel like a good time to propose this would be after the rearch and after ironing out the issues with chromedriver.

**Comment by k-boikov** [comment]
Closing in favor of https://github.com/Significant-Gravitas/Auto-GPT/pull/3058

**Pull request closed without merging**
