### PR TITLE
Add Edge browser support using EdgeChromiumDriverManager

### PR DESCRIPTION
**Pull request by karimhabush**
### Background
This pull request aims to add support for the Edge browser in the web_selenium.py commands. The change will allow users to leverage the Edge browser while using Selenium for web automation tasks, in addition to the existing supported browsers.

### Changes
- Imported EdgeChromiumDriverManager from the webdriver_manager.microsoft package.
- Added EdgeOptions to the available browser options.
- Updated the driver initialization logic to use the Edge driver when the configured browser is set to "edge".

### Documentation
The changes made in this pull request are documented within the `.env.template` file. 

### Test Plan
1. Set the `USE_WEB_BROWSER` variable to `edge` within the file `.env.template`.
2. Rename the file `.env.template` to `.env`
3. Run the script and provide a prompt that requires the command `browse_website` to ensure that the Edge browser is launched and web scraping tasks are performed without any issues.
4. Test the same script with other browsers (Chrome, Safari, and Firefox) to ensure that the existing functionality remains intact.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by ntindle — DISMISSED** [review]

**Comment by ntindle** [comment]
Can you run the linter (black) and issort to fix the linter errors

**Comment by karimhabush** [comment]
> Can you run the linter (black) and issort to fix the linter errors

Sure thing!

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Boostrix** [comment]
Note this looks like a useful change to be reviewed/integrated despite the ongoing re-arch effort, it's primarily config-level, with very few code changes (and those primarily are about supporting a new option). So definitely do consider for review/integration to help close some PRs. Thanks

**Comment by anonhostpi** [comment]
IMO, I don't recommend rn.

https://github.com/Significant-Gravitas/Auto-GPT/pull/1988#issuecomment-1537340291

**Comment by anonhostpi** [comment]
Related: https://gist.github.com/anonhostpi/97d4bb3e9535c92b8173fae704b76264#web-automation-capability

**Review by k-boikov — APPROVED** [review]

**Pull request merged**
