### PR TITLE
Switch from argparse to click for argument parsing

### PR DESCRIPTION
**Pull request by 0xArty**
### Background
This PR changes the argument parsing library from `argparse` to `click`. The primary reason for this switch is to leverage the benefits provided by `click`, while maintaining backward compatibility with the existing implementation. `Click` is a powerful and flexible library for creating command-line interfaces, offering several advantages over `argparse`, such as a more intuitive and consistent API, better error messages, automatic generation of help messages, and advanced features like command chaining and nested commands.

### Changes
- Replace **argparse** with **click** for argument parsing.
- Update the **main** function to use **click** decorators and options.
- Renamed the **parse_arguments** to **create_config**
- Ensure that existing functionality is preserved with minimal changes to the codebase.
- Keep the door open for future enhancements using **click's** built-in features.

### Benefits of Click
- More intuitive and consistent API.
- Better error messages and automatic generation of help messages.
- Advanced features like command chaining and nested commands.
- Actively maintained and widely used library, with extensive documentation and community support.

### Documentation
The code changes include in-code comments to describe the new **click** decorators and options. The external documentation will be updated to reflect the change from **argparse** to **click**.

### Test Plan
1. Manually test the script with various command-line options to ensure that the existing functionality is preserved.
2. Run existing test cases to ensure that the change does not introduce any regressions.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by nponeccop — APPROVED** [review]

**Comment by BillSchumacher** [comment]
<3 click

**Review by nponeccop — DISMISSED** [review]

**Comment by nponeccop** [comment]
@0xArty There are conflicts now

**Comment by 0xArty** [comment]
@nponeccop 

Merge conflicts fixed 👍

**Review by nponeccop — APPROVED** [review]

**Comment by richbeales** [comment]
please build in the changes that have just been merged by #1096

**Comment by 0xArty** [comment]
@richbeales done

**Comment by nponeccop** [comment]
@0xArty There are conflicts now

**Comment by 0xArty** [comment]
Closed too many merge conflicts.

Will coordinate this change with the team

**Pull request closed without merging**
