### PR TITLE
feature: optional requirements

### PR DESCRIPTION
**Pull request by Tymec**
### Background

Adds a feature to install optional dependencies based on the config options. For example, the memory backend config option can have different values that correspond to different optional packages, such as `redis`, `pinecone-client`, `weaviate-client` or `pymilvus`. Instead of installing all these packages, which may not be compatible with some operating systems or environments and wouldn't be used, this feature allows the user to install only the package that matches their config value. This can save time and space, and avoid installation errors. The feature uses a script that parses a file called `requirements-optional.txt`, which specifies the optional packages and their config options, and then uses subprocess to run pip install commands for the required packages.

### Changes

- Added a script to parse the `requirements-optional.txt` file and install dependencies based on used config options
- Added a file `requirements-optional.txt` to specify the optional packages and their corresponding config options
- Added an empty file `scripts/init.py`

### Documentation

- In-code comments that explain the logic and functionality of the code.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Boostrix** [comment]
Note that the same issue seems to have been solved recently as part of supporting plugins, so these two efforts may benefit from each other - especially since more and more optional functionality is likely to end up in plugins, and since you are talking about "optional requirements", there's probably a real use-case for the API at the plugin layer, so that plugins may also support different options.

**Comment by ntindle** [comment]
@Tymec can you consolidate this in as @Boostrix described

**Comment by Pwuts** [comment]
Since there has been no activity on this PR by OP for the past 2.5+ months, I'm closing it as stale. Feel free to bump, reply or ping me on Discord if you want to discuss further or pick it back up. :)

**Pull request closed without merging**
