### PR TITLE
First draft at adding persistent memory via sqlite3

### PR DESCRIPTION
**Pull request by EricFedrowisch**
Implemented persistent memory with a sqlite3 database instead of list of strings. 
Benefits include:
-session memories can now be persistent
-contents searchable between multiple sessions
-multiple agents could in theory interoperate/cooperate with one centralized memory repository since each would get a new session id

### CODE REVIEW

**Review by DamascusGit — COMMENTED** [review]
LGTM

**Review by DamascusGit — APPROVED** [review]
LGTM

**Comment by ryanpeach** [comment]
Is SQLLite really the best database for long term text storage? I'd think elastisearch...

Also we are getting close to needing a docker compose file.

**Comment by ryanpeach** [comment]
Also see https://github.com/Torantulino/Auto-GPT/pull/122

**Comment by merwanehamadi** [comment]
@ryanpeach elasticsearch is very heavy. they don't have a long term free version on the cloud like pinecone does, so putting the api key of the cloud offering wouldn't be very useful for most people.
Putting it as a docker file I am not sure...
But a big benefit of elasticsearch is that it does good keyword search and it allows people to not have to embed their texts.

But I would put opensearch though, Elasticsearch is under an ambiguous license, so people forking autogpt and using it for comercial use with the elasticsearch integration might run into issues.

**Comment by EricFedrowisch** [comment]
Sqlite3 is part of python standard library. That's why I chose it as a sensible default.

**Comment by Eunyxjk** [comment]
Thank you, big shot

**Comment by Eunyxjk** [comment]
!!

**Comment by EricFedrowisch** [comment]
To be clear, I'm pro-vector inputs. However, vectored inputs can be added in addition to this. This is more like a "persistent log".

**Comment by EricFedrowisch** [comment]
@ryanpeach  Wow! Then you should totally write some code, Ryan. Like just do it. No one is stopping you.

**Comment by ryanpeach** [comment]
@EricFedrowisch Dude i have several PR's. I'm contributing to the discussion on this one. That kind of unprofessional comment is very toxic.

**Comment by EricFedrowisch** [comment]
@Joe0  Framing the data as snapshots seems very useful. The persistent memory imp I roughed out uses "sessions", with basically each run of the program creating a new session. There is a command to get_session(id), so you can retrieve whatever session you want in plain text. If you can decouple the snapshot from data stores, that would be huge.

**Comment by EricFedrowisch** [comment]
@Joe0  I think you are onto something. Still reading and trying to understand your pr. 

Out of curiousity, what was your motivation for focusing on state transitions?

**Comment by EricFedrowisch** [comment]
@ryanpeach  Several people have confirmed that I was being toxic. Please accept my apology. Your desire to fully explore the questions this project raises are reasonable. Again, I'm sorry. I'll try and do better in the future.

**Comment by dschonholtz** [comment]
I like your class. 
I just put together the code mentioned above on #122 for using pinecone. 
It might make sense to put these both on the same interface and/or we could consider something like dumping text to sql and just putting the embeddings in pinecone.
Currently, I am sending up the raw text as meta data and it would be better to store that locally so we don't store more crap in pinecone than we need to and so we can query stuff locally. 

It might be worth doing something like:
1. Store raw memory data locally in sql mapped to a vector id
2. Query for relevant memories in pinecone which returns vector id so we can query sql from it.
3. Make a start up option to push local sql to pinecone embeddings. 

Just some thoughts. Also, wanted to make sure we could make the merge conflict situation less painful and make sure we work together on whatever solution we come up with if we do take both PRs

**Comment by EricFedrowisch** [comment]
@dschonholtz Glad to see https://github.com/Torantulino/Auto-GPT/pull/122 . I'd see this pr as analogous to your SimpleMemory class and/or a local cache. I'm not familiar with pinecone, currently using llama_index for my experiments. So, gonna leave decisions revolving around that to others with more experience.  
This repo is a viral success, pull requests and issues are coming in way faster than one person can likely deal with. So many changes are coming in, so fast that it seems likely that  merges are going to be painful for a while. @Torantulino needs some time to have a chance to communicate his vision.

**Comment by jdonkers** [comment]
I tested this code and believe there's be a bug. The memory addresses are being input to the prompt, rather than the memory itself.

Example:
`{'role': 'system', 'content': 'Permanent memory: <memory.MemoryDB object at 0x00000174FEDD3F40>'}`

**Comment by ryanpeach** [comment]
If we do choose to use a SQL database, I'd at least petition that we use an adaptor. I have plans to use autogpt on k8s with multiple instances talking to one another in the future. I believe the database should be Horizontally Autoscalable. In the SQL world, the best database for that is Postgres. If we implemented the option to use sqlalchemy, or something similar, then the database could be customizable by the user.

I think another thing is making the memory modular. We will apparently obviously disagree on database implementations. Maybe the only solution to that is to create a database folder, a class interface, and then just a bunch of implementations, with a CLI flag or config file for the user choice.

**Comment by EricFedrowisch** [comment]
I'll check it out, @jdonkers and do another commit. My guess is I need to do a __repr__ so that it can return a string for the current session text.

**Review by nponeccop — CHANGES_REQUESTED** [review]
Rebase against the current master

**Comment by merwanehamadi** [comment]
@jdonkers this would be dope, there's a bunch of things like commands, ai_settings, all that stuff that would be perfect insqlite instead of a file systems. Then after nothing prevents us from wrapping this in an orm and use postgres, for people who want to scale.

**Review by BillSchumacher — APPROVED** [review]

**Pull request merged**
