### PR TITLE
[Style]: Change imports

### PR DESCRIPTION
**Pull request by AndresCdo**
### Background
There are several imports are not necessary.

### Changes
Any file imports just what is necessary.

### CODE REVIEW

**Comment by BillSchumacher** [comment]
Please do a ```pre-commit install``` to fix linting.

**Comment by nponeccop** [comment]
@AndresCdo There are conflicts now

**Comment by nponeccop** [comment]
@AndresCdo CI is red

**Comment by nponeccop** [comment]
@AndresCdo CI is red

**Comment by BillSchumacher** [comment]
LGTM the time patch is broken though

**Comment by AndresCdo** [comment]
@BillSchumacher @nponeccop Why checks failed?

**Comment by Pwuts** [comment]
PR adds more characters than it removes, and adds linting errors. Closing.

**Pull request closed without merging**
