### PR TITLE
refactoring all json utilities

### PR DESCRIPTION
**Pull request by bingoko**
### Background

This pull request addresses the need to refactor and consolidate all JSON-related functions into a few utility files under the JSON Utils module. Previously, these functions were scattered across various JSON modules and functions, making it difficult to maintain and understand the codebase. This change is in line with the project's overall goal of improving maintainability, readability, and structure.

### Changes

- Created a new `json_utils` module to house all JSON-related utility functions.
- Moved existing JSON functions from their scattered locations into the `json_utils` module.
- Refactored and optimized the JSON functions for better readability and maintainability.

### Documentation

- Added in-code comments to explain the purpose and functionality of each JSON utility function in the `json_utils` module.

### Test Plan

- Manually tested each JSON utility function with a variety of JSON inputs to ensure they function as expected.
- Updated existing unit tests to reference the new module and function locations.
- No new tests were added since the changes only involved refactoring existing functions and no new functionality was introduced.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by nponeccop** [comment]
@merwanehamadi

**Comment by merwanehamadi** [comment]
@bingoko Great thanks a lot. I tested it and also the unit tests keep passing.
There is just one issue I don't know if it also bugs you: 
- our unit tests are not testing the right method that wraps everything
- our unit tests call the ai magic function which means it's going to cost tokens or we're going to need to mock that. It would be so nice to have the a separate ai function from the non ai functions, so we can load as many unit tests as we need on the non ai function.

But this approved, if you could help us with what's above after this is merged, that would be awesome

**Review by merwanehamadi — DISMISSED** [review]

**Comment by bingoko** [comment]
> 
You're welcome! I've taken your feedback into account and have now split the functions into AI and non-AI functions. This should make it easier to test the non-AI functions without incurring token costs or the need to mock the AI magic function.

Cheers!

**Comment by bingoko** [comment]
> @bingoko I have an issue running the agent Screenshot 2023-04-17 at 4 09 08 PM

done

**Review by merwanehamadi — APPROVED** [review]

**Review by BillSchumacher — APPROVED** [review]

**Pull request merged**
