### PR TITLE
[UX] Magic CLI with docker integration and bootstrapping capability

### PR DESCRIPTION
**Pull request by lc0rp**
Draft  fix for #4604 UX magic cli start.

See #4604 and comment: https://github.com/Significant-Gravitas/Auto-GPT/issues/4604#issuecomment-1586693825

This PR kicks off the bootstrapping fx:
1. Enables a system command (autogpt)
2. Encourages "pip install agpt" and attempts to install "pip install -e ." if detected
3. Deprecates workspace directories that are subdirectories of ```Auto-GPT```
4. Offers to move workspace directory to ```$HOME```

Next:
1. Prompt for workspace directory if omitted
2. Check for OpenAI key and prompt the user if needed
3. Prompt for installation method: Docker, venv or dev-container.
4. Kick off 

Qns:
1. Should the workspace directory be an argument (```autogpt test_project```) or a CMD line option (```autogpt --workspace-directory test_project```)?
2. Should we check other settings? E.g. we could parse the env-template and ask for values for all non-commented constants?

```

### CODE REVIEW

**Comment by dwrtz** [comment]
from my ai maintainer bot `🦾`
```
Request Changes

Hello and thank you for your contribution! Your pull request is almost acceptable, but there are a few changes needed before we can proceed:

1. In the PR description, please provide a more detailed explanation of the changes you've made and how they address the issue. This will help us better understand the scope of your proposed changes.

2. In the `check_installation` function, there is a typo in the argument `interative`. It should be `interactive`.

Once these changes are made, we can proceed with reviewing your pull request. Thank you for your understanding and cooperation!
```

**Comment by Pwuts** [comment]
@lc0rp what's the status of this cool thing? :)

**Comment by lc0rp** [comment]
Closing in favor of https://github.com/Significant-Gravitas/Auto-GPT/issues/5003

**Comment by lc0rp** [comment]
> @lc0rp what's the status of this cool thing? :)

I'm bad at checking messages. We're merging this work into #5003

**Pull request closed without merging**
