### PR TITLE
Added support for using chatgpt reverse engineered api

### PR DESCRIPTION
**Pull request by Jordan-Mesches**
Added the ablity for user to chose chatgpt as the llm that powers their auto-gpt instance. It's only an option for create_chat_completion, not create_embedding, so some charges will still occur, however, it will be significantly less than before.
### Background

Running auto-gpt can be costly so offering another way to make calls to GPT seemed imperative, also allows chatgpt-plus users a way to get their 20 bucks worth and be able to use auto-gpt with gpt4.
### Changes

--> Modified create_chat_completion in llm_utils to take a parameter of 'use_chatgpt'.
--> Modified chat_with_ai, message_agent and create_agent to pass cfg.use_chatgpt
--> Modified Config to have use_chatgpt flag and openai_chatgpt_access_token var
--> Modified env_template to include a place to define openai_chatgpt_access_token
### Documentation

Only create_chat_completion was significantly modified so added doc string for use_chatgpt flag
### Test Plan

Manually tested. Do note that with the current implementation, a new chat will be created every time create_chat_completion is called with use_chatgpt true. Also once use_chatgpt is used once, you can't revert back to regular api in that instance's execution. 

To get your access token: login to chatgpt, than visit https://chat.openai.com/api/auth/session
### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes 

It's not really testable as there's no logic other than trivially adapting messages to a format chatgpt expects

### CODE REVIEW

**Comment by Jordan-Mesches** [comment]
Needs more work to not completely screw up your chatgpt convo list also needs to be cleaned up (putting adapter in a separate area), but I figured that'd require me to change too much and wanted to keep the commit as small as possible.

**Review by nponeccop — COMMENTED** [review]
It doesn't look very ethical or complying with AUP. Once plugins are implemented, you can plug all sorts of dirty things, just not in the core.

**Comment by p-i-** [comment]
I don't feel comfortable with incorporating this.
Yes a logic is there for it. People will want it. But there is also logic against. We don't want to be providing backdoors to services -- likely against the wishes of the service provider. That doesn't seem a harmonious path forwards.
For now let's trust that LLM-access availability will improve.
If we need to cycle back to this, so be it.

**Comment by btcjon** [comment]
Is this functioning? Can it access my GPT4 plus account?

**Pull request closed without merging**
