### PR TITLE
Rearrange tests & fix CI

### PR DESCRIPTION
**Pull request by Pwuts**
### Background
* Not all tests are in the right location (`tests/` vs `tests/(unit|integration)/`)
* Challenges are run as part of the integration tests, while it can be useful to run only integration tests and not the challenges
* We have a bunch of bogus unit tests which contribute more headache than valuable test coverage
* Docker CI will succeed even if some of the tests fail

### Changes
- [x] Rearrange all tests into `tests/unit`, `tests/integration` and `tests/challenges`
  * Some tests also moved from `tests/integration` to `tests/unit`
- [x] Clean up bogus unit tests
- [x] Reduce Docker CI to only run unit+integration tests
- [x] Fix Docker CI to actually fail when the tests fail

**Other changes:**
* Fixed `get_text_summary` which broke in #4328

### Documentation
References to `tests/integration/challenges` or `tests.integration.challenges` in docs were also updated.

### Test Plan
Run CI and check result + coverage

### PR Quality Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [ ] I have not snuck in any "extra" small tweaks changes. 
- [x] I have run the following commands against my code to ensure it passes our linters:
    ```shell
    black .
    isort .
    mypy
    autoflake --remove-all-unused-imports --recursive --ignore-init-module-imports autogpt tests --in-place
    ```

### CODE REVIEW

**Comment by Pwuts** [comment]
Someone will have to take a look at `test_json_parser.py` and `_test_json_parser.py`, determine what we actually want `fix_and_parse_json()` to be capable of, and consolidate.

**Review by ntindle — APPROVED** [review]
Make sure the mypy config is updated

**Comment by ntindle** [comment]
> Someone will have to take a look at `test_json_parser.py` and `_test_json_parser.py`, determine what we actually want `fix_and_parse_json()` to be capable of, and consolidate.

We should make a new issue for this rather than holding this one up

**Review by merwanehamadi — APPROVED** [review]

**Review by merwanehamadi — APPROVED** [review]

**Comment by merwanehamadi** [comment]
> > Someone will have to take a look at `test_json_parser.py` and `_test_json_parser.py`, determine what we actually want `fix_and_parse_json()` to be capable of, and consolidate.
> 
> We should make a new issue for this rather than holding this one up

https://github.com/Significant-Gravitas/Auto-GPT/issues/4597

**Pull request merged**
