### PR TITLE
fix #1363

### LINKED ISSUE #1363: execute_python_file no such file or directory
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Set a goal that ends up writing a python file to take some action 

wait for auto-gpt to try that action 

### Current behavior 😯

Getting the error 

Executing file 'data_analysis.py' in workspace 'auto_gpt_workspace'
SYSTEM:  Command execute_python_file returned: Error: File 'data_analysis.py' does not exist.

### Expected behavior 🤔

The python script executes

### Your prompt 📝

```yaml
# Create a list of every museum in the UK
```

### PR DESCRIPTION
**Pull request by nobita2041**
### Background
Investigate the missing python executable error reported in #1363,#1896, etc.

### Changes.
Correct file path specification.

### Test Plan
We have verified that it runs correctly after the modification. Here is the prompt I used

- Create a python script that outputs "Hello world"
- Save and run the script file.
- Save the script file and run it.

### CODE REVIEW

**Comment by Pwuts** [comment]
Have you tested this? Neither of the referenced issues will be fixed by this PR, see https://github.com/Significant-Gravitas/Auto-GPT/issues/1363#issuecomment-1509302152 and https://github.com/Significant-Gravitas/Auto-GPT/issues/1896#issuecomment-1510395793.

**Comment by Pwuts** [comment]
Also conflicts with #1875

**Comment by Pwuts** [comment]
But it does solve the issue of `execute_shell` :)

**Review by zhayujie — APPROVED** [review]
It is necessary to add a parent here, otherwise the path of worksapce is autogpt/auto_gpt_workspace.

**Comment by Pwuts** [comment]
@nponeccop I would advise to either merge #1947 or this PR, but not both, since they solve the same problem and conflict with each other in that sense.

**Comment by nponeccop** [comment]
@nobita2041 There are conflicts now. We merged another PR fixing the same issue, so think if you have anything to add, and if not, close this one.

**Comment by p-i-** [comment]
Closing as fixed by https://github.com/Significant-Gravitas/Auto-GPT/pull/1947

**Pull request closed without merging**
