### PR TITLE
Adding version control operations & react operations(SWE Agent?) Help wanted!

### PR DESCRIPTION
**Pull request by atj3097**
### Background
Hey everyone, I saw some Twitter posts about people being able to install react apps and what not but didn't seem to be able to get it to work on my end. So, I took a stab at creating a module for working with react apps and adding github versioning functions. If anyone has any input or is willing to help me test this please ping me! 

Don't know how safe it is to update the prompt either, seems to "on the nose"

### Changes
This pull request adds the following changes:

- Added react_operations.py module for React app management
- Added git_operations.py module for GitHub repository management
- Added environment variables for GitHub username and PAT in the .env file
- Updated the execute_command() function to include new React and GitHub commands in the AI agent prompt

### Test Plan
WIP(will circle back on this on Friday evening)

### Change Safety

- [ ] I have added tests to cover my changes
- [ ] I have considered potential risks and mitigations for my changes

### CODE REVIEW

**Comment by nponeccop** [comment]
You need to rebase it on top of current master

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Boostrix** [comment]
See also #3815

**Comment by ntindle** [comment]
Hello!  We sincerely appreciate your contribution to our project. Please note that only essential features will be merged into the main repository. Thus, we encourage you to open a pull request in the [Auto-GPT-Plugins](https://github.com/Significant-Gravitas/Auto-GPT-Plugins) repository.  If you encounter difficulties converting your code into a plugin, please do not hesitate to seek assistance from the #plugins-chat on our Discord Server.  We look forward to your contribution to the Plugins repository and apologize for any inconvenience this may have caused.

**Pull request closed without merging**
