### PR TITLE
Fix problematic check_duplicate_operation and calls

### PR DESCRIPTION
**Pull request by rocks6**
### Background
Many issues (https://github.com/Significant-Gravitas/Auto-GPT/issues/1891#issuecomment-1519176961) have been spawned from the fact that check_duplicate_operation will prevent you from writing, appending, or deleting the same file more than once.

### Changes
Removed the offending method and calls. I attempted to pursue a solution where we hashed the content and added it to each line of the file logging command, but then realized there were still cases where this would break (if we appended the same text to the same file twice, which is a perfectly valid operation and common as well). So, just removed the offending code.

### Documentation
Code removed

### Test Plan
Ran unittests and prompt asking chatGPT to test the specific scenario

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by Pwuts** [comment]
Please check out #1891. The solution we are looking for is not to remove the logger, but to fix it.

**Review by Pwuts — CHANGES_REQUESTED** [review]
Please fix the logger instead of removing it

**Comment by rocks6** [comment]
> Please fix the logger instead of removing it

I can implement the suggestion you had on the other there where we hash the content and add this to the log line. However, for append_file, there are many cases where we need to add the same exact content to the same file which will break even with the new changes. I don't think appending the same text to the same file that we have in the past should be an error condition, what do you think?

**Comment by rocks6** [comment]
> > there are many cases where we need to add the same exact content to the same file
> 
> Do you have an example?
> 
> This feature was implemented because agents would regularly end up in infinite loops, performing the same file operation over and over. That function should be preserved.
> 
> I think a large fraction of the "duplicate operation" errors can be mitigated by reading/parsing the log in a way that makes sure only the last relevant operations are taken into account to determine whether it is a duplicate or not. Ideas:
> 
> * Parsing logic that ignores operations which have already been overwritten (e.g. write -> delete or vice versa)
> * Let the function provide clear feedback to the LLM
>   
>   * "This content has already been written to the file. Continue to the next step."

Sure, here's one example. I would like an agent to track the price of a stock every 5 minutes and record it to a file. The stock starts at 100, goes to 105, then drops back down to 100:

write stocks.txt-427BB37B82189ED44CE979C59AA1CF3CDA2BBA42300B00743B0DA5EB14A63164
write stocks.txt-0F15C9804218AAFA9CA7E824F513AAB92797F4F24BA73A7FC6379559904B1768
write stocks.txt-427BB37B82189ED44CE979C59AA1CF3CDA2BBA42300B00743B0DA5EB14A63164 -> throws

This is easily solved by adding a timestamp from the client side to the appending content, but it may be a sub-par user experience on the way to finding a solution. 

If the infinite loops are as big of an issue as you say, I agree we should keep it. I've updated the PR with the first steps (adding hash to log entries) and will see if we need to add a richer experience this week

**Comment by rocks6** [comment]
> > I would like an agent to track the price of a stock every 5 minutes and record it to a file. The stock starts at 100, goes to 105, then drops back down to 100:
> 
> Something tells me there are less resource-intensive ways to do that ;)
> 
> But I get your point.

For sure, typing it out makes me realize how silly it sounds. Either way, I re-added it for now, take a look

**Comment by Pwuts** [comment]
@bobisme has made a pretty clean PR fixing this with checksums as well. Can you please review that @rocks6? It looks to be more complete than this PR, but I would be happy to get your input on it.

Closing this PR as superseded by #3489

**Comment by rocks6** [comment]
Sounds good, I'll take a look

**Pull request closed without merging**
