### PR TITLE
Make Google Search command optional

### PR DESCRIPTION
**Pull request by kendallc**
### Background

This change allows the Google Search API and command to be configurable

### Changes

Adds the USE_GOOGLE_API environment variable in the .env.template and config file

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Review by nponeccop — CHANGES_REQUESTED** [review]
The PR title is misleading. Should be something like "Make Google Search command optional". It's what the PR does. Config is how it does what it does. And Google API isn't affected by the PR at all. So just re-title and rename the vars.

**Comment by nponeccop** [comment]
@richbeales @p-i- ?

**Comment by kendallc** [comment]
Please hold off on reviewing for now, I need to do some more testing

**Comment by kendallc** [comment]
Declining as this is already addressed in the latest master by checking for an existing Google API key

**Pull request closed without merging**
