### PR TITLE
Prompt file update for more specific command identification

### PR DESCRIPTION
**Pull request by robinicus**
Taking inspiration from the method that Langchain uses to instruct the bot on which tool to use, I've fleshed out each of the tools with a brief description to help the bot make a better decision. In testing it appears to work well and the bot seems to find its way to the goal faster.

### CODE REVIEW

**Comment by robinicus** [comment]
Fyi, here's what I was referring to regarding Langchain: https://python.langchain.com/en/latest/modules/agents/agents/examples/mrkl_chat.html - note their descriptions next to each tool.

**Comment by ryanmac** [comment]
Recommended change in PR https://github.com/Torantulino/Auto-GPT/pull/170 to switch the command and thoughts.

**Comment by Torantulino** [comment]
The prompt did actually use to be like this, but I reduced it to reduce the token count. I suppose it's probably a good trade-off though.

Will Benchmark!

**Comment by nponeccop** [comment]
Rebase against the current master, please.

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by merwanehamadi** [comment]
@robinicus we're currently building challenges in order to measure the effect of these types of changes, and I would like to discuss with you.

Please join use on Discord through this link https://discord.gg/autogpt (if not already)

DM me on the Auto-GPT discord channel (my discord is merwanehamadi).

**Comment by Boostrix** [comment]
You might also want to take a look at the following recent comments (look at the summary that @valayDave come up with):

- https://github.com/Significant-Gravitas/Auto-GPT/issues/2987#issuecomment-1528954237
- https://github.com/Significant-Gravitas/Auto-GPT/issues/2987#issuecomment-1537055761
- https://github.com/Significant-Gravitas/Auto-GPT/issues/2987#issuecomment-1536929354

**Comment by Boostrix** [comment]
See:

#3954

**Comment by Pwuts** [comment]
Closing in favor of #4683 :)

**Pull request closed without merging**
